In [1]:
import pandas as pd
import numpy as np
import cpi
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import seaborn as sns

# # %pip install cpi
# cpi.update()

## IMPORTAR DATASETS

In [2]:
# Load Dataframes
print("Loading raw data...")

DATA_FILE_FACTS = 'data/raw_facts_500.pkl'
DATA_FILE_SONGS = 'data/raw_songs_500.pkl'
DATA_FILE_MOVIES = 'data/raw_movies_500.pkl'
DATA_FILE_ARTISTS = 'data/raw_artists_500.pkl'

df_facts_raw = pd.read_pickle(DATA_FILE_FACTS)
df_songs_raw = pd.read_pickle(DATA_FILE_SONGS)
df_movies_raw = pd.read_pickle(DATA_FILE_MOVIES)
df_artists_raw = pd.read_pickle(DATA_FILE_ARTISTS)

print("Data loaded! Ready for transformations...")
display(df_facts_raw.head())

Loading raw data...
Data loaded! Ready for transformations...

   song_id  year           song_title            film_title  film_id
0   193401  1934      The Continental      The Gay Divorcee   193401
1   193402  1934        Love In Bloom      She Loves Me Not   193402
2   193501  1935  Lullaby Of Broadway  Gold Diggers of 1935   193501
3   193502  1935       Cheek To Cheek               Top Hat   193502
4   193503  1935    Lovely To Look At               Roberta   193503

### Inspección de los Datasets

In [3]:
print(df_songs_raw.columns)
# display(df_songs_raw[['song_id', 'song_title', 'oscar_song_nominee', 'oscar_song_win']].head())

print(df_movies_raw.columns)
# display(df_movies_raw[['film_id', 'film_title', 'tmdb_budget', 'tmdb_revenue', 'omdb_awards']].head())

print(df_artists_raw.columns)
# display(df_artists_raw[['artist_id', 'artist_name', 'artist_playcount', 'artist_listeners']].head())

Index(['song_id', 'year', 'song_title', 'song_composers', 'song_lyricists',
       'original_artists', 'streams_original', 'other_artists',
       'streams_others', 'oscar_song_nominee', 'oscar_song_win',
       'grammy_song_nominee', 'grammy_song_win', 'grammy_record_nominee',
       'grammy_record_win', 'spotify_id', 'spotify_track_title',
       'spotify_artists', 'spotify_album_title', 'spotify_release_date',
       'spotify_duration_ms', 'isrc', 'lastfm_track_title',
       'lastfm_artist_name', 'lastfm_track_playcount',
       'lastfm_track_listeners', 'lastfm_tags', 'lastfm_track_url',
       'lastfm_duration_ms', 'track_mbid', 'artist_mbid', 'lastfm_album_title',
       'lastfm_album_artist', 'wiki_summary', 'mb_work_id', 'mb_work_title',
       'mb_iswcs', 'mb_composers', 'mb_lyricists', 'mb_total_recordings',
       'mb_original_recordings_count', 'mb_cover_recordings_count',
       'mb_covers_performers_count', 'mb_covers_performers_top',
       'mb_covers_earliest_year', 'mb_covers_earliest_performer',
       'mb_covers_latest_year', 'mb_covers_latest_performer',
       'lastfm_duration', 'match_key_am', 'match_key_cm', 'am_ranking',
       'am_song_artist', 'am_song_year', 'cm_ranking', 'cm_song_artist',
       'cm_song_eas'],
      dtype='str')
Index(['film_id', 'year', 'film_title', 'film_directors', 'film_composers',
       'oscar_nominations', 'oscar_wins', 'tmdb_id', 'imdb_id',
       'tmdb_official_title', 'tmdb_original_title', 'tmdb_release_date',
       'tmdb_runtime', 'tmdb_budget', 'tmdb_revenue', 'tmdb_vote_average',
       'tmdb_vote_count', 'tmdb_original_language', 'tmdb_origin_countries',
       'tmdb_actors', 'tmdb_directors', 'tmdb_composers',
       'tmdb_production_companies', 'tmdb_genres', 'tmdb_tagline',
       'omdb_title', 'omdb_awards', 'omdb_imdb_rating', 'omdb_imdb_votes',
       'omdb_metascore', 'omdb_rotten_tomatoes'],
      dtype='str')
Index(['artist_id', 'artist_name', 'roles', 'mb_artist_id', 'artist_playcount',
       'artist_listeners', 'artist_bio', 'mb_artist_type', 'mb_gender',
       'mb_country', 'mb_begin_area', 'mb_disambiguation', 'mb_lifespan_begin',
       'mb_lifespan_end', 'mb_is_active', 'mb_isnis', 'mb_aliases', 'mb_tags',
       'mb_wikidata_url', 'mb_imdb_url', 'match_artist_cm',
       'cm_artist_ranking', 'cm_artist_eas'],
      dtype='str')

### Dataframes Auxiliares

In [4]:
# Songs Dataframe
df_songs_aux = pd.DataFrame()

columns_to_keep = [
    'song_id', 'song_title', 'year',
    'lastfm_track_playcount', 'lastfm_track_listeners',
    'oscar_song_nominee', 'oscar_song_win',
    'grammy_song_nominee', 'grammy_song_win',
    'grammy_record_nominee', 'grammy_record_win',
    'song_composers', 'song_lyricists',
    'original_artists', 'streams_original', 
    'other_artists', 'streams_others', 
    'spotify_release_date', 'spotify_duration_ms',
    # 'spotify_id', 'isrc',
    'spotify_track_title', 'spotify_artists', 'spotify_album_title', 
    'lastfm_track_title', 'lastfm_artist_name', 'lastfm_album_title', 
    # 'lastfm_album_artist', 'lastfm_track_url', 'lastfm_duration_ms', 
    # 'track_mbid', 'artist_mbid', 
    'lastfm_tags', 'wiki_summary', 
    # 'mb_work_id', 'mb_iswcs',
    'mb_work_title', 'mb_composers', 'mb_lyricists', 
    'mb_total_recordings', 'mb_original_recordings_count', 'mb_cover_recordings_count',
    'mb_covers_performers_count', 'mb_covers_performers_top',
    'mb_covers_earliest_year', 'mb_covers_earliest_performer',
    'mb_covers_latest_year', 'mb_covers_latest_performer', 
    'am_ranking', 'am_song_artist', 'am_song_year', 
    'cm_ranking', 'cm_song_artist', 'cm_song_eas',
    'match_key_am', 'match_key_cm'
]

df_songs_aux = df_songs_raw[columns_to_keep].copy()

# Films Dataframe
df_films_aux = pd.DataFrame()

columns_to_keep = [
    'film_id', 'year', 'film_title', 'film_directors', 'film_composers',
    'oscar_nominations', 'oscar_wins', 
    # 'tmdb_id', 'imdb_id',
    'tmdb_official_title', 'tmdb_original_title', 'tmdb_release_date',
    'tmdb_runtime', 'tmdb_budget', 'tmdb_revenue', 'tmdb_vote_average',
    'tmdb_vote_count', 'tmdb_original_language', 'tmdb_origin_countries',
    'tmdb_actors', 'tmdb_directors', 'tmdb_composers',
    'tmdb_production_companies', 'tmdb_genres', 'tmdb_tagline',
    'omdb_title', 'omdb_awards', 'omdb_imdb_rating', 'omdb_imdb_votes',
    'omdb_metascore', 'omdb_rotten_tomatoes'
]

df_films_aux = df_movies_raw[columns_to_keep].copy()

# Artists Dataframe
columns_to_keep = [
    'artist_id', 'artist_name', 'roles', # 'mb_artist_id', 
    'artist_playcount', 'artist_listeners', 
    'artist_bio', 'mb_artist_type', 'mb_gender',
    'mb_country', 'mb_begin_area', 'mb_disambiguation', 
    'mb_lifespan_begin', 'mb_lifespan_end', 'mb_is_active', # 'mb_isnis', 
    'mb_aliases', 'mb_tags', # 'mb_wikidata_url', 'mb_imdb_url', 
    'cm_artist_ranking', 'cm_artist_eas'
]

df_artists_aux = df_artists_raw[columns_to_keep].copy()

### Comprobaciones de Calidad

In [5]:
"""
df_songs_aux[['spotify_artists', 'lastfm_artist_name', 
              'streams_original', 'streams_others', 
              'lastfm_track_playcount','lastfm_track_listeners', 
              'mb_total_recordings', 'mb_original_recordings_count',
              'mb_cover_recordings_count', 'mb_covers_performers_count',
              'am_ranking', 'am_song_artist', 'cm_ranking', 'cm_song_artist', 
              'cm_song_eas']].info()
"""

# Display Missing Artists
missing_mask = df_songs_aux['spotify_artists'].isna() | df_songs_aux['lastfm_artist_name'].isna()

cols_to_view = [
    'song_id', 'song_title', 
    'original_artists', 'other_artists',
    'spotify_artists', 'lastfm_artist_name',
    'streams_original', 'streams_others'
]

# Apply the filter and view the results
df_missing = df_songs_aux.loc[missing_mask, cols_to_view]
# print(df_missing.shape)
display(df_missing)

,song_id,song_title,original_artists,other_artists,spotify_artists,lastfm_artist_name,streams_original,streams_others
25,194003,Down Argentina Way,"Betty Grable, Don Ameche",NaN,NaN,NaN,12700.0,NaN
133,196304,So Little Time,Andy Williams,NaN,NaN,NaN,189900.0,NaN
198,197403,Benji's Theme (I Feel Love),Euel Box,NaN,[Euel Box],NaN,30500.0,NaN
257,198304,Over You,Betty Buckley,NaN,NaN,NaN,NaN,NaN
285,198605,Mean Green Mother from Outer Space,Levi Stubbs,NaN,NaN,NaN,5905000.0,NaN
311,199001,Sooner Or Later (I Always Get My Man),Madonna,NaN,NaN,NaN,2190000.0,NaN
315,199005,I'm Checkin' Out,"Meryl Streep, Blue Rodeo",NaN,NaN,NaN,NaN,NaN
330,199304,The Day I Fall In Love,"Dolly Parton, James Ingram",NaN,NaN,NaN,17919000.0,NaN
337,199405,Look What Love Has Done,Patty Smyth,NaN,NaN,NaN,NaN,NaN
342,199505,Moonlight,Michael Dees,NaN,NaN,NaN,NaN,NaN
369,199905,Blame Canada,Geek Music,NaN,[Geek Music],NaN,894700.0,NaN
396,200405,In The Deep,Bird York,NaN,NaN,NaN,NaN,NaN
397,200406,Look To Your Path (Vois Sur Ton Chemin),Bruno Coulais,NaN,NaN,NaN,65695000.0,NaN
398,200501,It's Hard Out Here For A Pimp,"Three 6 Mafia, Paula Campbell",NaN,NaN,NaN,26000000.0,NaN
497,202503,Train Dreams,Sierra Ferrell,NaN,NaN,NaN,1660000.0,NaN

In [6]:
# Display Missing Streams
missing_mask = df_songs_aux['streams_original'].isna() & df_songs_aux['streams_others'].isna()

cols_to_view = [
    'song_id', 'song_title', 'original_artists',
    'spotify_artists', 'lastfm_artist_name',
    'streams_original', 'streams_others',
    'lastfm_track_playcount','lastfm_track_listeners'
]

# Apply the filter and view the results
df_missing = df_songs_aux.loc[missing_mask, cols_to_view]
display(df_missing)

,song_id,song_title,original_artists,spotify_artists,lastfm_artist_name,streams_original,streams_others,lastfm_track_playcount,lastfm_track_listeners
251,198204,If We Were In Love,"Luciano Pavarotti, John Williams","[John Williams, Boston Pops Orchestra]",Luciano Pavarotti,NaN,NaN,762.0,207.0
257,198304,Over You,Betty Buckley,NaN,NaN,NaN,NaN,NaN,NaN
315,199005,I'm Checkin' Out,"Meryl Streep, Blue Rodeo",NaN,NaN,NaN,NaN,NaN,NaN
337,199405,Look What Love Has Done,Patty Smyth,NaN,NaN,NaN,NaN,NaN,NaN
342,199505,Moonlight,Michael Dees,NaN,NaN,NaN,NaN,NaN,NaN
396,200405,In The Deep,Bird York,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# Acclaimed Music matched songs quality check
mask = df_songs_aux['am_ranking'].notna()

cols_to_view = [
    'song_id', 'original_artists',
    'am_song_artist', 'year', 'am_song_year'
]

df_aux = df_songs_aux.loc[mask, cols_to_view]
print(df_aux.to_string())

     song_id                   original_artists                     am_song_artist  year  am_song_year
5     193601                       Fred Astaire                       Fred Astaire  1936          1936
7     193603                        Bing Crosby                        Bing Crosby  1936          1936
11    193702                       Fred Astaire                       Fred Astaire  1937          1937
21    193901                       Judy Garland                       Judy Garland  1939          1939
23    194001                      Cliff Edwards                      Cliff Edwards  1940          1940
33    194103                       Glenn Miller                       Glenn Miller  1941          1941
36    194106                The Andrews Sisters                The Andrews Sisters  1941          1941
39    194201                        Bing Crosby                        Bing Crosby  1942          1942
48    194401                        Bing Crosby                        Bing Crosby  1944          1944
51    194404                       Judy Garland                       Judy Garland  1944          1944
68    194802                          Doris Day                          Doris Day  1948          1948
73    195001                      Nat King Cole                      Nat King Cole  1950          1950
75    195003       Mario Lanza, Kathryn Grayson                        Mario Lanza  1950          1950
83    195301                          Doris Day                          Doris Day  1953          1953
84    195302                        Dean Martin                        Dean Martin  1953          1953
87    195402                       Judy Garland                       Judy Garland  1954          1954
91    195501                      The Four Aces                      The Four Aces  1955          1955
100   195701                      Frank Sinatra                      Frank Sinatra  1957          1957
105   195712                      Elvis Presley                      Elvis Presley  1957          1957
124   196104                        Gene Pitney                        Gene Pitney  1961          1961
141   196412                        The Beatles                        The Beatles  1964          1964
142   196413                     Shirley Bassey                     Shirley Bassey  1964          1964
145   196503                          Tom Jones                          Tom Jones  1965          1965
149   196513                        The Beatles                        The Beatles  1965          1965
155   196612                      Frank Sinatra                      Frank Sinatra  1966          1966
157   196702                  Dusty Springfield                  Dusty Springfield  1967          1967
161   196712                  Simon & Garfunkel                Simon and Garfunkel  1967          1968
162   196713                      Nancy Sinatra                      Nancy Sinatra  1967          1967
169   196901                       B. J. Thomas                        B.J. Thomas  1969          1969
174   197001         Carpenters, Larry Meredith                         Carpenters  1970          1971
178   197101                        Isaac Hayes                        Isaac Hayes  1971          1971
185   197202                    Michael Jackson                    Michael Jackson  1972          1972
187   197301                   Barbra Streisand                   Barbra Streisand  1973          1973
192   197312                          Bob Dylan                          Bob Dylan  1973          1973
205   197504                         Diana Ross                         Diana Ross  1975          1975
211   197702                        Carly Simon                        Carly Simon  1977          1977
215   197713                           Bee Gees                           Bee Gees  1977          1977
216   197714                           Bee Gees                           Bee Gees  1977          1977
217   197715                           Bee Gees                           Bee Gees  1977          1977
218   197716                           Bee Gees                           Bee Gees  1977          1977
220   197801                       Donna Summer                       Donna Summer  1978          1978
226   197812                      Frankie Valli                      Frankie Valli  1978          1978
233   198001                         Irene Cara                         Irene Cara  1980          1980
235   198003                      Willie Nelson                      Willie Nelson  1980          1980
236   198004                       Dolly Parton                       Dolly Parton  1980          1980
239   198013                            Blondie                            Blondie  1980          1980
240   198014                         Paul Simon                         Paul Simon  1980          1980
241   198015                       Neil Diamond                       Neil Diamond  1980          1980
243   198101                  Christopher Cross                  Christopher Cross  1981          1981
250   198203                           Survivor                           Survivor  1982          1982
253   198212                        David Bowie                        David Bowie  1982          1982
254   198301                         Irene Cara                         Irene Cara  1983          1983
262   198401                      Stevie Wonder                      Stevie Wonder  1984          1984
263   198402                       Phil Collins                       Phil Collins  1984          1984
264   198403                      Kenny Loggins                      Kenny Loggins  1984          1984
265   198404                   Deniece Williams                   Deniece Williams  1984          1984
266   198405                     Ray Parker Jr.                     Ray Parker Jr.  1984          1984
272   198501                      Lionel Richie                      Lionel Richie  1985          1985
274   198503              Huey Lewis & The News            Huey Lewis and The News  1985          1985
278   198513                            Madonna                            Madonna  1985          1985
280   198515                        Duran Duran                        Duran Duran  1985          1985
281   198601                             Berlin                             Berlin  1986          1986
286   198612                      Kenny Loggins                      Kenny Loggins  1986          1986
287   198613                              Queen                              Queen  1986          1986
289   198615  Orchestral Manoeuvres In The Dark  Orchestral Manoeuvres in the Dark  1986          1986
291   198617                            Madonna                            Madonna  1986          1986
293   198702                           Starship                           Starship  1987          1987
299   198714                            Madonna                            Madonna  1987          1987
301   198801                        Carly Simon                        Carly Simon  1988          1989
310   198912                      Gladys Knight                      Gladys Knight  1989          1989
319   199104                        Bryan Adams                        Bryan Adams  1991          1991
320   199112                       Eric Clapton                       Eric Clapton  1991          1992
323   199202                    Whitney Houston                    Whitney Houston  1992          1992
327   199301                  Bruce Springsteen                  Bruce Springsteen  1993          1993
350   199701                        Céline Dion                      Cï¿½line Dion  1997          1997
351   199702                      Elliott Smith                      Elliott Smith  1997          1997
360   199802                          Aerosmith                          Aerosmith  1998          1998
364   199812                  The Goo Goo Dolls                      Goo Goo Dolls  1998          1998
366   199902                         Aimee Mann                         Aimee Mann  1999          1999
371   200001                          Bob Dylan                          Bob Dylan  2000          2000
381   200201                             Eminem                             Eminem  2002          2002
386   200212                            Madonna                            Madonna  2002          2002
433   201302                  Pharrell Williams                  Pharrell Williams  2013          2013
460   201802                Kendrick Lamar, SZA               Kendrick Lamar & SZA  2018          2018

In [8]:
# Chart Masters matched songs quality check
mask = df_songs_aux['cm_ranking'].notna()

cols_to_view = [
    'song_id', 'original_artists', 'song_title',
    # 'am_song_artist', 'year', 'am_song_year'
    'match_key_cm', 'cm_song_eas' # 'cm_ranking',
]

df_aux = df_songs_aux.loc[mask, cols_to_view]
print(df_aux.to_string())

     song_id            original_artists                                               song_title                                    match_key_cm  cm_song_eas
39    194201                 Bing Crosby                                          White Christmas                     bing crosby white christmas     19602000
48    194401                 Bing Crosby                                       Swinging On A Star                  bing crosby swinging on a star       624000
54    194407    Bing Crosby, Sonny Tufts                             Ac-Cen-Tchu-Ate the Positive          bing crosby accenttchuate the positive       758000
57    194502               Frank Sinatra                                I Fall In Love Too Easily         frank sinatra i fall in love too easily       321000
86    195401               Frank Sinatra                              Three Coins In The Fountain       frank sinatra three coins in the fountain       792000
93    195503               Frank Sinatra                                (Love Is) The Tender Trap                   frank sinatra the tender trap      1382000
97    195602    Bing Crosby, Grace Kelly                                                True Love                           bing crosby true love       316000
100   195701               Frank Sinatra                                              All The Way                       frank sinatra all the way      2385000
105   195712               Elvis Presley                                           Jailhouse Rock                    elvis presley jailhouse rock     18565000
111   195901               Frank Sinatra                                               High Hopes                        frank sinatra high hopes       237000
139   196404               Frank Sinatra                                          My Kind Of Town                   frank sinatra my kind of town      1090000
141   196412                 The Beatles                                       A Hard Day's Night                   the beatles a hard days night      9399000
149   196513                 The Beatles                                                    Help!                                the beatles help     11421000
155   196612               Frank Sinatra                                   Strangers in the Night            frank sinatra strangers in the night      8582000
161   196712           Simon & Garfunkel                                            Mrs. Robinson                  simon & garfunkel mrs robinson     19677000
165   196803            Barbra Streisand                                               Funny Girl                     barbra streisand funny girl       307000
174   197001  Carpenters, Larry Meredith                                          For All We Know                      carpenters for all we know      3317000
180   197103              The Carpenters                              Bless The Beasts & Children        carpenters bless the beasts and children       221000
185   197202             Michael Jackson                                                      Ben                             michael jackson ben      4346000
187   197301            Barbra Streisand                                          The Way We Were                barbra streisand the way we were     14387000
188   197302       Paul McCartney, Wings                                         Live And Let Die                 paul mccartney live and let die      3925000
192   197312                   Bob Dylan                                Knockin' On Heaven's Door               bob dylan knockin on heavens door      7419000
203   197502            Barbra Streisand                                    How Lucky Can You Get          barbra streisand how lucky can you get       570000
205   197504                  Diana Ross  Theme From Mahogany (Do You Know Where You're Going To)                  diana ross theme from mahogany      3338000
206   197601            Barbra Streisand               Evergreen (Love Theme From A Star Is Born)                      barbra streisand evergreen     11993000
215   197713                    Bee Gees                                              Night Fever                            bee gees night fever     10644000
216   197714                    Bee Gees                                            Stayin' Alive                           bee gees stayin alive     34307000
217   197715                    Bee Gees                                    How Deep Is Your Love                  bee gees how deep is your love     16800000
218   197716                    Bee Gees                                        More Than a Woman                      bee gees more than a woman      6429000
221   197802          Olivia Newton-John                                Hopelessly Devoted To You    olivia newton-john hopelessly devoted to you      5354000
226   197812               Frankie Valli                                                   Grease                            frankie valli grease      5913000
240   198014                  Paul Simon                                      Late In The Evening                  paul simon late in the evening      1714000
241   198015                Neil Diamond                                                  America                            neil diamond america      5489000
242   198016                Neil Diamond                                        Love on the Rocks                  neil diamond love on the rocks      4148000
253   198212                 David Bowie                            Cat People (Putting Out Fire)                          david bowie cat people      1090000
255   198302            Michael Sembello                                                   Maniac                         michael sembello maniac      9493000
256   198303            Barbra Streisand                                   Papa, Can You Hear Me?           barbra streisand papa can you hear me      1636000
262   198401               Stevie Wonder                          I Just Called To Say I Love You   stevie wonder i just called to say i love you     11213000
263   198402                Phil Collins                 Against All Odds (Take A Look At Me Now)                   phil collins against all odds      5327000
272   198501               Lionel Richie                                          Say You, Say Me                    lionel richie say you say me      9908000
278   198513                     Madonna                                          Into The Groove                         madonna into the groove      9217000
279   198514                 Tina Turner                               We Don't Need Another Hero           tina turner we dont need another hero      4098000
287   198613                       Queen                                Who Wants To Live Forever                 queen who wants to live forever      5203000
288   198614                       Queen                                          A Kind of Magic                           queen a kind of magic      4238000
290   198616                 David Bowie                                              Magic Dance                         david bowie magic dance       220000
291   198617                     Madonna                                             Live to Tell                            madonna live to tell      6665000
299   198714                     Madonna                                          Who's That Girl                          madonna whos that girl      4600000
303   198803                Phil Collins                                               Two Hearts                         phil collins two hearts      1812000
304   198804              The Beach Boys                                                   Kokomo                           the beach boys kokomo      4621000
314   199004                Jon Bon Jovi                                           Blaze Of Glory                     jon bon jovi blaze of glory      6008000
319   199104                 Bryan Adams                        (Everything I Do) I Do It For You                     bryan adams i do it for you     21807000
320   199112                Eric Clapton                                          Tears In Heaven                    eric clapton tears in heaven     14593000
323   199202             Whitney Houston                                           I Have Nothing                  whitney houston i have nothing     12402000
324   199203             Whitney Houston                                               Run To You                      whitney houston run to you      3736000
327   199301           Bruce Springsteen                                  Streets Of Philadelphia       bruce springsteen streets of philadelphia      2825000
331   199305               Janet Jackson                                                    Again                             janet jackson again      1979000
333   199401                  Elton John                            Can You Feel The Love Tonight        elton john can you feel the love tonight      3388000
334   199402                  Elton John                                           Circle Of Life                       elton john circle of life       864000
340   199503                 Bryan Adams                       Have You Ever Really Loved A Woman  bryan adams have you ever really loved a woman      3809000
343   199512                 Tina Turner                                                Goldeneye                           tina turner goldeneye      2466000
345   199601                     Madonna                                         You Must Love Me                        madonna you must love me       914000
348   199604                 Céline Dion                                     Because You Loved Me                celine dion because you loved me     17019000
350   199701                 Céline Dion                                      My Heart Will Go On                 celine dion my heart will go on     64042000
360   199802                   Aerosmith                             I Don't Want To Miss A Thing           aerosmith i dont want to miss a thing      3335000
365   199901                Phil Collins                                    You'll Be In My Heart               phil collins youll be in my heart      4558000
373   200003                       Björk                                         I've Seen It All                           bjork ive seen it all       617000
379   200104                        Enya                                                May It Be                                  enya may it be       347000
381   200201                      Eminem                                            Lose Yourself                            eminem lose yourself     18420000
385   200205                  Paul Simon                                      Father And Daughter                  paul simon father and daughter       410000
386   200212                     Madonna                                          Die Another Day                         madonna die another day      1942000
427   201201                       Adele                                                  Skyfall                                   adele skyfall      1180000
436   201312                Lana Del Rey                                      Young And Beautiful                lana del rey young and beautiful       461000
443   201501                   Sam Smith                                    Writing's On The Wall                  sam smith writings on the wall       563000
444   201502                  The Weeknd                                                Earned It                            the weeknd earned it      3811000
451   201603           Justin Timberlake                                   Can't Stop The Feeling         justin timberlake cant stop the feeling       970000

In [9]:
# Extracted TMDB and OMDB films quality check
cols_to_view = [
    'film_id', 'film_title', 'tmdb_official_title', # 'tmdb_original_title', 
    'year', 'tmdb_release_date',
    'omdb_title'
]

# Apply the filter and view the results
df_aux = df_films_aux[cols_to_view]
print(df_aux.to_string())

     film_id                                         film_title                                     tmdb_official_title  year tmdb_release_date                                               omdb_title
0     193401                                   The Gay Divorcee                                        The Gay Divorcee  1934        1934-10-12                                         The Gay Divorcee
1     193402                                   She Loves Me Not                                        She Loves Me Not  1934        1934-08-31                                         She Loves Me Not
2     193501                               Gold Diggers of 1935                                    Gold Diggers of 1935  1935        1935-03-15                                     Gold Diggers of 1935
3     193502                                            Top Hat                                                 Top Hat  1935        1935-08-29                                                  Top Hat
4     193503                                            Roberta                                                 Roberta  1935        1935-03-07                                                  Roberta
5     193601                                         Swing Time                                              Swing Time  1936        1936-08-28                                               Swing Time
6     193602                                      Born to Dance                                           Born to Dance  1936        1936-11-27                                            Born to Dance
7     193603                                Pennies from Heaven                                     Pennies from Heaven  1936        1936-11-25                                      Pennies from Heaven
8     193604                                   Sing, Baby, Sing                                        Sing, Baby, Sing  1936        1936-08-21                                         Sing, Baby, Sing
9     193605                                               Suzy                                                    Suzy  1936        1936-07-20                                                     Suzy
10    193701                                    Waikiki Wedding                                         Waikiki Wedding  1937        1937-03-23                                          Waikiki Wedding
11    193702                                     Shall We Dance                                          Shall We Dance  1937        1937-05-07                                           Shall We Dance
12    193703                                     Vogues of 1938                          Walter Wanger's Vogues of 1938  1937        1937-08-18                                           Vogues of 1938
13    193704                                 Artists and Models                                        Artists & Models  1937        1937-08-04                                        Artist and Models
14    193801                          The Big Broadcast of 1938                               The Big Broadcast of 1938  1938        1938-02-11                                The Big Broadcast of 1938
15    193802                           Alexander's Ragtime Band                                Alexander's Ragtime Band  1938        1938-05-24                                 Alexander's Ragtime Band
16    193803                                       Going Places                                            Going Places  1938        1938-12-31                                             Going Places
17    193804                                           Carefree                                                Carefree  1938        1938-09-02                                                 Carefree
18    193805                                   The Lady Objects                                        The Lady Objects  1938        1938-10-12                                         The Lady Objects
19    193806                            The Cowboy and the Lady                                 The Cowboy and the Lady  1938        1938-11-17                                  The Cowboy and the Lady
20    193807                                Under Western Stars                                     Under Western Stars  1938        1938-04-20                                      Under Western Stars
21    193901                                   The Wizard of Oz                                        The Wizard of Oz  1939        1939-08-21                                         The Wizard of Oz
22    193902                                      Second Fiddle                                           Second Fiddle  1939        1939-06-30                                            Second Fiddle
23    194001                                          Pinocchio                                               Pinocchio  1940        1940-02-23                                                Pinocchio
24    194002                                      Second Chorus                                           Second Chorus  1940        1941-01-03                                            Second Chorus
25    194003                                 Down Argentine Way                                      Down Argentine Way  1940        1940-10-11                                       Down Argentine Way
26    194004                                  Music in My Heart                                       Music in My Heart  1940        1940-01-04                                        Music in My Heart
27    194005                                 Hit Parade of 1941                                      Hit Parade of 1941  1940        1940-10-14                                       Hit Parade of 1941
28    194006                                 Strike Up the Band                                      Strike Up the Band  1940        1940-09-27                                       Strike Up the Band
29    194007                                    You'll Find Out                                         You'll Find Out  1940        1940-11-22                                          You'll Find Out
30    194008                                      Spring Parade                                           Spring Parade  1940        1940-09-27                                            Spring Parade
31    194101                                       Lady Be Good                                            Lady Be Good  1941        1941-09-18                                             Lady Be Good
32    194102                                 Blues in the Night                                      Blues in the Night  1941        1941-11-15                                       Blues in the Night
33    194103                                Sun Valley Serenade                                     Sun Valley Serenade  1941        1941-08-29                                      Sun Valley Serenade
34    194104                                  Babes on Broadway                                       Babes on Broadway  1941        1941-12-31                                        Babes on Broadway
35    194105                                              Dumbo                                                   Dumbo  1941        1941-10-31                                                    Dumbo
36    194106                                      Buck Privates                                           Buck Privates  1941        1941-01-31                                            Buck Privates
37    194107                                   Las Vegas Nights                                        Las Vegas Nights  1941        1941-03-28                                         Las Vegas Nights
38    194108                                Ridin' on a Rainbow                                     Ridin' on a Rainbow  1941        1941-01-24                                      Ridin' on a Rainbow
39    194201                                        Holiday Inn                                             Holiday Inn  1942        1942-07-10                                              Holiday Inn
40    194202                            You Were Never Lovelier                                 You Were Never Lovelier  1942        1942-11-19                                  You Were Never Lovelier
41    194203                                              Bambi                                                   Bambi  1942        1942-08-14                                                    Bambi
42    194204                                    Youth on Parade                                         Youth on Parade  1942        1942-10-24                                          Youth on Parade
43    194301                               Hello, Frisco, Hello                                    Hello, Frisco, Hello  1943        1943-03-26                                      Hello Frisco, Hello
44    194302                               Star Spangled Rhythm                                    Star Spangled Rhythm  1943        1942-03-05                                     Star Spangled Rhythm
45    194303                                The Sky's the Limit                                     The Sky's the Limit  1943        1943-07-13                                      The Sky's the Limit
46    194304                           Something to Shout About                                Something to Shout About  1943        1943-02-25                                 Something to Shout About
47    194305                                   Cabin in the Sky                                        Cabin in the Sky  1943        1943-03-24                                         Cabin in the Sky
48    194401                                       Going My Way                                            Going My Way  1944        1944-01-01                                             Going My Way
49    194402                                         Cover Girl                                              Cover Girl  1944        1944-03-22                                               Cover Girl
50    194403                                    Follow the Boys                                         Follow the Boys  1944        1944-05-05                                          Follow the Boys
51    194404                               Meet Me in St. Louis                                    Meet Me in St. Louis  1944        1944-11-28                                     Meet Me in St. Louis
52    194405                                         Up in Arms                                              Up in Arms  1944        1944-02-17                                               Up in Arms
53    194406                                 Sweet and Low-Down                                      Sweet and Low-Down  1944        1944-09-21                                       Sweet and Low-Down
54    194407                                Here Come the Waves                                     Here Come the Waves  1944        1944-12-18                                      Here Come the Waves
55    194408                                 Can't Help Singing                                      Can't Help Singing  1944        1944-12-25                                       Can't Help Singing
56    194501                                         State Fair                                              State Fair  1945        1945-08-29                                               State Fair
57    194502                                     Anchors Aweigh                                          Anchors Aweigh  1945        1945-08-13                                           Anchors Aweigh
58    194503                            The Bells of St. Mary's                                 The Bells of St. Mary's  1945        1945-12-27                                  The Bells of St. Mary's
59    194504                                  The Dolly Sisters                                       The Dolly Sisters  1945        1945-11-14                                        The Dolly Sisters
60    194601                                   The Harvey Girls                                        The Harvey Girls  1946        1946-01-18                                         The Harvey Girls
61    194602                                         Blue Skies                                              Blue Skies  1946        1946-10-15                                               Blue Skies
62    194603                                  Centennial Summer                                       Centennial Summer  1946        1946-07-10                                        Centennial Summer
63    194604                   The Time, the Place and the Girl                        The Time, The Place and The Girl  1946        1946-12-26                         The Time, the Place and the Girl
64    194612                                              Gilda                                                   Gilda  1946        1946-04-25                                                    Gilda
65    194701                                  Song of the South                                       Song of the South  1947        1946-11-20                                        Song of the South
66    194702                              The Perils of Pauline                                   The Perils of Pauline  1947        1947-07-04                                    The Perils of Pauline
67    194801                                       The Paleface                                            The Paleface  1948        1948-12-17                                             The Paleface
68    194802                           Romance on the High Seas                                Romance on the High Seas  1948        1948-06-25                                 Romance on the High Seas
69    194803                                             Casbah                                                  Casbah  1948        1948-04-01                                                   Casbah
70    194901                                 Neptune's Daughter                                      Neptune's Daughter  1949        1949-06-10                                       Neptune's Daughter
71    194902                                   My Foolish Heart                                        My Foolish Heart  1949        1950-01-19                                         My Foolish Heart
72    194903                               It's a Great Feeling                                    It's a Great Feeling  1949        1949-08-20                                     It's a Great Feeling
73    195001                              Captain Carey, U.S.A.                                   Captain Carey, U.S.A.  1950        1950-02-21                                    Captain Carey, U.S.A.
74    195002                                         Cinderella                                              Cinderella  1950        1950-02-22                                               Cinderella
75    195003                           The Toast of New Orleans                                The Toast of New Orleans  1950        1950-08-24                                 The Toast of New Orleans
76    195101                               Here Comes the Groom                                    Here Comes the Groom  1951        1951-09-20                                     Here Comes the Groom
77    195102                                          The Strip                                               The Strip  1951        1951-08-31                                                The Strip
78    195103                             Rich, Young and Pretty                                  Rich, Young and Pretty  1951        1951-07-09                                   Rich, Young and Pretty
79    195201                                          High Noon                                               High Noon  1952        1952-06-09                                                High Noon
80    195202                                Because You're Mine                                     Because You're Mine  1952        1952-10-01                                      Because You're Mine
81    195203                            Hans Christian Andersen                                 Hans Christian Andersen  1952        1952-12-19                                  Hans Christian Andersen
82    195204                                       Just for You                                            Just for You  1952        1952-09-27                                             Just for You
83    195301                                      Calamity Jane                                           Calamity Jane  1953        1953-11-04                                            Calamity Jane
84    195302                                          The Caddy                                               The Caddy  1953        1953-08-10                                                The Caddy
85    195303                                    Small Town Girl                                         Small Town Girl  1953        1953-04-10                                          Small Town Girl
86    195401                        Three Coins in the Fountain                             Three Coins in the Fountain  1954        1954-05-01                              Three Coins in the Fountain
87    195402                                     A Star Is Born                                          A Star Is Born  1954        1954-10-01                                           A Star Is Born
88    195403                                   Susan Slept Here                                        Susan Slept Here  1954        1954-07-28                                         Susan Slept Here
89    195404                            The High and the Mighty                                 The High and the Mighty  1954        1954-07-03                                  The High and the Mighty
90    195405                                    White Christmas                                         White Christmas  1954        1954-10-14                                          White Christmas
91    195501                    Love Is a Many-Splendored Thing                         Love Is a Many-Splendored Thing  1955        1955-08-18                          Love Is a Many-Splendored Thing
92    195502                                    Daddy Long Legs                                         Daddy Long Legs  1955        1955-05-05                                          Daddy Long Legs
93    195503                                    The Tender Trap                                         The Tender Trap  1955        1955-11-04                                          The Tender Trap
94    195504                                          Unchained                                               Unchained  1955        1955-08-25                                                Unchained
95    195505                                Love Me or Leave Me                                     Love Me or Leave Me  1955        1955-05-26                                      Love Me or Leave Me
96    195601                          The Man Who Knew Too Much                               The Man Who Knew Too Much  1956        1956-05-16                                The Man Who Knew Too Much
97    195602                                       High Society                                            High Society  1956        1956-07-17                                             High Society

In [10]:
# Display Missing Budgets and Revenues
missing_mask = (df_films_aux['tmdb_budget'] == 0) | (df_films_aux['tmdb_revenue'] == 0)

cols_to_view = ['film_id', 'film_title', 'tmdb_budget', 'tmdb_revenue']

df_missing = df_films_aux.loc[missing_mask, cols_to_view]
print(df_missing.to_string())

     film_id                            film_title  tmdb_budget  tmdb_revenue
1     193402                      She Loves Me Not            0             0
2     193501                  Gold Diggers of 1935            0             0
4     193503                               Roberta            0             0
6     193602                         Born to Dance            0             0
7     193603                   Pennies from Heaven            0             0
8     193604                      Sing, Baby, Sing            0             0
9     193605                                  Suzy            0             0
10    193701                       Waikiki Wedding            0             0
12    193703                        Vogues of 1938            0             0
13    193704                    Artists and Models            0             0
14    193801             The Big Broadcast of 1938      1000000             0
16    193803                          Going Places            0             0
18    193805                      The Lady Objects            0             0
19    193806               The Cowboy and the Lady            0             0
20    193807                   Under Western Stars            0             0
22    193902                         Second Fiddle            0             0
24    194002                         Second Chorus            0             0
25    194003                    Down Argentine Way            0             0
26    194004                     Music in My Heart            0             0
27    194005                    Hit Parade of 1941            0             0
28    194006                    Strike Up the Band            0             0
29    194007                       You'll Find Out            0             0
30    194008                         Spring Parade            0             0
31    194101                          Lady Be Good            0             0
32    194102                    Blues in the Night            0             0
33    194103                   Sun Valley Serenade            0             0
34    194104                     Babes on Broadway            0             0
36    194106                         Buck Privates            0             0
37    194107                      Las Vegas Nights            0             0
38    194108                   Ridin' on a Rainbow            0             0
39    194201                           Holiday Inn            0       3750000
40    194202               You Were Never Lovelier            0             0
42    194204                       Youth on Parade            0             0
43    194301                  Hello, Frisco, Hello            0             0
44    194302                  Star Spangled Rhythm            0             0
46    194304              Something to Shout About            0             0
48    194401                          Going My Way            0      16300000
49    194402                            Cover Girl            0             0
50    194403                       Follow the Boys            0       2000000
52    194405                            Up in Arms      2000000             0
53    194406                    Sweet and Low-Down            0             0
54    194407                   Here Come the Waves            0             0
55    194408                    Can't Help Singing            0             0
56    194501                            State Fair            0             0
58    194503               The Bells of St. Mary's            0      21300000
59    194504                     The Dolly Sisters            0             0
60    194601                      The Harvey Girls            0             0
61    194602                            Blue Skies            0             0
62    194603                     Centennial Summer            0             0
63    194604      The Time, the Place and the Girl            0             0
66    194702                 The Perils of Pauline            0             0
67    194801                          The Paleface            0             0
69    194803                                Casbah            0             0
70    194901                    Neptune's Daughter            0             0
71    194902                      My Foolish Heart            0             0
73    195001                 Captain Carey, U.S.A.            0             0
75    195003              The Toast of New Orleans            0             0
76    195101                  Here Comes the Groom            0             0
77    195102                             The Strip            0             0
78    195103                Rich, Young and Pretty            0             0
80    195202                   Because You're Mine            0             0
81    195203               Hans Christian Andersen            0             0
82    195204                          Just for You            0             0
83    195301                         Calamity Jane            0             0
84    195302                             The Caddy            0             0
85    195303                       Small Town Girl            0             0
86    195401           Three Coins in the Fountain            0             0
88    195403                      Susan Slept Here            0             0
89    195404               The High and the Mighty            0             0
90    195405                       White Christmas            0       1109388
91    195501       Love Is a Many-Splendored Thing            0             0
92    195502                       Daddy Long Legs            0             0
93    195503                       The Tender Trap            0             0
94    195504                             Unchained            0             0
95    195505                   Love Me or Leave Me            0             0
99    195604                                 Julie            0             0
102   195703                      Wild Is the Wind            0             0
104   195705                Tammy and the Bachelor            0             0
107   195802                       A Certain Smile            0             0
108   195803                             Houseboat            0       3500000
110   195805                     Some Came Running            0             0
111   195901                    A Hole in the Head            0             0
112   195902                      The Hanging Tree            0             0
113   195903                The Best of Everything            0             0
114   195904                      The Five Pennies            0             0
115   195905                        The Young Land            0             0
117   196002                             High Time            0             0
119   196004                     The Facts of Life            0             0
120   196005                                  Pepe            0             0
123   196103                  Bachelor in Paradise            0             0
124   196104                     Town Without Pity            0             0
125   196201                Days of Wine and Roses            0             0
126   196202                    Two for the Seesaw            0       3000000
130   196301             Papa's Delicate Condition            0             0
134   196312                      The Pink Panther            0      10878107
137   196402                            Dear Heart            0             0
139   196404                 Robin and the 7 Hoods            0             0
140   196405                   Where Love Has Gone            0             0
143   196501                         The Sandpiper            0       6161000
145   196503                  What's New Pussycat?            0      18820000
147   196505                            Cat Ballou            0      20666667
149   196513                                 Help!      1500000             0
150   196601                             Born Free            0             0
151   196602                                 Alfie            0             0
153   196604                           Georgy Girl            0             0
154   196605                     An American Dream            0             0
155   196612                A Man Could Get Killed            0             0
158   196703              Thoroughly Modern Millie            0             0
160   196705                               Banning            0             0
167   196805                       For Love of Ivy            0             0
170   196902                             True Grit            0      37659900
171   196903                      The Happy Ending            0             0
172   196904                    The Sterile Cuckoo            0      14000000
173   196905         The Prime of Miss Jean Brodie            0             0
174   197001            Lovers and Other Strangers            0             0
176   197003                      Pieces of Dreams            0             0
177   197004                                Madron            0             0
180   197103           Bless the Beasts & Children            0             0
181   197104              Sometimes a Great Notion      3660000             0
185   197202                                   Ben            0             0
186   197203  The Life and Times of Judge Roy Bean            0             0
189   197303                      A Touch of Class            0      18312000
191   197305                    Cinderella Liberty            0             0
196   197403                                 Benji            0             0
202   197503                                Whiffs            0             0
203   197504                              Mahogany            0             0
208   197701                  You Light Up My Life            0             0
210   197703                         Pete's Dragon     10000000             0
214   197717                          The Greatest            0       8284000
215   197801                 Thank God It's Friday            0             0
218   197804                   The Magic of Lassie            0             0
219   197805                           Ice Castles            0             0
223   197903                           The Promise            0             0
228   198003                      Honeysuckle Rose            0             0
230   198005                       The Competition            0             0
233   198014                        One-Trick Pony            0        843215
236   198102                          Endless Love            0      32492674
238   198104                               Ragtime            0             0
254   198402                      Against All Odds            0             0
260   198501                          White Nights            0      42160849
271   198604                           That's Life            0             0
285   198802                           Bagdad Cafe            0       3732660
286   198803                                Buster            0             0
291   198905                     Shirley Valentine            0             0
301   199112                                  Rush     17000000             0
305   199204                       The Mambo Kings            0       6742168
325   199605                          One Fine Day            0      97529550
332   199713                             Metroland            0             0
361   200205            The Wild Thornberrys Movie     35000000             0
367   200401                The Motorcycle Diaries            0      57663224
385   200803                              Paris 36            0      12940622
401   201205                           Chasing Ice            0       1328467
407   201313                Barcelona, nit d'estiu            0             0
410   201403             Glen Campbell: I'll Be Me            0        365522
415   201503                    The Hunting Ground            0        411115
417   201505                     Racing Extinction            0             0
421   201604            Jim: The James Foley Story            0             0
426   201703                              Mudbound     10000000             0
431   201804                                   RBG            0       2002767
432   201805          The Ballad of Buster Scruggs            0             0
436   201903                               Harriet     17000000             0
440   202002                        The Life Ahead            0             0
442   202004                 One Night in Miami...            0             0
444   202013                        Four Good Days            0        843965
453   202212                  Tell It like a Woman     21000000             0
456   202304                     American Symphony            0             0
457   202312                           Flamin' Hot            0             0
459   202403                  The Six Triple Eight            0             0
460   202404                             Sing Sing            0             0
461   202405            Elton John: Never Too Late            0             0
464   202503                          Train Dreams     10000000             0
465   202504                           Viva Verdi!            0             0
466   202505              Diane Warren: Relentless            0             0

## TRANSFORMACIONES

### Columnas de Década

In [11]:
df_songs_aux['decade'] = (df_songs_aux['year'] // 10) * 10

### Imputaciones de Datos

Incorporo algún dato de streams de canción que se pasó en la extracción inicial (para no repetir todo el proceso que puede tardar 90 minutos aprox.)

In [12]:
# Fill Missing Stream data
df_songs_aux.loc[df_songs_aux['song_id'] == 199505, ['other_artists', 'streams_others']] = ['Sheléa', 808000]

# Display Confirmation
display(df_songs_aux.loc[df_songs_aux['song_id'] == 199505, ['song_title', 'other_artists', 'streams_others']])

    song_title other_artists  streams_others
342  Moonlight        Sheléa        808000.0

También incorporo nuevos datos de presupuestos y taquilla de Películas que no estaban disponibles en la API de TMDB o OMDB pero pude captar manualmente en la web de IMDB.

In [13]:
# Fill Missing Budgets and Revenues (from IMDB)
df_films_aux.loc[df_films_aux['film_id'] == 193806, ['tmdb_budget', 'tmdb_revenue']] = [1500000, 0]
df_films_aux.loc[df_films_aux['film_id'] == 194006, ['tmdb_budget', 'tmdb_revenue']] = [840000, 0]
df_films_aux.loc[df_films_aux['film_id'] == 194007, ['tmdb_budget', 'tmdb_revenue']] = [353000, 0]
df_films_aux.loc[df_films_aux['film_id'] == 194101, ['tmdb_budget', 'tmdb_revenue']] = [863000, 0]
df_films_aux.loc[df_films_aux['film_id'] == 194104, ['tmdb_budget', 'tmdb_revenue']] = [940000, 0]
df_films_aux.loc[df_films_aux['film_id'] == 194106, ['tmdb_budget', 'tmdb_revenue']] = [245000, 0]
df_films_aux.loc[df_films_aux['film_id'] == 194201, ['tmdb_budget', 'tmdb_revenue']] = [3200000, 3750000]
df_films_aux.loc[df_films_aux['film_id'] == 194202, ['tmdb_budget', 'tmdb_revenue']] = [0, 673000]
df_films_aux.loc[df_films_aux['film_id'] == 194301, ['tmdb_budget', 'tmdb_revenue']] = [0, 3400000]
df_films_aux.loc[df_films_aux['film_id'] == 194302, ['tmdb_budget', 'tmdb_revenue']] = [0, 602000]
df_films_aux.loc[df_films_aux['film_id'] == 194401, ['tmdb_budget', 'tmdb_revenue']] = [0, 2200]
df_films_aux.loc[df_films_aux['film_id'] == 194504, ['tmdb_budget', 'tmdb_revenue']] = [2510000, 0]
df_films_aux.loc[df_films_aux['film_id'] == 194601, ['tmdb_budget', 'tmdb_revenue']] = [2525000, 1400]
df_films_aux.loc[df_films_aux['film_id'] == 194602, ['tmdb_budget', 'tmdb_revenue']] = [3000000, 0]
df_films_aux.loc[df_films_aux['film_id'] == 194803, ['tmdb_budget', 'tmdb_revenue']] = [1307000, 0]
df_films_aux.loc[df_films_aux['film_id'] == 195101, ['tmdb_budget', 'tmdb_revenue']] = [2120000, 0]
df_films_aux.loc[df_films_aux['film_id'] == 195102, ['tmdb_budget', 'tmdb_revenue']] = [885000, 0]
df_films_aux.loc[df_films_aux['film_id'] == 195103, ['tmdb_budget', 'tmdb_revenue']] = [1528000, 0]
df_films_aux.loc[df_films_aux['film_id'] == 195203, ['tmdb_budget', 'tmdb_revenue']] = [4000000, 0]
df_films_aux.loc[df_films_aux['film_id'] == 195301, ['tmdb_budget', 'tmdb_revenue']] = [0, 9200]
df_films_aux.loc[df_films_aux['film_id'] == 195302, ['tmdb_budget', 'tmdb_revenue']] = [1864000, 0]
df_films_aux.loc[df_films_aux['film_id'] == 195303, ['tmdb_budget', 'tmdb_revenue']] = [1440000, 0]
df_films_aux.loc[df_films_aux['film_id'] == 195401, ['tmdb_budget', 'tmdb_revenue']] = [0, 6800]
df_films_aux.loc[df_films_aux['film_id'] == 195404, ['tmdb_budget', 'tmdb_revenue']] = [1470000, 4300]
df_films_aux.loc[df_films_aux['film_id'] == 195405, ['tmdb_budget', 'tmdb_revenue']] = [0, 2990000]
df_films_aux.loc[df_films_aux['film_id'] == 195501, ['tmdb_budget', 'tmdb_revenue']] = [1780000, 29300]
df_films_aux.loc[df_films_aux['film_id'] == 195505, ['tmdb_budget', 'tmdb_revenue']] = [2750000, 200]
df_films_aux.loc[df_films_aux['film_id'] == 195604, ['tmdb_budget', 'tmdb_revenue']] = [785000, 0]
df_films_aux.loc[df_films_aux['film_id'] == 195803, ['tmdb_budget', 'tmdb_revenue']] = [3500000, 0]
df_films_aux.loc[df_films_aux['film_id'] == 195805, ['tmdb_budget', 'tmdb_revenue']] = [3150000, 30800]
df_films_aux.loc[df_films_aux['film_id'] == 195901, ['tmdb_budget', 'tmdb_revenue']] = [1890000, 2900]
df_films_aux.loc[df_films_aux['film_id'] == 195902, ['tmdb_budget', 'tmdb_revenue']] = [1350000, 9000]
df_films_aux.loc[df_films_aux['film_id'] == 195903, ['tmdb_budget', 'tmdb_revenue']] = [2500000, 0]
df_films_aux.loc[df_films_aux['film_id'] == 196002, ['tmdb_budget', 'tmdb_revenue']] = [0, 5450000]
df_films_aux.loc[df_films_aux['film_id'] == 196005, ['tmdb_budget', 'tmdb_revenue']] = [0, 9600000]
df_films_aux.loc[df_films_aux['film_id'] == 196103, ['tmdb_budget', 'tmdb_revenue']] = [1990000, 0]
df_films_aux.loc[df_films_aux['film_id'] == 196201, ['tmdb_budget', 'tmdb_revenue']] = [0, 2000]
df_films_aux.loc[df_films_aux['film_id'] == 196202, ['tmdb_budget', 'tmdb_revenue']] = [3000000, 3000000]
df_films_aux.loc[df_films_aux['film_id'] == 196312, ['tmdb_budget', 'tmdb_revenue']] = [3000000, 10878107]
df_films_aux.loc[df_films_aux['film_id'] == 196404, ['tmdb_budget', 'tmdb_revenue']] = [0, 9800000]
df_films_aux.loc[df_films_aux['film_id'] == 196501, ['tmdb_budget', 'tmdb_revenue']] = [5300000, 6161000]
df_films_aux.loc[df_films_aux['film_id'] == 196602, ['tmdb_budget', 'tmdb_revenue']] = [800000, 0]
df_films_aux.loc[df_films_aux['film_id'] == 196604, ['tmdb_budget', 'tmdb_revenue']] = [400000, 0]
df_films_aux.loc[df_films_aux['film_id'] == 196703, ['tmdb_budget', 'tmdb_revenue']] = [6000000, 0]
df_films_aux.loc[df_films_aux['film_id'] == 196805, ['tmdb_budget', 'tmdb_revenue']] = [2590000, 0]
df_films_aux.loc[df_films_aux['film_id'] == 196902, ['tmdb_budget', 'tmdb_revenue']] = [0, 275000]
df_films_aux.loc[df_films_aux['film_id'] == 196903, ['tmdb_budget', 'tmdb_revenue']] = [2000000, 0]
df_films_aux.loc[df_films_aux['film_id'] == 196905, ['tmdb_budget', 'tmdb_revenue']] = [2750000, 14500]
df_films_aux.loc[df_films_aux['film_id'] == 197001, ['tmdb_budget', 'tmdb_revenue']] = [0, 5484000]
df_films_aux.loc[df_films_aux['film_id'] == 197103, ['tmdb_budget', 'tmdb_revenue']] = [0, 212000]
df_films_aux.loc[df_films_aux['film_id'] == 197104, ['tmdb_budget', 'tmdb_revenue']] = [3660000, 0]
df_films_aux.loc[df_films_aux['film_id'] == 197202, ['tmdb_budget', 'tmdb_revenue']] = [0, 770000]
df_films_aux.loc[df_films_aux['film_id'] == 197203, ['tmdb_budget', 'tmdb_revenue']] = [0, 16500000]
df_films_aux.loc[df_films_aux['film_id'] == 197305, ['tmdb_budget', 'tmdb_revenue']] = [2465000, 0]
df_films_aux.loc[df_films_aux['film_id'] == 197403, ['tmdb_budget', 'tmdb_revenue']] = [500000, 39550000]
df_films_aux.loc[df_films_aux['film_id'] == 197504, ['tmdb_budget', 'tmdb_revenue']] = [0, 5000000]
df_films_aux.loc[df_films_aux['film_id'] == 197703, ['tmdb_budget', 'tmdb_revenue']] = [10000000, 39600000]
df_films_aux.loc[df_films_aux['film_id'] == 197801, ['tmdb_budget', 'tmdb_revenue']] = [2200000, 0]
df_films_aux.loc[df_films_aux['film_id'] == 197805, ['tmdb_budget', 'tmdb_revenue']] = [0, 20700000]
df_films_aux.loc[df_films_aux['film_id'] == 197903, ['tmdb_budget', 'tmdb_revenue']] = [0, 11600000]
df_films_aux.loc[df_films_aux['film_id'] == 198003, ['tmdb_budget', 'tmdb_revenue']] = [11000000, 17800000]
df_films_aux.loc[df_films_aux['film_id'] == 198005, ['tmdb_budget', 'tmdb_revenue']] = [10100000, 14285000]
df_films_aux.loc[df_films_aux['film_id'] == 198102, ['tmdb_budget', 'tmdb_revenue']] = [9700000, 32492674]
df_films_aux.loc[df_films_aux['film_id'] == 198104, ['tmdb_budget', 'tmdb_revenue']] = [0, 14920000]
df_films_aux.loc[df_films_aux['film_id'] == 198402, ['tmdb_budget', 'tmdb_revenue']] = [13000000, 21690000]
df_films_aux.loc[df_films_aux['film_id'] == 198501, ['tmdb_budget', 'tmdb_revenue']] = [20000000, 42160849]
df_films_aux.loc[df_films_aux['film_id'] == 198604, ['tmdb_budget', 'tmdb_revenue']] = [10000000, 4080000]
df_films_aux.loc[df_films_aux['film_id'] == 198803, ['tmdb_budget', 'tmdb_revenue']] = [0, 540000]
df_films_aux.loc[df_films_aux['film_id'] == 198905, ['tmdb_budget', 'tmdb_revenue']] = [0, 6000000]
df_films_aux.loc[df_films_aux['film_id'] == 199112, ['tmdb_budget', 'tmdb_revenue']] = [17000000, 7240000]
df_films_aux.loc[df_films_aux['film_id'] == 199204, ['tmdb_budget', 'tmdb_revenue']] = [15500000, 6742168]
df_films_aux.loc[df_films_aux['film_id'] == 199713, ['tmdb_budget', 'tmdb_revenue']] = [0, 26700]
df_films_aux.loc[df_films_aux['film_id'] == 200205, ['tmdb_budget', 'tmdb_revenue']] = [25000000, 60700000]
df_films_aux.loc[df_films_aux['film_id'] == 201313, ['tmdb_budget', 'tmdb_revenue']] = [0, 300000]
df_films_aux.loc[df_films_aux['film_id'] == 201505, ['tmdb_budget', 'tmdb_revenue']] = [1500000, 0]
df_films_aux.loc[df_films_aux['film_id'] == 201604, ['tmdb_budget', 'tmdb_revenue']] = [0, 8250]
df_films_aux.loc[df_films_aux['film_id'] == 201703, ['tmdb_budget', 'tmdb_revenue']] = [10000000, 86000]
df_films_aux.loc[df_films_aux['film_id'] == 201903, ['tmdb_budget', 'tmdb_revenue']] = [17000000, 43350000]
df_films_aux.loc[df_films_aux['film_id'] == 202004, ['tmdb_budget', 'tmdb_revenue']] = [17000000, 0]
df_films_aux.loc[df_films_aux['film_id'] == 202212, ['tmdb_budget', 'tmdb_revenue']] = [7000000, 12800]
df_films_aux.loc[df_films_aux['film_id'] == 202404, ['tmdb_budget', 'tmdb_revenue']] = [2000000, 3110476]
# df_films_aux.loc[df_films_aux['film_id'] == 00, ['tmdb_budget', 'tmdb_revenue']] = [0, 0]

# Display imputations
print(df_films_aux[['film_id', 'film_title', 'tmdb_budget', 'tmdb_revenue']].to_string())

     film_id                                         film_title  tmdb_budget  tmdb_revenue
0     193401                                   The Gay Divorcee       520000       1800000
1     193402                                   She Loves Me Not            0             0
2     193501                               Gold Diggers of 1935            0             0
3     193502                                            Top Hat       609000       3202000
4     193503                                            Roberta            0             0
5     193601                                         Swing Time       886000       2600000
6     193602                                      Born to Dance            0             0
7     193603                                Pennies from Heaven            0             0
8     193604                                   Sing, Baby, Sing            0             0
9     193605                                               Suzy            0             0
10    193701                                    Waikiki Wedding            0             0
11    193702                                     Shall We Dance       991000       2168000
12    193703                                     Vogues of 1938            0             0
13    193704                                 Artists and Models            0             0
14    193801                          The Big Broadcast of 1938      1000000             0
15    193802                           Alexander's Ragtime Band      2000000       4000000
16    193803                                       Going Places            0             0
17    193804                                           Carefree      1253000       1731000
18    193805                                   The Lady Objects            0             0
19    193806                            The Cowboy and the Lady      1500000             0
20    193807                                Under Western Stars            0             0
21    193901                                   The Wizard of Oz      2777000      33754967
22    193902                                      Second Fiddle            0             0
23    194001                                          Pinocchio      2600000     164000000
24    194002                                      Second Chorus            0             0
25    194003                                 Down Argentine Way            0             0
26    194004                                  Music in My Heart            0             0
27    194005                                 Hit Parade of 1941            0             0
28    194006                                 Strike Up the Band       840000             0
29    194007                                    You'll Find Out       353000             0
30    194008                                      Spring Parade            0             0
31    194101                                       Lady Be Good       863000             0
32    194102                                 Blues in the Night            0             0
33    194103                                Sun Valley Serenade            0             0
34    194104                                  Babes on Broadway       940000             0
35    194105                                              Dumbo       812000       1600000
36    194106                                      Buck Privates       245000             0
37    194107                                   Las Vegas Nights            0             0
38    194108                                Ridin' on a Rainbow            0             0
39    194201                                        Holiday Inn      3200000       3750000
40    194202                            You Were Never Lovelier            0        673000
41    194203                                              Bambi       858000     267447150
42    194204                                    Youth on Parade            0             0
43    194301                               Hello, Frisco, Hello            0       3400000
44    194302                               Star Spangled Rhythm            0        602000
45    194303                                The Sky's the Limit       871000       2185000
46    194304                           Something to Shout About            0             0
47    194305                                   Cabin in the Sky       662141       1606624
48    194401                                       Going My Way            0          2200
49    194402                                         Cover Girl            0             0
50    194403                                    Follow the Boys            0       2000000
51    194404                               Meet Me in St. Louis      1707561       7566000
52    194405                                         Up in Arms      2000000             0
53    194406                                 Sweet and Low-Down            0             0
54    194407                                Here Come the Waves            0             0
55    194408                                 Can't Help Singing            0             0
56    194501                                         State Fair            0             0
57    194502                                     Anchors Aweigh      2600000       7500000
58    194503                            The Bells of St. Mary's            0      21300000
59    194504                                  The Dolly Sisters      2510000             0
60    194601                                   The Harvey Girls      2525000          1400
61    194602                                         Blue Skies      3000000             0
62    194603                                  Centennial Summer            0             0
63    194604                   The Time, the Place and the Girl            0             0
64    194612                                              Gilda      2000000       6000000
65    194701                                  Song of the South      2125000      65000000
66    194702                              The Perils of Pauline            0             0
67    194801                                       The Paleface            0             0
68    194802                           Romance on the High Seas      2532000       3225000
69    194803                                             Casbah      1307000             0
70    194901                                 Neptune's Daughter            0             0
71    194902                                   My Foolish Heart            0             0
72    194903                               It's a Great Feeling      1452000       2713000
73    195001                              Captain Carey, U.S.A.            0             0
74    195002                                         Cinderella      2900000     263600000
75    195003                           The Toast of New Orleans            0             0
76    195101                               Here Comes the Groom      2120000             0
77    195102                                          The Strip       885000             0
78    195103                             Rich, Young and Pretty      1528000             0
79    195201                                          High Noon       730000       8000000
80    195202                                Because You're Mine            0             0
81    195203                            Hans Christian Andersen      4000000             0
82    195204                                       Just for You            0             0
83    195301                                      Calamity Jane            0          9200
84    195302                                          The Caddy      1864000             0
85    195303                                    Small Town Girl      1440000             0
86    195401                        Three Coins in the Fountain            0          6800
87    195402                                     A Star Is Born      5019770      12000000
88    195403                                   Susan Slept Here            0             0
89    195404                            The High and the Mighty      1470000          4300
90    195405                                    White Christmas            0       2990000
91    195501                    Love Is a Many-Splendored Thing      1780000         29300
92    195502                                    Daddy Long Legs            0             0
93    195503                                    The Tender Trap            0             0
94    195504                                          Unchained            0             0
95    195505                                Love Me or Leave Me      2750000           200
96    195601                          The Man Who Knew Too Much      1200000      11300000
97    195602                                       High Society      2800000       8200000
98    195603                                Friendly Persuasion      3000000       8000000
99    195604                                              Julie       785000             0
100   195701                                  The Joker Is Wild      2400000       3000000
101   195702                              An Affair to Remember      2100000       3800000
102   195703                                   Wild Is the Wind            0             0
103   195704                                         April Love      1425000       3700000
104   195705                             Tammy and the Bachelor            0             0
105   195712                                     Jailhouse Rock      1000000       4000000
106   195801                                               Gigi      3319355      13200000
107   195802                                    A Certain Smile            0             0
108   195803                                          Houseboat      3500000             0
109   195804                               Marjorie Morningstar      2000000       3000000
110   195805                                  Some Came Running      3150000         30800
111   195901                                 A Hole in the Head      1890000          2900
112   195902                                   The Hanging Tree      1350000          9000
113   195903                             The Best of Everything      2500000             0
114   195904                                   The Five Pennies            0             0
115   195905                                     The Young Land            0             0
116   196001                                    Never on Sunday       151000       8000000
117   196002                                          High Time            0       5450000
118   196003                                          The Alamo     12000000       7900000
119   196004                                  The Facts of Life            0             0
120   196005                                               Pepe            0       9600000
121   196101                             Breakfast at Tiffany's      2500000       9500000
122   196102                              Pocketful of Miracles      2900000       5000000
123   196103                               Bachelor in Paradise      1990000             0
124   196104                                  Town Without Pity            0             0
125   196201                             Days of Wine and Roses            0          2000
126   196202                                 Two for the Seesaw      3000000       3000000
127   196203                                Tender Is the Night      3900000       1250000
128   196204                               Mutiny on the Bounty     19000000      13680000
129   196212                                             Dr. No      1000000      59000000
130   196301                          Papa's Delicate Condition            0             0
131   196302                                            Charade      4000000      13475000
132   196303                    It's a Mad, Mad, Mad, Mad World      9400000      60000000
133   196304                                  55 Days at Peking     17000000      10000000
134   196312                                   The Pink Panther      3000000      10878107
135   196313                              From Russia With Love      2000000      78900000
136   196401                                       Mary Poppins      4650000     103100000
137   196402                                         Dear Heart            0             0
138   196403                       Hush...Hush, Sweet Charlotte      2200000       4000000
139   196404                              Robin and the 7 Hoods            0       9800000
140   196405                                Where Love Has Gone            0             0
141   196412                                 A Hard Day's Night       560000      11000000
142   196413                                         Goldfinger      3000000     124900000
143   196501                                      The Sandpiper      5300000       6161000
144   196502                                     The Great Race     12000000      25300000
145   196503                               What's New Pussycat?            0      18820000
146   196504                         The Umbrellas of Cherbourg       200000       7600000
147   196505                                         Cat Ballou            0      20666667
148   196512                                        Thunderball      9000000     141200000
149   196513                                              Help!      1500000             0
150   196601                                          Born Free            0             0
151   196602                                              Alfie       800000             0
152   196603                                             Hawaii     15000000      34562222
153   196604                                        Georgy Girl       400000             0
154   196605                                  An American Dream            0             0
155   196612                             A Man Could Get Killed            0             0
156   196701                                    Doctor Dolittle     18000000       9000000
157   196702                                      Casino Royale     12000000      41744718
158   196703                           Thoroughly Modern Millie      6000000             0
159   196704                                    The Jungle Book      4000000     378000000
160   196705                                            Banning            0             0
161   196712                                       The Graduate      3000000     104945305
162   196713                                You Only Live Twice      9500000     111600000
163   196801                            The Thomas Crown Affair      4300000      14000000
164   196802                            Chitty Chitty Bang Bang     10000000       7500445
165   196803                                         Funny Girl     14100000      58707416
166   196804                                              Star!     14320000      14000000
167   196805                                    For Love of Ivy      2590000             0
168   196812                    On Her Majesty's Secret Service      7000000      82000000
169   196901                 Butch Cassidy and the Sundance Kid      6000000     102308889
170   196902                                          True Grit            0        275000
171   196903                                   The Happy Ending      2000000             0
172   196904                                 The Sterile Cuckoo            0      14000000
173   196905                      The Prime of Miss Jean Brodie      2750000         14500
174   197001                         Lovers and Other Strangers            0       5484000
175   197002                                       Darling Lili     25000000       3250000
176   197003                                   Pieces of Dreams            0             0
177   197004                                             Madron            0             0
178   197101                                              Shaft      1125000      12121618
179   197102                           Bedknobs and Broomsticks     20000000      17900000
180   197103                        Bless the Beasts & Children            0        212000
181   197104                           Sometimes a Great Notion      3660000             0
182   197112                               Diamonds Are Forever      7200000     116019547
183   197113                Willy Wonka & The Chocolate Factory      3000000       4000000
184   197201                             The Poseidon Adventure      5000000      84563118
185   197202                                                Ben            0        770000
186   197203               The Life and Times of Judge Roy Bean            0      16500000
187   197301                                    The Way We Were      5000000      50000000
188   197302                                   Live and Let Die      7000000     126400000
189   197303                                   A Touch of Class            0      18312000
190   197304                                         Robin Hood      5000000      33000000
191   197305                                 Cinderella Liberty      2465000             0
192   197312                        Pat Garrett & Billy the Kid      4638783      11000000
193   197313                                     The Wicker Man       810000        885371
194   197401                               The Towering Inferno     14000000     116000000
195   197402                                    Blazing Saddles      2600000     119500000
196   197403                                              Benji       500000      39550000
197   197404                                  The Little Prince      6000000       1000000
198   197412                        The Man With The Golden Gun      7000000      97600000
199   197413                                         Emmanuelle       500000      20200000
200   197501                                          Nashville      2200000       9995555
201   197502                                         Funny Lady      8500000      40055897
202   197503                                             Whiffs            0             0
203   197504                                           Mahogany            0       5000000
204   197601                                     A Star Is Born      6000000      80000000
205   197602                                              Rocky      1000000     117253345
206   197603                     The Pink Panther Strikes Again      6000000      33833201
207   197604                                           The Omen      2800000      60922980
208   197701                               You Light Up My Life            0             0
209   197702                               The Spy Who Loved Me     13500000     185438673
210   197703                                      Pete's Dragon     10000000      39600000
211   197704                                       The Rescuers      7500000     169015869
212   197712                                 New York, New York     14000000      16400000
213   197713                               Saturday Night Fever      3500000     237113184
214   197717                                       The Greatest            0       8284000
215   197801                              Thank God It's Friday      2200000             0
216   197802                                             Grease      6000000     396271103
217   197803                                          Foul Play      5000000      45000000

### Eliminación de datos inservibles

Decido eliminar Canciones donde no dispongo de ningún tipo de dato de streams o reproducciones, puesto que la canción no fue localizada ni a través de las API ni en búsqueda manual en Spotify.

In [14]:
# Display Missing Streams and Playcounts
missing_mask = (df_songs_aux['streams_original'].isna() & df_songs_aux['streams_others'].isna() 
                & df_songs_aux['lastfm_track_playcount'].isna() & df_songs_aux['lastfm_track_listeners'].isna())

cols_to_view = [
    'song_id', 'song_title',
    'streams_original', 'streams_others',
    'lastfm_track_playcount','lastfm_track_listeners'
]

# Apply the filter and view the results
df_missing = df_songs_aux.loc[missing_mask, cols_to_view]
display(df_missing)

,song_id,song_title,streams_original,streams_others,lastfm_track_playcount,lastfm_track_listeners
257,198304,Over You,NaN,NaN,NaN,NaN
315,199005,I'm Checkin' Out,NaN,NaN,NaN,NaN
337,199405,Look What Love Has Done,NaN,NaN,NaN,NaN
396,200405,In The Deep,NaN,NaN,NaN,NaN

In [15]:
# Delete the invalid songs
delete_mask = ((df_songs_aux['song_id'] == 198304) | (df_songs_aux['song_id'] == 199005)
               | (df_songs_aux['song_id'] == 199405) | (df_songs_aux['song_id'] == 199405))

df_songs_aux.drop(df_songs_aux[delete_mask].index, inplace=True)
df_songs_aux.reset_index(drop=True, inplace=True)

display(df_songs_aux[['song_id', 'song_title', 
                      'streams_original', 'streams_others',
                      'lastfm_track_playcount','lastfm_track_listeners']].info())

<class 'pandas.DataFrame'>
RangeIndex: 497 entries, 0 to 496
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   song_id                 497 non-null    int64
 1   song_title              497 non-null    str
 2   streams_original        469 non-null    float64
 3   streams_others          105 non-null    float64
 4   lastfm_track_playcount  487 non-null    float64
 5   lastfm_track_listeners  487 non-null    float64
dtypes: float64(4), int64(1), str(1)
memory usage: 32.0 KB

None

### Columnas Booleanas

Transformamos a valores booleanos algunas columnas que habían sido extraídas como texto (Y / N)

In [16]:
df_songs_aux = df_songs_aux.assign(
    oscar_song_nominee = lambda x: x['oscar_song_nominee'] == 'Y',
    oscar_song_win = lambda x: x['oscar_song_win'] == 'Y',
    grammy_song_nominee = lambda x: x['grammy_song_nominee'] == 'Y',
    grammy_song_win = lambda x: x['grammy_song_win'] == 'Y',
    grammy_record_nominee = lambda x: x['grammy_record_nominee'] == 'Y',
    grammy_record_win = lambda x: x['grammy_record_win'] == 'Y'
)

display(df_songs_aux[['song_title', 'oscar_song_nominee', 'oscar_song_win', 'grammy_song_nominee', 'grammy_song_win']].head(10))

,song_title,oscar_song_nominee,oscar_song_win,grammy_song_nominee,grammy_song_win
0,The Continental,True,True,False,False
1,Love In Bloom,True,False,False,False
2,Lullaby Of Broadway,True,True,False,False
3,Cheek To Cheek,True,False,False,False
4,Lovely To Look At,True,False,False,False
5,The Way You Look Tonight,True,True,False,False
6,I've Got You Under My Skin,True,False,False,False
7,Pennies From Heaven,True,False,False,False
8,When Did You Leave Heaven,True,False,False,False
9,Did I Remember,True,False,False,False

### Conversión tipos de datos

In [17]:
metric_cols = [
    'streams_original', 
    'streams_others', 
    'lastfm_track_playcount', 
    'lastfm_track_listeners'
]

# Apply to_numeric and cast to Int64
for col in metric_cols:
    df_songs_aux[col] = pd.to_numeric(df_songs_aux[col], errors='coerce').astype('Int64')

# print(df_songs_aux[metric_cols].head().to_string())
print("\nData Types:")
print(df_songs_aux[metric_cols].dtypes)

Data Types:
streams_original          Int64
streams_others            Int64
lastfm_track_playcount    Int64
lastfm_track_listeners    Int64
dtype: object

In [18]:
metric_cols = [
    'streams_original', 
    'streams_others', 
    'lastfm_track_playcount', 
    'lastfm_track_listeners'
]

# Cleanup Zeroes
# Replace exactly 0 with pd.NA across all specified columns
df_songs_aux[metric_cols] = df_songs_aux[metric_cols].replace(0, pd.NA)

# Check how many zeros were successfully converted to missing values
print("Missing values after converting zeros:")
print(df_songs_aux[metric_cols].isna().sum())

Missing values after converting zeros:
streams_original           28
streams_others            392
lastfm_track_playcount     12
lastfm_track_listeners     12
dtype: int64

### Imputación columna de Streams

In [19]:
# Imputate the maximum between the two columns for each row
df_songs_aux['streams_obs_max'] = (
    df_songs_aux[['streams_original', 'streams_others']]
    .max(axis=1)
    .astype('Int64') # Maintain our nullable integer type
)

print(df_songs_aux[['streams_original', 'streams_others', 'streams_obs_max']].head(10))
# print(df_songs_aux[['streams_obs_max']].describe())
# print(df_songs_aux[['streams_obs_max']].info())

   streams_original  streams_others  streams_obs_max
0             65000            <NA>            65000
1             15800          171500           171500
2             37200         7020000          7020000
3          28200000       210100000        210100000
4            218000            <NA>           218000
5           7000000       269900000        269900000
6            103400       268000000        268000000
7           1000000        73700000         73700000
8              <NA>          348000           348000
9           1200000        34500000         34500000

### Normalización Streams

In [20]:
# Percentiles and Logarithmic Normalization of Streams

# 1. Percentile to 0-100 Scale
df_songs_aux['streams_percentile'] = (
    df_songs_aux['streams_obs_max'].rank(pct=True) * 100
).round(2)

# 2. Logarithmic to 0-100 Scale (Min-Max Scaling)
# First, get the raw log values
log_streams = np.log10(df_songs_aux['streams_obs_max'].astype(float))

# Calculate the minimum and maximum of those log values
log_min = log_streams.min()
log_max = log_streams.max()

# Apply Min-Max scaling: (value - min) / (max - min) * 100
df_songs_aux['streams_normalized'] = (
    ((log_streams - log_min) / (log_max - log_min)) * 100
).round(2)

print(df_songs_aux[['streams_obs_max', 'streams_percentile', 'streams_normalized']].head(10))

   streams_obs_max  streams_percentile  streams_normalized
0            65000                8.69               26.93
1           171500               11.72               33.32
2          7020000               43.23               57.74
3        210100000               79.19               80.11
4           218000               12.93               34.89
5        269900000               81.62               81.75
6        268000000               81.41               81.71
7         73700000               69.49               73.21
8           348000               15.76               37.97
9         34500000               59.19               68.22

In [21]:
lastfm_cols = ['lastfm_track_playcount', 'lastfm_track_listeners']

for col in lastfm_cols:
    # 1. Percentile to 0-100 Scale
    df_songs_aux[f'{col}_percentile'] = (
        df_songs_aux[col].rank(pct=True) * 100
    ).round(2)
    
    # 2. Logarithmic to 0-100 Scale (Min-Max)
    # Cast to float for np.log10
    log_vals = np.log10(df_songs_aux[col].astype(float))
    log_min = log_vals.min()
    log_max = log_vals.max()
    
    df_songs_aux[f'{col}_normalized'] = (
        ((log_vals - log_min) / (log_max - log_min)) * 100
    ).round(2)

print(df_songs_aux[[
    'lastfm_track_playcount', 
    'lastfm_track_playcount_percentile', 
    'lastfm_track_playcount_normalized',
    'lastfm_track_listeners_percentile',
    'lastfm_track_listeners_normalized'
]].head(10).to_string())

   lastfm_track_playcount  lastfm_track_playcount_percentile  lastfm_track_playcount_normalized  lastfm_track_listeners_percentile  lastfm_track_listeners_normalized
0                   19965                              27.01                              57.80                              33.81                              63.06
1                    6003                              18.35                              50.79                              20.21                              53.57
2                   47022                              37.11                              62.80                              44.12                              68.13
3                 1765062                              85.77                              83.97                              89.48                              89.58
4                    3571                              15.67                              47.75                              17.53                              49.66
5                 2714285                              89.07                              86.48                              91.55                              91.61
6                 2156175                              87.01                              85.13                              90.31                              89.94
7                  650279                              70.31                              78.14                              76.08                              83.36
8                    7220                               20.0                              51.86                              21.65                              54.76
9                  276915                              59.18                              73.15                              66.39                              79.83

### Normalización Datos de AM y CM

In [22]:
# Chart Masters and Acclaimed Music metric normalization

# ---------------------------------------------------------
# 1. Normalizing Equivalent Album Sales (EAS)
# ---------------------------------------------------------
col_eas = 'cm_song_eas'

# Fill missing sales with 0
eas_filled = df_songs_aux[col_eas].fillna(0).astype(float)

# Percentile
df_songs_aux[f'{col_eas}_percentile'] = (
    eas_filled.rank(pct=True) * 100
).round(2)

# Apply Log Shift (+1) because we now have true zeros
log_vals_eas = np.log10(eas_filled + 1)
log_min_eas = log_vals_eas.min()
log_max_eas = log_vals_eas.max()

df_songs_aux[f'{col_eas}_normalized'] = (
    ((log_vals_eas - log_min_eas) / (log_max_eas - log_min_eas)) * 100
).round(2)

# ---------------------------------------------------------
# 2. Normalizing the Ranking Columns (AM & CM)
# ---------------------------------------------------------
rank_cols = ['am_ranking', 'cm_ranking']

for col in rank_cols:
    # Find the worst (highest number) rank on the chart
    worst_rank = df_songs_aux[col].max()
    
    # Fill unranked songs with worst_rank + 1
    rank_filled = df_songs_aux[col].fillna(worst_rank + 1).astype(float)
    
    # A. Inverted Percentile
    df_songs_aux[f'{col}_percentile'] = (
        rank_filled.rank(pct=True, method='min', ascending=False) * 100
    ).round(2)
    
    # B. Inverted Logarithmic Min-Max
    log_vals = np.log10(rank_filled)
    log_min = log_vals.min()
    log_max = log_vals.max()
    
    df_songs_aux[f'{col}_normalized'] = (
        100 - (((log_vals - log_min) / (log_max - log_min)) * 100)
    ).round(2)

# Verify the inversion
# A song with cm_ranking of 1 should have a normalized score of 100.
cols_to_check = [
    'am_ranking', 'am_ranking_percentile', 'am_ranking_normalized',
    'cm_ranking', 'cm_ranking_percentile', 'cm_ranking_normalized',
    'cm_song_eas', 'cm_song_eas_normalized'
]
print(df_songs_aux.sort_values('cm_ranking')[cols_to_check].head(15).to_string())

     am_ranking  am_ranking_percentile  am_ranking_normalized  cm_ranking  cm_ranking_percentile  cm_ranking_normalized  cm_song_eas  cm_song_eas_normalized
347        3055                  93.16                  27.65           1                 100.00                 100.00     64042000                  100.00
216         138                 100.00                 100.00           9                  99.80                  76.10     34307000                   96.53
317        4759                  90.54                  17.30          39                  99.60                  60.16     21807000                   94.01
161         786                  97.99                  59.36          53                  99.40                  56.82     19677000                   93.43
39          336                  98.59                  79.21          55                  99.20                  56.42     19602000                   93.41
105         160                  99.60                  96.54          61                  98.99                  55.29     18565000                   93.11
378         273                  98.99                  84.06          63                  98.79                  54.94     18420000                   93.07
345        <NA>                   0.20                   0.00          85                  98.59                  51.68     17019000                   92.63
217        1862                  96.58                  39.22          88                  98.39                  51.31     16800000                   92.56
318        1450                  97.38                  45.06         137                  98.19                  46.49     14593000                   91.77
187        3030                  93.56                  27.84         144                  97.99                  45.95     14387000                   91.69
321        8889                  84.10                   2.70         191                  97.79                  42.88     12402000                   90.87
206        <NA>                   0.20                   0.00         202                  97.59                  42.27     11993000                   90.68
149         189                  99.20                  92.65         221                  97.38                  41.29     11421000                   90.41
261        5304                  89.13                  14.77         225                  97.18                  41.10     11213000                   90.31

### Normalización de Song Awards

In [23]:
# Create a column with the major Song awards
df_songs_aux['song_major_awards'] = (df_songs_aux['oscar_song_win'].astype('Int64') 
                                     + df_songs_aux['grammy_song_win'].astype('Int64')
                                     + df_songs_aux['grammy_record_win'].astype('Int64'))

df_songs_aux['song_major_awards'] = df_songs_aux['song_major_awards'].astype('Int64')

# Assign an Awards combined value percent

# 1. Calculate the weighted score (max 10)
df_songs_aux['awards_combined'] = (
    (df_songs_aux['oscar_song_nominee'] * 3) +
    (df_songs_aux['oscar_song_win'] * 3) +
    (df_songs_aux['grammy_song_nominee'] * 1) +
    (df_songs_aux['grammy_song_win'] * 1) +
    (df_songs_aux['grammy_record_nominee'] * 1) +
    (df_songs_aux['grammy_record_win'] * 1)
)

# 2. Scale it to 0-100 to match your other percentile/normalized metrics
df_songs_aux['awards_combined_percent'] = df_songs_aux['awards_combined'] * 10

# Cast the new percentage column to a nullable float
df_songs_aux['awards_combined_percent'] = df_songs_aux['awards_combined_percent'].astype('Float64')

print(df_songs_aux[['song_title', 'song_major_awards', 'awards_combined_percent']].head().to_string())

            song_title  song_major_awards  awards_combined_percent
0      The Continental                  1                     60.0
1        Love In Bloom                  0                     30.0
2  Lullaby Of Broadway                  1                     60.0
3       Cheek To Cheek                  0                     30.0
4    Lovely To Look At                  0                     30.0

### Normalización datos de Recordings

In [24]:
# Calculate percentiles (0.0 to 1.0) and multiply by 100 for a 0-100 scale
df_songs_aux['mb_original_recordings_pct'] = (
    df_songs_aux['mb_original_recordings_count'].rank(pct=True) * 100
)

df_songs_aux['mb_cover_recordings_pct'] = (
    df_songs_aux['mb_cover_recordings_count'].rank(pct=True) * 100
)

# Preview the new metrics alongside the old ones to verify
print(df_songs_aux[[
    'mb_original_recordings_count', 'mb_original_recordings_pct', 
    'mb_cover_recordings_count', 'mb_cover_recordings_pct'
]].describe().to_string())

       mb_original_recordings_count  mb_original_recordings_pct  mb_cover_recordings_count  mb_cover_recordings_pct
count                    487.000000                  487.000000                 487.000000               487.000000
mean                      20.406571                   50.102669                  54.993840                50.102669
std                       44.190653                   28.785153                 122.023298                28.819429
min                        0.000000                    7.494867                   0.000000                 8.316222
25%                        1.000000                   22.587269                   1.000000                20.944559
50%                        5.000000                   49.383984                  14.000000                50.410678
75%                       21.000000                   74.845996                  54.000000                75.051335
max                      378.000000                  100.000000                1295.000000               100.000000

In [25]:
# Recordings Factor Normalization

# Step 1: Calculate the weighted raw score first
df_songs_aux['weighted_recordings_raw'] = (
    df_songs_aux['mb_original_recordings_count'].fillna(0) + 
    (df_songs_aux['mb_cover_recordings_count'].fillna(0) * 2)
)

# Step 2: Identify the true extraction failures (where the sum of both columns is 0)
zero_totals_mask = df_songs_aux[['mb_original_recordings_count', 'mb_cover_recordings_count']].sum(axis=1) == 0

# Step 3: Overwrite the weighted score with NaN only for those failed extractions
df_songs_aux.loc[zero_totals_mask, 'weighted_recordings_raw'] = np.nan

# Step 4: Calculate the final percentile metric
df_songs_aux['recordings_metric_pct'] = (
    df_songs_aux['weighted_recordings_raw'].rank(pct=True) * 100
)

df_songs_aux['mb_original_recordings_pct'] = df_songs_aux['mb_original_recordings_pct'].round(2)
df_songs_aux['mb_cover_recordings_pct'] = df_songs_aux['mb_cover_recordings_pct'].round(2)
df_songs_aux['recordings_metric_pct'] = df_songs_aux['recordings_metric_pct'].round(2)

# Check how many valid scores survived the filter
print("Valid scores remaining:", df_songs_aux['recordings_metric_pct'].notna().sum())

Valid scores remaining: 460

### Datos de Film Awards

In [26]:
print(df_films_aux[['film_title', 'omdb_awards']].head())

             film_title                                        omdb_awards
0      The Gay Divorcee          Won 1 Oscar. 4 wins & 5 nominations total
1      She Loves Me Not  Nominated for 1 Oscar. 1 win & 1 nomination total
2  Gold Diggers of 1935            Won 1 Oscar. 1 win & 1 nomination total
3               Top Hat  Nominated for 4 Oscars. 7 wins & 6 nominations...
4               Roberta         Nominated for 1 Oscar. 2 nominations total

In [27]:
# Awards Calculations

# Columns tidy up
df_films_aux['oscar_wins'] = df_films_aux['oscar_wins'].fillna(0).astype(int)
df_films_aux['oscar_nominations'] = df_films_aux['oscar_nominations'].fillna(0).astype(int)

# ==========================================
# REGEX EXTRACTION
# ==========================================
# r'...'   -> Tells Python this is a "raw string" regex pattern
# (\d+)    -> The capture group. \d means "digits", + means "one or more". It grabs the number!
# \s*      -> Accounts for any spaces (or lack of spaces) between the number and the word
# win      -> The exact text to look for right after the number. 

df_films_aux['total_wins'] = df_films_aux['omdb_awards'].str.extract(r'(\d+)\s*win', expand=False)
df_films_aux['total_nominations'] = df_films_aux['omdb_awards'].str.extract(r'(\d+)\s*nomination', expand=False)

# Fill NaN with 0
df_films_aux['total_wins'] = df_films_aux['total_wins'].fillna(0)
df_films_aux['total_nominations'] = df_films_aux['total_nominations'].fillna(0)

# Convert to standard integers so you can do math on them later
df_films_aux['total_wins'] = df_films_aux['total_wins'].astype(int)
df_films_aux['total_nominations'] = df_films_aux['total_nominations'].astype(int)

# ==========================================
# LOGICAL RECALCULATION (The "True" Nominations)
# ==========================================
# Since OMDB treats "wins" and "nominations" as mutually exclusive,
# we add the wins to the nominations to get the chronological total.
df_films_aux['total_nominations'] = df_films_aux['total_nominations'] + df_films_aux['total_wins']

# Drop raw column
# df_films_aux = df_films_aux.drop(columns=['omdb_awards'])

# Display resulting dataframe
print(df_films_aux[['film_title', 'oscar_wins', 'oscar_nominations', 'total_wins', 'total_nominations']].head().to_string())

             film_title  oscar_wins  oscar_nominations  total_wins  total_nominations
0      The Gay Divorcee           1                  5           4                  9
1      She Loves Me Not           0                  1           1                  2
2  Gold Diggers of 1935           1                  2           1                  2
3               Top Hat           0                  4           7                 13
4               Roberta           0                  1           0                  2

In [28]:
# Song Awards Calculation
nom_columns = ['oscar_song_nominee', 'grammy_song_nominee', 'grammy_record_nominee']
win_columns = ['oscar_song_win', 'grammy_song_win', 'grammy_record_win']

df_songs_aux['song_nominations'] = df_songs_aux[nom_columns].sum(axis=1)
df_songs_aux['song_wins'] = df_songs_aux[win_columns].sum(axis=1)

display(df_songs_aux[['song_title', 'song_nominations', 'song_wins']].head())

            song_title  song_nominations  song_wins
0      The Continental                 1          1
1        Love In Bloom                 1          0
2  Lullaby Of Broadway                 1          1
3       Cheek To Cheek                 1          0
4    Lovely To Look At                 1          0

### Ajustar Datos Monetarios

In [29]:
df_films_aux['tmdb_budget'] = pd.to_numeric(df_films_aux['tmdb_budget'], errors='coerce')
df_films_aux['tmdb_revenue'] = pd.to_numeric(df_films_aux['tmdb_revenue'], errors='coerce')

df_films_aux['tmdb_budget'] = df_films_aux['tmdb_budget'].replace(0, np.nan)
df_films_aux['tmdb_revenue'] = df_films_aux['tmdb_revenue'].replace(0, np.nan)

print("Calculating historical multipliers...")

# Step A: Find the unique years in your dataset
unique_years = df_films_aux['year'].dropna().unique()

# Step B: Create a dictionary of multipliers ($1 in that year -> Current Dollars)
cpi_multipliers = {}

for year in unique_years:
    try:
        # Calculate what $1 from this release year is worth today
        cpi_multipliers[year] = cpi.inflate(1, int(year))
    except Exception as e:
        print(f"Warning: Could not get CPI for {year}. Defaulting to 1.0 multiplier.")
        cpi_multipliers[year] = 1.0

# Step C: Map the dictionary back to the DataFrame to create a new multiplier column
df_films_aux['cpi_multiplier'] = df_films_aux['year'].map(cpi_multipliers)

# Multiply the entire column
df_films_aux['budget_adjusted'] = df_films_aux['tmdb_budget'] * df_films_aux['cpi_multiplier']
df_films_aux['revenue_adjusted'] = df_films_aux['tmdb_revenue'] * df_films_aux['cpi_multiplier']

# Round the results and convert to Nullable Integers
df_films_aux['budget_adjusted'] = df_films_aux['budget_adjusted'].round().astype('Int64')
df_films_aux['revenue_adjusted'] = df_films_aux['revenue_adjusted'].round().astype('Int64')

# Drop the auxiliar multiplier column
# df_films_aux = df_films_aux.drop(columns=['cpi_multiplier'])

# Show the results
print(df_films_aux[['film_title', 'year', 'tmdb_budget', 'budget_adjusted']])

Calculating historical multipliers...
                   film_title  year  tmdb_budget  budget_adjusted
0            The Gay Divorcee  1934     520000.0         12493310
1            She Loves Me Not  1934          NaN             <NA>
2        Gold Diggers of 1935  1935          NaN             <NA>
3                     Top Hat  1935     609000.0         14311189
4                     Roberta  1935          NaN             <NA>
..                        ...   ...          ...              ...
462        KPop Demon Hunters  2025  100000000.0        100000000
463                   Sinners  2025  100000000.0        100000000
464              Train Dreams  2025   10000000.0         10000000
465               Viva Verdi!  2025          NaN             <NA>
466  Diane Warren: Relentless  2025          NaN             <NA>

[467 rows x 4 columns]

In [30]:
# ==========================================
# DATA COVERAGE REPORT
# ==========================================
# Let's see how much data we have per decade to understand the gaps
df_films_aux['decade'] = (df_films_aux['year'] // 10) * 10

# Group by decade and calculate the percentage of non-null budgets
coverage = df_films_aux.groupby('decade')['tmdb_budget'].apply(lambda x: x.count() / len(x) * 100)

print("=== BUDGET DATA COVERAGE BY DECADE (%) ===")
print(coverage.round(1))

# TIP: How to handle the gaps in your Final Analysis
# Whenever you do an analysis, define a "Data Integrity" subset if needed:
# df_complete_financials = df_films_aux.dropna(subset=['budget_adjusted', 'revenue_adjusted'])

print("\nAnalysis Tip: There are " + str(len(df_films_aux.dropna(subset=['budget_adjusted']))) + " movies with full financial data.")

=== BUDGET DATA COVERAGE BY DECADE (%) ===
decade
1930    39.1
1940    44.0
1950    62.8
1960    70.7
1970    73.6
1980    92.4
1990    96.3
2000    95.3
2010    85.7
2020    71.4
Name: tmdb_budget, dtype: float64

Analysis Tip: There are 354 movies with full financial data.

### Cálculos de Factores Financieros

In [31]:
df_films_aux['budget_math'] = df_films_aux['budget_adjusted'].astype(float)
df_films_aux['revenue_math'] = df_films_aux['revenue_adjusted'].astype(float)

# Raw ROI Percentage
# Formula: (Revenue - Budget) / Budget
df_films_aux['roi_percent'] = ((df_films_aux['revenue_math'] - df_films_aux['budget_math']) / df_films_aux['budget_math']) * 100

# Commercial Success Factor (The "2.5x Rule")
# Formula: Revenue / (Budget * 2.5)
# This tells us if they exceeded the "break-even" threshold
df_films_aux['commercial_success_factor'] = df_films_aux['revenue_math'] / (df_films_aux['budget_math'] * 2.5)

# Cleanup and Format
# Round for readability (ROI as percentage, Factor as a decimal)
df_films_aux['roi_percent'] = df_films_aux['roi_percent'].round(1)
df_films_aux['commercial_success_factor'] = df_films_aux['commercial_success_factor'].round(2)

# Remove the temporary math columns
df_films_aux = df_films_aux.drop(columns=['budget_math', 'revenue_math'])

print("=== ROI AND COMMERCIAL SUCCESS METRICS ===")
print(df_films_aux[['film_title', 'budget_adjusted', 'revenue_adjusted', 'roi_percent', 'commercial_success_factor']].head(10).to_string())

=== ROI AND COMMERCIAL SUCCESS METRICS ===
             film_title  budget_adjusted  revenue_adjusted  roi_percent  commercial_success_factor
0      The Gay Divorcee         12493310          43246075        246.2                       1.38
1      She Loves Me Not             <NA>              <NA>          NaN                        NaN
2  Gold Diggers of 1935             <NA>              <NA>          NaN                        NaN
3               Top Hat         14311189          75245364        425.8                       2.10
4               Roberta             <NA>              <NA>          NaN                        NaN
5            Swing Time         20520971          60219554        193.5                       1.17
6         Born to Dance             <NA>              <NA>          NaN                        NaN
7   Pennies from Heaven             <NA>              <NA>          NaN                        NaN
8      Sing, Baby, Sing             <NA>              <NA>          NaN                        NaN
9                  Suzy             <NA>              <NA>          NaN                        NaN

### Normalización de métricas Financieras

In [32]:
# Financial Metrics Normalization
financial_cols = [
    'budget_adjusted', 'revenue_adjusted', 
    'roi_percent', 'commercial_success_factor'
]

for col in financial_cols:
    # 1. Percentile Normalization (This works perfectly with negatives/zeros!)
    df_films_aux[f'{col}_percentile'] = (
        df_films_aux[col].rank(pct=True) * 100
    ).round(2)
    
    # 2. Logarithmic Min-Max Normalization
    # Check if the column has any values <= 0
    min_val = df_films_aux[col].min()
    
    if min_val <= 0:
        # LOG SHIFT: Shift the data so the minimum value is exactly 1
        shift_amount = abs(min_val) + 1
        shifted_series = df_films_aux[col].dropna().astype(float) + shift_amount
        log_vals = np.log10(shifted_series)
    else:
        # Standard approach for purely positive columns
        log_vals = np.log10(df_films_aux[col].dropna().astype(float))
        
    log_min = log_vals.min()
    log_max = log_vals.max()
    
    df_films_aux[f'{col}_normalized'] = (
        ((log_vals - log_min) / (log_max - log_min)) * 100
    ).round(2)

# Verify the columns with the tricky zero/negative minimums
cols_to_check = [
    'roi_percent', 'roi_percent_percentile', 'roi_percent_normalized',
    'commercial_success_factor', 'commercial_success_factor_percentile', 'commercial_success_factor_normalized'
]
print(df_films_aux.sort_values('roi_percent')[cols_to_check].head(20).to_string())

     roi_percent  roi_percent_percentile  roi_percent_normalized  commercial_success_factor  commercial_success_factor_percentile  commercial_success_factor_normalized
95        -100.0                    0.31                    0.00                       0.00                                  1.71                                  0.00
60         -99.9                    0.62                    0.92                       0.00                                  1.71                                  0.00
453        -99.8                    1.09                    1.76                       0.00                                  1.71                                  0.00
111        -99.8                    1.09                    1.76                       0.00                                  1.71                                  0.00
89         -99.7                    1.71                    2.54                       0.00                                  1.71                                  0.00
441        -99.7                    1.71                    2.54                       0.00                                  1.71                                  0.00
173        -99.5                    2.18                    3.92                       0.00                                  1.71                                  0.00
112        -99.3                    2.49                    5.13                       0.00                                  1.71                                  0.00
426        -99.1                    2.80                    6.20                       0.00                                  1.71                                  0.00
110        -99.0                    3.12                    6.70                       0.00                                  1.71                                  0.00
91         -98.4                    3.43                    9.23                       0.01                                  3.43                                  0.21
243        -88.0                    3.74                   24.79                       0.05                                  3.89                                  1.01
175        -87.0                    4.05                   25.50                       0.05                                  3.89                                  1.01
416        -85.0                    4.36                   26.80                       0.06                                  4.52                                  1.21
382        -84.6                    4.67                   27.03                       0.06                                  4.52                                  1.21
197        -83.3                    4.98                   27.77                       0.07                                  4.98                                  1.40
462        -75.4                    5.30                   31.34                       0.10                                  5.45                                  1.97
439        -75.3                    5.61                   31.38                       0.10                                  5.45                                  1.97
127        -67.9                    5.92                   33.82                       0.13                                  5.92                                  2.53
276        -63.9                    6.23                   34.92                       0.14                                  6.23                                  2.71

### Normalización Movie Awards

In [39]:
# Calculate the Movie Awards Normalized score

# 1. Calculate the raw weighted prestige score and cast to your standard nullable integer
df_films_aux['movie_awards_score'] = (
    # (df_films_aux['oscar_wins'] * 10) +
    # (df_films_aux['oscar_nominations'] * 5) +
    (df_films_aux['total_wins'] * 10) +
    (df_films_aux['total_nominations'] * 5)
).astype('Int64')

# 2. Apply log10 to tame the massive outliers 
# (We temporarily cast to float for the numpy math, adding 1 to avoid log(0))
log_scores = np.log10(df_films_aux['movie_awards_score'].astype(float) + 1)

# 3. Min-Max normalize to a 0-100 scale, round to 2 decimals, and cast to Float64
min_log = log_scores.min()
max_log = log_scores.max()

df_films_aux['movie_awards_normalized'] = (
    ((log_scores - min_log) / (max_log - min_log)) * 100
).round(2).astype('Float64')

# Verify the output
cols_to_view = [
    'oscar_nominations', 'oscar_wins', 
    'total_nominations', 'total_wins', 
    'movie_awards_score', 'movie_awards_normalized'
]
print(df_films_aux[cols_to_view].head().to_string())

   oscar_nominations  oscar_wins  total_nominations  total_wins  movie_awards_score  movie_awards_normalized
0                  5           1                  9           4                  85                    49.54
1                  1           0                  2           1                  20                    33.86
2                  2           1                  2           1                  20                    33.86
3                  4           0                 13           7                 135                    54.64
4                  1           0                  2           0                  10                    26.67

In [35]:
# 1. Create the tie-breaker score (Wins as integers, Nominations as decimals)
composite_oscar_score = (
    df_films_aux['oscar_wins'].fillna(0) + 
    (df_films_aux['oscar_nominations'].fillna(0) * 0.01)
)

# 2. Rank the combined score
df_films_aux['oscar_wins_pct'] = (
    composite_oscar_score.rank(method='min', pct=True) * 100
).round(2).astype('Float64')

# Show results
cols_to_view = [
    'film_title', 'year',
    'oscar_nominations', 'oscar_wins', 
    'oscar_wins_pct', 'movie_awards_normalized'
]

print(df_films_aux[cols_to_view].head(10).to_string())
# print()
# print(df_films_aux[['oscar_wins_pct']].describe())

             film_title  year  oscar_nominations  oscar_wins  oscar_wins_pct  movie_awards_normalized
0      The Gay Divorcee  1934                  5           1           81.37                    52.48
1      She Loves Me Not  1934                  1           0           12.85                    32.13
2  Gold Diggers of 1935  1935                  2           1           73.66                    41.74
3               Top Hat  1935                  4           0           61.67                    52.86
4               Roberta  1935                  1           0           12.85                    28.84
5            Swing Time  1936                  2           1           73.66                    50.65
6         Born to Dance  1936                  2           0           44.75                    33.92
7   Pennies from Heaven  1936                  1           0           12.85                    26.05
8      Sing, Baby, Sing  1936                  1           0           12.85                    26.05
9                  Suzy  1936                  1           0           12.85                    26.05

### Normalización Popularidad Films

In [40]:
# ==========================================
# Casting the data types
# ==========================================

# 1. Counts (Cast to nullable Int64)
# IMDB Votes: Force string, remove commas, coerce
df_films_aux['omdb_imdb_votes'] = pd.to_numeric(
    df_films_aux['omdb_imdb_votes'].astype(str).str.replace(',', ''), errors='coerce'
).astype('Int64')


# 2. Existing 0-100 Scores (Clean and cast DIRECTLY to nullable Float64)
# Rotten Tomatoes: Force string, remove '%', coerce
df_films_aux['omdb_rotten_tomatoes'] = pd.to_numeric(
    df_films_aux['omdb_rotten_tomatoes'].astype(str).str.replace('%', ''), errors='coerce'
).astype('Float64')

# Metascore: Coerce "N/A"
df_films_aux['omdb_metascore'] = pd.to_numeric(
    df_films_aux['omdb_metascore'], errors='coerce'
).astype('Float64')


# 3. 0-10 Scores (Clean, rescale to 0-100, round, and cast to nullable Float64)

# IMDB Rating: First, coerce "N/A" and cast to Float64
df_films_aux['omdb_imdb_rating'] = pd.to_numeric(
    df_films_aux['omdb_imdb_rating'], errors='coerce'
).astype('Float64')

# Only multiply by 10 if the column hasn't been scaled yet
if df_films_aux['omdb_imdb_rating'].max() <= 10:
    df_films_aux['omdb_imdb_rating'] = (df_films_aux['omdb_imdb_rating'] * 10).round(2)

# TMDB Vote Average: Cast to Float64
df_films_aux['tmdb_vote_average'] = df_films_aux['tmdb_vote_average'].astype('Float64')

# Only multiply by 10 if the column hasn't been scaled yet
if df_films_aux['tmdb_vote_average'].max() <= 10:
    df_films_aux['tmdb_vote_average'] = (df_films_aux['tmdb_vote_average'] * 10).round(2)
    
# Verify the changes
cols_to_view = [
    'tmdb_vote_average', 'tmdb_vote_count',
    'omdb_imdb_rating', 'omdb_imdb_votes', 
    'omdb_metascore', 'omdb_rotten_tomatoes'
]
print(df_films_aux[cols_to_view].dtypes)
print("\n", df_films_aux[cols_to_view].head().to_string())

tmdb_vote_average       Float64
tmdb_vote_count           int64
omdb_imdb_rating        Float64
omdb_imdb_votes           Int64
omdb_metascore          Float64
omdb_rotten_tomatoes    Float64
dtype: object

    tmdb_vote_average  tmdb_vote_count  omdb_imdb_rating  omdb_imdb_votes  omdb_metascore  omdb_rotten_tomatoes
0              68.91              147              73.0             9241            80.0                  93.0
1               60.0               11              57.0              227            <NA>                  <NA>
2              65.09               56              69.0             3123            <NA>                 100.0
3              72.53              331              77.0            22008            93.0                 100.0
4              70.82               49              70.0             3720            66.0                  86.0

In [42]:
# === 1. Audience Score (movie_popularity) ===

# === Data Quality Check: Nullify ghost votes ===
# If the rating is missing, force the vote count to 0 so it doesn't skew the denominator
df_films_aux.loc[df_films_aux['tmdb_vote_average'].isna(), 'tmdb_vote_count'] = 0
df_films_aux.loc[df_films_aux['omdb_imdb_rating'].isna(), 'omdb_imdb_votes'] = 0

# Calculate weighted values, filling nulls with 0 to prevent math errors
tmdb_weighted = (df_films_aux['tmdb_vote_average'] * df_films_aux['tmdb_vote_count']).fillna(0)
imdb_weighted = (df_films_aux['omdb_imdb_rating'] * df_films_aux['omdb_imdb_votes']).fillna(0)

# Calculate total votes
total_votes = df_films_aux['tmdb_vote_count'].fillna(0) + df_films_aux['omdb_imdb_votes'].fillna(0)

# Initialize the column
df_films_aux['movie_popularity'] = pd.NA

# Apply the weighted average only where total_votes > 0
mask_has_votes = total_votes > 0
df_films_aux.loc[mask_has_votes, 'movie_popularity'] = (
    (tmdb_weighted[mask_has_votes] + imdb_weighted[mask_has_votes]) / total_votes[mask_has_votes]
).round(2)

# Cast to the consistent nullable float type
df_films_aux['movie_popularity'] = df_films_aux['movie_popularity'].astype('Float64')


# === 2. Critics Score (movie_critics_score) ===

# mean(axis=1) automatically ignores NaNs. 
df_films_aux['movie_critics_score'] = df_films_aux[
    ['omdb_metascore', 'omdb_rotten_tomatoes']
].mean(axis=1).round(2).astype('Float64')

# Let's verify the new combined metrics
cols_to_view = ['movie_popularity', 'movie_critics_score', 'tmdb_vote_average', 'omdb_imdb_rating', 
                'omdb_metascore', 'omdb_rotten_tomatoes']
print(df_films_aux[cols_to_view].head().to_string())

   movie_popularity  movie_critics_score  tmdb_vote_average  omdb_imdb_rating  omdb_metascore  omdb_rotten_tomatoes
0             72.94                 86.5              68.91              73.0            80.0                  93.0
1             57.14                 <NA>               60.0              57.0            <NA>                  <NA>
2             68.93                100.0              65.09              69.0            <NA>                 100.0
3             76.93                 96.5              72.53              77.0            93.0                 100.0
4             70.01                 76.0              70.82              70.0            66.0                  86.0

### Limpieza de tabla de Artistas

In [43]:
print("=== 1. IDENTIFYING THE DUPLICATES ===")
# keep=False tells Pandas to show us ALL rows involved in the duplication, not just the extras
# duplicates_mask = df_artists_aux.duplicated(subset=['artist_id'], keep=False)
# print(df_artists_aux[duplicates_mask].sort_values('artist_id'))

print("\n=== 2. CONSOLIDATING THE DATA ===")
# UPGRADE: Instead of typing out every single column manually, we use a Python 
# "dictionary comprehension" to tell Pandas to use 'first' (first non-null value) 
# for ALL columns in your table, except for 'artist_id' and 'roles'!
aggregation_logic = {col: 'first' for col in df_artists_aux.columns if col not in ['artist_id', 'roles']}

# For 'roles', we want to combine them just in case one row says 'performer' 
# and another says 'composer'. We use a quick lambda with a Python Set to ensure no duplicates.
aggregation_logic['roles'] = lambda x: ', '.join(sorted(set(', '.join(x.dropna()).split(', '))))

# We group by the ID, apply our logic, and reset the index so it remains a flat table
df_artists_clean = (
    df_artists_aux
    .groupby('artist_id', as_index=False)
    .agg(aggregation_logic)
)

# Reorder columns to match the original structure dynamically
df_artists_clean = df_artists_clean[df_artists_aux.columns]

print(df_artists_clean[[
    'artist_id', 'artist_name', 
    'roles', 'mb_artist_type'
    # 'artist_playcount', 'artist_listeners', 
    # 'mb_gender', 'mb_country', 'mb_begin_area', 'mb_disambiguation', 
    # 'mb_lifespan_begin', 'mb_lifespan_end', 'mb_aliases',
    # 'cm_artist_ranking', 'cm_artist_eas'
]].to_string())

=== 1. IDENTIFYING THE DUPLICATES ===

=== 2. CONSOLIDATING THE DATA ===
                              artist_id                         artist_name      roles mb_artist_type
0                            a_r_rahman                        A. R. Rahman  performer         Person
1                               aaliyah                             Aaliyah  performer         Person
2                     abraham_alexander                   Abraham Alexander  performer         Person
3                          abraham_ivan                        Abraham Ivan  performer           None
4                           adam_levine                         Adam Levine  performer           None
5                                 adele                               Adele  performer         Person
6                        adrian_quesada                      Adrian Quesada  performer         Person
7                             aerosmith                           Aerosmith  performer          Group
8                                   aha                                A-ha  performer          Group
9                            aimee_mann                          Aimee Mann  performer         Person
10                        alan_blaikley                       Alan Blaikley  performer         Person
11                          alan_menken                         Alan Menken  performer         Person
12                         alessia_cara                        Alessia Cara  performer         Person
13                           alice_faye                          Alice Faye  performer         Person
14                          alicia_keys                         Alicia Keys  performer         Person
15                        alison_krauss                       Alison Krauss  performer         Person
16                       allison_moorer                      Allison Moorer  performer         Person
17                            amy_adams                           Amy Adams  performer         Person
18                             ana_laan                            Ana Laan  performer         Person
19                            andra_day                           Andra Day  performer         Person
20                         andre_previn                        Andre Previn  performer         Person
21                       andrea_bocelli                      Andrea Bocelli  performer         Person
22                       andrew_higgins                      Andrew Higgins  performer         Person
23                  andrew_lloyd_webber                 Andrew Lloyd Webber  performer         Person
24                         andré_previn                        André Previn  performer         Person
25                        andy_williams                       Andy Williams  performer         Person
26                      angela_lansbury                     Angela Lansbury  performer         Person
27                      anika_noni_rose                     Anika Noni Rose  performer         Person
28                          anita_ellis                         Anita Ellis  performer         Person
29                          ann_sothern                         Ann Sothern  performer         Person
30                         ann_southern                        Ann Southern  performer         Person
31                        anne_hathaway                       Anne Hathaway  performer         Person
32                         annie_lennox                        Annie Lennox  performer         Person
33                               anohni                              Anohni  performer         Person
34                     antonio_banderas                    Antonio Banderas  performer         Person
35                               antony                              Antony  performer         Person
36                 antônio_carlos_jobim                Antônio Carlos Jobim  performer         Person
37                            ar_rahman                         A.R. Rahman  performer           None
38                          archie_pena                         Archie Pena  performer         Person
39                        ariana_grande                       Ariana Grande  performer         Person
40                           artie_shaw                          Artie Shaw  performer         Person
41                        ashton_rhodes                       Ashton Rhodes  performer           None
42                       audrey_hepburn                      Audrey Hepburn  performer         Person
43                          audrey_nuna                         AUDREY NUNA  performer         Person
44                               aurora                              AURORA  performer         Person
45                           b_j_thomas                        B. J. Thomas  performer           None
46                     barbra_streisand                    Barbra Streisand  performer         Person
47                        barry_manilow                       Barry Manilow  performer         Person
48                              becky_g                             Becky G  performer         Person
49                             bee_gees                            Bee Gees  performer          Group
50                           ben_martin                          Ben Martin  performer         Person
51                           ben_sidran                          Ben Sidran  performer         Person
52                        benny_goodman                       Benny Goodman  performer         Person
53                               berlin                              Berlin  performer          Group
54                       bernard_keeffe                      Bernard Keeffe  performer         Person
55                        betty_buckley                       Betty Buckley  performer         Person
56                         betty_grable                        Betty Grable  performer         Person
57                          betty_noyes                         Betty Noyes  performer           None
58                              beyoncé                             Beyoncé  performer         Person
59                           bill_conti                          Bill Conti  performer         Person
60                      bill_evans_trio                     Bill Evans Trio  performer          Group
61                          bill_medley                         Bill Medley  performer         Person
62                        billie_eilish                       Billie Eilish  performer         Person
63                       billie_holiday                      Billie Holiday  performer         Person
64                        billy_crystal                       Billy Crystal  performer         Person
65                       billy_eckstine                      Billy Eckstine  performer         Person
66                          bing_crosby                         Bing Crosby  performer         Person
67                            bird_york                           Bird York  performer         Person
68                            bj_thomas                         B.J. Thomas  performer         Person
69                                björk                               Björk  performer         Person
70                              blondie                             Blondie  performer          Group
71                           blue_rodeo                          Blue Rodeo  performer          Group
72                           bob_crosby                          Bob Crosby  performer         Person
73                            bob_dylan                           Bob Dylan  performer         Person
74                             bob_hope                            Bob Hope  performer         Person
75                          bob_russell                         Bob Russell  performer         Person
76                            bob_seger                           Bob Seger  performer         Person
77                          bobby_darin                         Bobby Darin  performer         Person
78                      bobby_goldsboro                     Bobby Goldsboro  performer         Person
79                      bombay_jayashri                     Bombay Jayashri  performer         Person
80                boston_pops_orchestra               Boston Pops Orchestra  performer      Orchestra
81                            brad_kane                           Brad Kane  performer         Person
82                       bradley_cooper                      Bradley Cooper  performer         Person
83                       brandi_carlile                      Brandi Carlile  performer         Person
84                     bruce_reitherman                    Bruce Reitherman  performer         Person
85                    bruce_springsteen                   Bruce Springsteen  performer         Person
86                        bruno_coulais                       Bruno Coulais  performer         Person
87                          bryan_adams                         Bryan Adams  performer         Person
88                     cabin_in_the_sky                    Cabin In The Sky  performer           None
89                       caetano_veloso                      Caetano Veloso  performer         Person
90                      calogero_barino                     Calogero Barino  performer           None
91                              camille                             Camille  performer         Person
92                          carina_voly                         Carina Voly  performer         Person
93                          carla_bruni                         Carla Bruni  performer         Person
94                          carly_simon                         Carly Simon  performer         Person
95                     carmen_cavallaro                    Carmen Cavallaro  performer         Person
96                       carmen_twillie                      Carmen Twillie  performer         Person
97                           carpenters                          Carpenters  performer          Group
98                    catherine_russell                   Catherine Russell  performer         Person
99                  catherine_zetajones                Catherine Zeta-Jones  performer         Person
100                             celeste                             Celeste  performer          Group
101                        chandra_bose                        Chandra Bose  performer         Person
102                       charley_pride                       Charley Pride  performer         Person
103                        charlie_puth                        Charlie Puth  performer         Person
104                                cher                                Cher  performer         Person
105                          chet_baker                          Chet Baker  performer         Person
106         chorus_beauty_and_the_beast       Chorus - Beauty And the Beast  performer          Choir
107                       chris_cornell                       Chris Cornell  performer         Person
108                         chris_isaak                         Chris Isaak  performer         Person
109                        chrissy_metz                        Chrissy Metz  performer         Person
110                     christina_perri                     Christina Perri  performer         Person
111                   christopher_cross                   Christopher Cross  performer         Person
112                         cilla_black                         Cilla Black  performer         Person
113                       cliff_edwards                       Cliff Edwards  performer         Person
114                      clifford_brown                      Clifford Brown  performer         Person
115    coastal_communities_concert_band    Coastal Communities Concert Band  performer          Group
116                            coco_lee                            CoCo Lee  performer           None
117                              common                              Common  performer         Person
118  common_praise_gospelchoir_salzburg  Common Praise Gospelchoir Salzburg  performer           None
119                      compay_segundo                      Compay Segundo  performer         Person
120                      connee_boswell                      Connee Boswell  performer         Person
121                      connie_francis                      Connie Francis  performer         Person
122                              coolio                              Coolio  performer         Person
123                      counting_crows                      Counting Crows  performer          Group
124                       cynthia_erivo                       Cynthia Erivo  performer         Person
125                         céline_dion                         Céline Dion  performer         Person
126                  dame_marie_rambert                  Dame Marie Rambert  performer           None
127                   dame_monica_mason                   Dame Monica Mason  performer           None
128                          dan_warner                          Dan Warner  performer         Person
129                          danny_kaye                          Danny Kaye  performer         Person
130                         david_bowie                         David Bowie  performer         Person
131                         david_byrne                         David Byrne  performer         Person
132                          david_lang                          David Lang  performer         Person
133                         david_shire                         David Shire  performer         Person
134                         dean_martin                         Dean Martin  performer         Person
135                       deanna_durbin                       Deanna Durbin  performer         Person
136                     debbie_reynolds                     Debbie Reynolds  performer         Person
137                         debby_boone                         Debby Boone  performer         Person
138                    deniece_williams                    Deniece Williams  performer         Person
139                       dennis_morgan                       Dennis Morgan  performer         Person
140                      diana_coupland                      Diana Coupland  performer         Person
141                         diana_krall                         Diana Krall  performer         Person
142                          diana_ross                          Diana Ross  performer         Person
143                         dick_haymes                         Dick Haymes  performer         Person
144                         dick_powell                         Dick Powell  performer         Person
145                       dick_van_dyke                       Dick Van Dyke  performer         Person
146     dick_van_dyke_and_the_vantastix     Dick Van Dyke and The Vantastix  performer           None
147                                dido                                Dido  performer         Person
148                      dillon_lubbers                      Dillon Lubbers  performer           None
149                     dimitri_tiomkin                     Dimitri Tiomkin  performer         Person
150                         dinah_shore                         Dinah Shore  performer         Person
151                      dionne_warwick                      Dionne Warwick  performer         Person
152                              disney                              Disney  performer          Other
153                disney_studio_chorus                Disney Studio Chorus  performer          Choir
154                     dizzy_gillespie                     Dizzy Gillespie  performer         Person
155                        dolly_parton                        Dolly Parton  performer         Person
156                          don_ameche                          Don Ameche  performer         Person
157                         don_cornell                         Don Cornell  performer         Person
158                           don_costa                           Don Costa  performer         Person
159                        donald_novis                        Donald Novis  performer           None
160                        donna_summer                        Donna Summer  performer         Person
161                           doris_day                           Doris Day  performer         Person
162                             dr_john                            Dr. John  performer         Person
163                          duane_eddy                          Duane Eddy  performer         Person
164                        dudley_moore                        Dudley Moore  performer         Person
165                      duke_ellington                      Duke Ellington  performer         Person
166                         duran_duran                         Duran Duran  performer          Group
167                   dusty_springfield                   Dusty Springfield  performer         Person
168                          dylan_gray                          Dylan Gray  performer           None
169                        eddie_murphy                        Eddie Murphy  performer         Person
170                                ejae                                EJAE  performer         Person
171                     ella_fitzgerald                     Ella Fitzgerald  performer         Person
172                       elliott_smith                       Elliott Smith  performer         Person
173                          elton_john                          Elton John  performer         Person
174                       elvis_presley                       Elvis Presley  performer         Person
175                       emery_nichols                       Emery Nichols  performer           None
176                         emily_blunt                         Emily Blunt  performer         Person
177                         emily_brady                         Emily Brady  performer           None
178                              eminem                              Eminem  performer         Person
179                          emma_stone                          Emma Stone  performer         Person
180                                enya                                Enya  performer         Person
181                         eric_carmen                         Eric Carmen  performer         Person
182                        eric_clapton                        Eric Clapton  performer         Person
183                           eric_idle                           Eric Idle  performer         Person
184                       ernie_sabella                       Ernie Sabella  performer         Person
185                        ethel_waters                        Ethel Waters  performer         Person
186                            euel_box                            Euel Box  performer         Person
187                         eydie_gormé                         Eydie Gormé  performer         Person
188                         ezra_koenig                         Ezra Koenig  performer         Person
189                          faith_hill                          Faith Hill  performer         Person
190                       fran_jeffries                       Fran Jeffries  performer         Person
191                    frances_langford                    Frances Langford  performer         Person
192                     frank_churchill                     Frank Churchill  performer         Person
193                            frank_oz                            Frank Oz  performer         Person

### Tabla de Roles

In [44]:
# Credits Table

# PREPARE THE DATA (String to List)
columns_to_melt = ['original_artists', 'song_composers', 'song_lyricists']
df_credits = df_songs_aux[['song_id', 'year', 'song_title'] + columns_to_melt].copy()

# Convert the comma-separated strings into actual Python lists
for col in columns_to_melt:
    df_credits[col] = df_credits[col].astype(str).str.split(r',\s*')

# MELT (Unpivot the columns into rows)
# Take the 3 role columns and collapse them into two new columns: 'role' and 'person'
df_credits = pd.melt(
    df_credits,
    id_vars=['song_id', 'year', 'song_title'], # Columns to keep static
    value_vars=columns_to_melt,                # Columns to collapse
    var_name='role',
    value_name='person'
)

# EXPLODE (List items into separate rows)
df_credits = df_credits.explode('person')

# CLEANUP AND RENAME
# Drop any NaN values or strings that literally say 'nan' or 'None'
df_credits = df_credits.dropna(subset=['person'])
df_credits = df_credits[~df_credits['person'].isin(['nan', 'None', ''])]

# We wrap the Songwriters in a single category
role_mapping = {
    'original_artists': 'artist',
    'song_composers': 'composer', # 'composer',
    'song_lyricists': 'lyricist' # 'lyricist'
}
df_credits['role'] = df_credits['role'].map(role_mapping)

# Sort it so it looks pretty and chronological
df_credits = df_credits.sort_values(['year', 'song_title', 'role']).reset_index(drop=True)

print("=== THE NEW CREDITS TABLE ===")
print(df_credits)

=== THE NEW CREDITS TABLE ===
      song_id  year           song_title      role          person
0      193402  1934        Love In Bloom    artist     Bing Crosby
1      193402  1934        Love In Bloom  composer   Ralph Rainger
2      193402  1934        Love In Bloom  lyricist       Leo Robin
3      193401  1934      The Continental    artist    Fred Astaire
4      193401  1934      The Continental    artist   Ginger Rogers
...       ...   ...                  ...       ...             ...
2037   202504  2025  Sweet Dreams Of Joy  lyricist   Nicholas Pike
2038   202503  2025         Train Dreams    artist  Sierra Ferrell
2039   202503  2025         Train Dreams  composer       Nick Cave
2040   202503  2025         Train Dreams  composer   Bryce Dessner
2041   202503  2025         Train Dreams  lyricist       Nick Cave

[2042 rows x 5 columns]

### Normalización Métricas de Artistas

In [45]:
# Normalize Artists metrics

# 1. Cast string-objects to numeric Int64
artist_metrics = ['artist_playcount', 'artist_listeners']

for col in artist_metrics:
    df_artists_clean[col] = pd.to_numeric(df_artists_clean[col], errors='coerce').astype('Int64')

# 2. Replace any exact 0s with pd.NA (just like we did for songs)
df_artists_clean[artist_metrics] = df_artists_clean[artist_metrics].replace(0, pd.NA)

# Let's take a quick look at the distribution before normalizing
print("--- Raw Artist Metrics ---")
print(df_artists_clean[artist_metrics].describe())


# 3. Apply Percentile and Logarithmic Normalization
for col in artist_metrics:
    # A. Percentile to 0-100 Scale
    df_artists_clean[f'{col}_percentile'] = (
        df_artists_clean[col].rank(pct=True) * 100
    ).round(2)
    
    # B. Logarithmic to 0-100 Scale (Min-Max)
    # We drop NAs specifically for the log calculation to avoid warnings,
    # but Pandas maps the results back to the correct rows automatically.
    log_vals = np.log10(df_artists_clean[col].dropna().astype(float))
    log_min = log_vals.min()
    log_max = log_vals.max()
    
    df_artists_clean[f'{col}_normalized'] = (
        ((np.log10(df_artists_clean[col].astype(float)) - log_min) / (log_max - log_min)) * 100
    ).round(2)

print("\n--- Normalized Artist Metrics Preview ---")
cols_to_view = ['artist_name', 'artist_listeners', 'artist_listeners_normalized', 'artist_playcount_normalized']
print(df_artists_clean[cols_to_view].head(10).to_string())

--- Raw Artist Metrics ---
       artist_playcount  artist_listeners
count             591.0             591.0
mean    42854795.751269     933062.235195
std    152416016.766594    1433803.947009
min                 1.0               1.0
25%            166593.0           25600.5
50%           2255750.0          287069.0
75%          17693447.0         1203446.0
max        1622785028.0         8436184.0

--- Normalized Artist Metrics Preview ---
         artist_name  artist_listeners  artist_listeners_normalized  artist_playcount_normalized
0       A. R. Rahman            689682                        84.30                        78.80
1            Aaliyah           2060186                        91.16                        82.89
2  Abraham Alexander             30076                        64.66                        55.11
3       Abraham Ivan              <NA>                          NaN                          NaN
4        Adam Levine            360555                        80.23                        71.17
5              Adele           5713292                        97.56                        92.41
6     Adrian Quesada             97044                        72.00                        63.09
7          Aerosmith           4795686                        96.46                        88.21
8               A-ha           3479473                        94.45                        84.48
9         Aimee Mann           1019945                        86.75                        79.80

In [46]:
# ---------------------------------------------------------
# 1. Normalizing Artist Equivalent Album Sales (EAS)
# ---------------------------------------------------------
col_artist_eas = 'cm_artist_eas'

# Fill missing artist sales with 0
artist_eas_filled = df_artists_clean[col_artist_eas].fillna(0).astype(float)

# Percentile (Updated with method='min')
df_artists_clean[f'{col_artist_eas}_percentile'] = (
    artist_eas_filled.rank(pct=True, method='min') * 100
).round(2)

# Logarithmic Min-Max (with Log Shift +1)
log_vals_artist_eas = np.log10(artist_eas_filled + 1)
log_min_artist_eas = log_vals_artist_eas.min()
log_max_artist_eas = log_vals_artist_eas.max()

df_artists_clean[f'{col_artist_eas}_normalized'] = (
    ((log_vals_artist_eas - log_min_artist_eas) / (log_max_artist_eas - log_min_artist_eas)) * 100
).round(2)

# ---------------------------------------------------------
# 2. Normalizing the Artist Ranking Column
# ---------------------------------------------------------
col_artist_rank = 'cm_artist_ranking'

# Find the worst (highest number) rank on the chart
worst_artist_rank = df_artists_clean[col_artist_rank].max()

# Fill unranked artists with worst_rank + 1
artist_rank_filled = df_artists_clean[col_artist_rank].fillna(worst_artist_rank + 1).astype(float)

# A. Inverted Percentile (Updated with method='min')
df_artists_clean[f'{col_artist_rank}_percentile'] = (
    artist_rank_filled.rank(pct=True, ascending=False, method='min') * 100
).round(2)

# B. Inverted Logarithmic Min-Max
log_vals_artist_rank = np.log10(artist_rank_filled)
log_min_artist_rank = log_vals_artist_rank.min()
log_max_artist_rank = log_vals_artist_rank.max()

df_artists_clean[f'{col_artist_rank}_normalized'] = (
    100 - (((log_vals_artist_rank - log_min_artist_rank) / (log_max_artist_rank - log_min_artist_rank)) * 100)
).round(2)

# View the results
cols_to_view = ['artist_name', # 'artist_listeners', 
                'cm_artist_eas_percentile', 'cm_artist_eas_normalized',
                'cm_artist_ranking_percentile', 'cm_artist_ranking_normalized']
print(df_artists_clean[cols_to_view].head(10).to_string())


# Drop Columns

# 1. Drop the logarithmic ranking columns from the Songs table
songs_cols_to_drop = ['am_ranking_normalized', 'cm_ranking_normalized']
df_songs_aux.drop(columns=songs_cols_to_drop, inplace=True, errors='ignore')

# 2. Drop the logarithmic ranking column from the Artists table
artists_cols_to_drop = ['cm_artist_ranking_normalized']
df_artists_clean.drop(columns=artists_cols_to_drop, inplace=True, errors='ignore')

# Let's verify what remains for our ranking columns
print()
print("--- Songs Table Rankings ---")
print([col for col in df_songs_aux.columns if 'ranking' in col])

print("\n--- Artists Table Rankings ---")
print([col for col in df_artists_clean.columns if 'ranking' in col])

         artist_name  cm_artist_eas_percentile  cm_artist_eas_normalized  cm_artist_ranking_percentile  cm_artist_ranking_normalized
0       A. R. Rahman                     85.71                     86.02                         85.71                         10.65
1            Aaliyah                     85.22                     83.67                         85.22                          6.46
2  Abraham Alexander                      0.17                      0.00                          0.17                          0.00
3       Abraham Ivan                      0.17                      0.00                          0.17                          0.00
4        Adam Levine                      0.17                      0.00                          0.17                          0.00
5              Adele                     95.02                     92.77                         95.02                         38.99
6     Adrian Quesada                      0.17                      0.00                          0.17                          0.00
7          Aerosmith                     96.35                     93.36                         96.35                         42.93
8               A-ha                     86.71                     87.10                         86.71                         13.41
9         Aimee Mann                      0.17                      0.00                          0.17                          0.00

--- Songs Table Rankings ---
['am_ranking', 'cm_ranking', 'am_ranking_percentile', 'cm_ranking_percentile']

--- Artists Table Rankings ---
['cm_artist_ranking', 'cm_artist_ranking_percentile']

### Columna Número de Autores

In [54]:
# display(df_songs_aux[['song_composers', 'song_lyricists']].head())

def count_unique_writers(row):
    # 1. Grab the strings, treating NaNs/nulls as empty strings
    composers = str(row['song_composers']) if pd.notna(row['song_composers']) else ""
    lyricists = str(row['song_lyricists']) if pd.notna(row['song_lyricists']) else ""
    
    # 2. Split by comma, strip whitespace, and ignore empty values
    comp_list = [name.strip() for name in composers.split(',') if name.strip()]
    lyric_list = [name.strip() for name in lyricists.split(',') if name.strip()]
    
    # 3. Combine both lists to a set to automatically remove duplicates
    unique_writers = set(comp_list + lyric_list)
    
    # 4. Total count
    return len(unique_writers)

# Apply the function row by row and save it to the new column
df_songs_aux['num_ind_songwriters'] = df_songs_aux.apply(count_unique_writers, axis=1)

# Display a quick sample to verify it worked (e.g., showing songs with the most writers)
print(df_songs_aux[['song_title', 'song_composers', 'song_lyricists', 'num_ind_songwriters']].sort_values(by='num_ind_songwriters', ascending=False).head().to_string())

               song_title                                                                                                  song_composers                                                                                                  song_lyricists  num_ind_songwriters
390  Accidentally In Love                     Adam Duritz, Charles Gillingham, Jim Bogios, David Immergluck, Matthew Malley, David Bryson                                                                                     Adam Duritz, Daniel Vickrey                    7
492                Golden                    EJAE, Mark Sonnenblick, Joong Gyu Kwak, Yu Han Lee, Hee Dong Nam, Jeong Hoon Seo, Teddy Park                    EJAE, Mark Sonnenblick, Joong Gyu Kwak, Yu Han Lee, Hee Dong Nam, Jeong Hoon Seo, Teddy Park                    7
445         See You Again  Charlie Puth, Andrew Cedar, Cameron Thomaz, Dann Hume, Joshua Karl Simon Hardy, Justin Franks, Phoebe Cockburn  Charlie Puth, Andrew Cedar, Cameron Thomaz, Dann Hume, Joshua Karl Simon Hardy, Justin Franks, Phoebe Cockburn                    7
461             Sunflower                                         Swae Lee, Louis Bell, Post Malone, Billy Walsh, Carter Lang, Carl Rosen                                         Swae Lee, Louis Bell, Post Malone, Billy Walsh, Carter Lang, Carl Rosen                    6
279      A View To A Kill                                                Simon Le Bon, Andy Taylor, Roger Taylor, Nick Rhodes, John Barry                                                Simon Le Bon, Andy Taylor, Roger Taylor, Nick Rhodes, John Barry                    5

## MUESTRA DE MEDIDAS

In [47]:
target_song_ids = [193502, 194401, 195701, 196602, 197702, 198203, 199701, 200001, 201801, 202101]

# Filter the junction table
df_sample_facts = df_facts_raw[df_facts_raw['song_id'].isin(target_song_ids)]

# Merge with the songs table
df_sample_merged = df_sample_facts.merge(
    df_songs_aux, 
    on='song_id', 
    how='left'
)

# Merge with the films table
df_sample_final = df_sample_merged.merge(
    df_films_aux, 
    on='film_id', 
    how='left'
)

# Metrics and identifiers to peek at
inspection_columns = [
    # 'song_id',
    'year_x',
    'song_title_x',
    'film_title_y',
    'oscar_nominations', 'oscar_wins',    
    'recordings_metric_pct', 
    'streams_obs_max', 'streams_obs_normalized', 
    'lastfm_track_listeners', 'lastfm_track_listeners_normalized',
    'movie_popularity', 'movie_critics_score'
    'budget_adjusted_normalized', 'revenue_adjusted_normalized',
    'movie_awards_normalized'
]

# Extract the columns
df_inspection = df_sample_final.reindex(columns=inspection_columns).dropna(axis=1, how='all')

display(df_inspection)
# print(df_songs_aux.head())

,year_x,song_title_x,film_title_y,oscar_nominations,oscar_wins,recordings_metric_pct,streams_obs_max,lastfm_track_listeners,lastfm_track_listeners_normalized,movie_popularity,revenue_adjusted_normalized,movie_awards_normalized
0,1935,Cheek To Cheek,Top Hat,4,0,97.61,210100000,466316,89.58,76.93,70.89,54.64
1,1944,Swinging On A Star,Going My Way,10,7,85.87,14200000,63142,75.86,69.96,19.30,65.34
2,1957,All The Way,The Joker Is Wild,1,1,91.74,43200000,169744,82.65,71.03,65.52,33.86
3,1966,Alfie,Alfie,5,0,94.02,6000000,40157,72.75,69.94,NaN,60.53
4,1977,Nobody Does It Better,The Spy Who Loved Me,3,0,78.80,67700000,212252,84.18,69.96,88.50,53.34
5,1982,Eye Of The Tiger,Rocky III,1,0,90.65,1833600000,1852253,99.05,69.0,82.62,50.17
6,1997,My Heart Will Go On,Titanic,14,11,94.78,714970000,255451,85.45,79.98,98.97,86.15
7,2000,Things Have Changed,Wonder Boys,3,1,73.48,20790000,142710,81.45,71.96,69.62,70.1
8,2018,Shallow,A Star Is Born,8,1,66.74,3118711700,950176,94.47,75.97,84.63,88.77
9,2021,No Time To Die,No Time to Die,3,1,46.74,797166000,862252,93.80,73.01,88.03,78.44

## EXPORTACIÓN DATASETS

In [55]:
df_songs_clean = df_songs_aux[[
    'song_id', 'song_title', 'year', 'decade',
    'oscar_song_nominee', 'oscar_song_win',
    'grammy_song_nominee', 'grammy_song_win', 'grammy_record_nominee',
    'song_nominations', 'song_wins', 'song_major_awards', 
    'awards_combined', 'awards_combined_percent',
    'grammy_record_win', 'song_composers', 'song_lyricists',
    'original_artists', 'other_artists', # 'streams_original', 'streams_others',
    'spotify_release_date', # 'spotify_duration_ms',
    'spotify_track_title', 'spotify_artists', # 'spotify_album_title',
    'lastfm_track_title', 'lastfm_artist_name', # 'lastfm_album_title',
    'lastfm_track_playcount', 'lastfm_track_listeners',
    'wiki_summary', 'mb_work_title', 'mb_composers', # 'lastfm_tags', 
    'mb_lyricists', 'mb_total_recordings', 'mb_original_recordings_count',
    'mb_cover_recordings_count', 'mb_covers_performers_count', 'mb_covers_performers_top',
    'mb_covers_earliest_year', 'mb_covers_latest_year',
    'mb_covers_earliest_performer', 'mb_covers_latest_performer', 
    'am_ranking', 'am_song_artist', 'am_song_year', 
    'cm_ranking', 'cm_song_artist', 'cm_song_eas', # 'match_key_am', 'match_key_cm', 
    'streams_obs_max', 'streams_percentile', 'streams_normalized', # 'streams_obs_normalized',
    'lastfm_track_playcount_percentile', 'lastfm_track_playcount_normalized', 
    'lastfm_track_listeners_percentile','lastfm_track_listeners_normalized', 
    'cm_song_eas_percentile', 'cm_song_eas_normalized', 
    'am_ranking_percentile', 'cm_ranking_percentile', 
    'mb_original_recordings_pct', 'mb_cover_recordings_pct', 
    'weighted_recordings_raw', 'recordings_metric_pct', 'num_ind_songwriters'
    ]].copy()

df_films_clean = df_films_aux[[
    'film_id', 'film_title', 'year', 'decade', 
    'film_directors', 'film_composers',
    'oscar_nominations', 'oscar_wins', 'oscar_wins_pct',
    'total_nominations', 'total_wins',
    'movie_awards_score', 'movie_awards_normalized', 
    'movie_popularity', 'movie_critics_score',
    'tmdb_official_title', 'tmdb_original_title', 'tmdb_release_date', 'tmdb_runtime',
    'tmdb_budget', 'tmdb_revenue', 'tmdb_vote_average', 'tmdb_vote_count',
    'tmdb_original_language', 'tmdb_origin_countries', 
    'tmdb_actors', 'tmdb_directors', 'tmdb_composers', 'tmdb_production_companies',
    'tmdb_genres', 'tmdb_tagline', 
    'omdb_title', 'omdb_awards',
    'omdb_imdb_rating', 'omdb_imdb_votes', 'omdb_metascore', 'omdb_rotten_tomatoes', 
    'budget_adjusted', 'revenue_adjusted', 'cpi_multiplier',
    'roi_percent', 'commercial_success_factor',
    'budget_adjusted_percentile', 'budget_adjusted_normalized',
    'revenue_adjusted_percentile', 'revenue_adjusted_normalized',
    'roi_percent_percentile', 'roi_percent_normalized',
    'commercial_success_factor_percentile', 'commercial_success_factor_normalized'
    ]].copy()

df_facts_clean = df_facts_raw.copy()
df_roles_clean = df_credits.copy()

In [56]:
df_songs_clean.to_pickle('data/clean_songs_df.pkl')
df_films_clean.to_pickle('data/clean_films_df.pkl')
df_facts_raw.to_pickle('data/clean_facts_df.pkl')
df_artists_clean.to_pickle('data/clean_artists_df.pkl')
df_roles_clean.to_pickle('data/clean_roles_df.pkl')

print("Data saved successfully!")

Data saved successfully!