# Sprint 10: APIs REST

In [1]:
import pandas as pd
import numpy as np
import requests
import json

In [2]:
resposta = requests.get('https://api.github.com')
print(f"Estat de la connexió: {resposta.status_code}")

Estat de la connexió: 200

## Nivel 1: API de ejemplo

### 1.1-1.2: Obtener datos

In [3]:
url = "https://jsonplaceholder.typicode.com/"

response = requests.get(url + "posts")

if response.ok:
    if response.text:
        posts_data = response.json()
        print(f"Código de la petición: {response.status_code}")
        print(f"Descargados {len(posts_data)} posts:")
        print(posts_data[0])
        for post in posts_data:
            print(f"{post['id']}: {post['title']}")
    else:
        print("Petición OK, pero el servidor no ha devuelto datos.")
else:
    print(f"Error en la petición. Código: {response.status_code}")

Código de la petición: 200
Descargados 100 posts:
{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}
1: sunt aut facere repellat provident occaecati excepturi optio reprehenderit
2: qui est esse
3: ea molestias quasi exercitationem repellat qui ipsa sit aut
4: eum et est occaecati
5: nesciunt quas odio
6: dolorem eum magni eos aperiam quia
7: magnam facilis autem
8: dolorem dolore est ipsam
9: nesciunt iure omnis dolorem tempora et accusantium
10: optio molestias id quia eum
11: et ea vero quia laudantium autem
12: in quibusdam tempore odit est dolorem
13: dolorum ut in voluptas mollitia et saepe quo animi
14: voluptatem eligendi optio
15: eveniet quod temporibus
16: sint suscipit perspiciatis velit dolorum rerum ipsa laboriosam odio
17: fugit voluptas sed molestias voluptatem provident
18: voluptate et itaque vero tempora molestiae
19: adipisci placeat illum aut reiciendis qui
20: doloribus ad provident suscipit at
21: asperiores ea ipsam voluptatibus modi minima quia sint
22: dolor sint quo a velit explicabo quia nam
23: maxime id vitae nihil numquam
24: autem hic labore sunt dolores incidunt
25: rem alias distinctio quo quis
26: est et quae odit qui non
27: quasi id et eos tenetur aut quo autem
28: delectus ullam et corporis nulla voluptas sequi
29: iusto eius quod necessitatibus culpa ea
30: a quo magni similique perferendis
31: ullam ut quidem id aut vel consequuntur
32: doloremque illum aliquid sunt
33: qui explicabo molestiae dolorem
34: magnam ut rerum iure
35: id nihil consequatur molestias animi provident
36: fuga nam accusamus voluptas reiciendis itaque
37: provident vel ut sit ratione est
38: explicabo et eos deleniti nostrum ab id repellendus
39: eos dolorem iste accusantium est eaque quam
40: enim quo cumque
41: non est facere
42: commodi ullam sint et excepturi error explicabo praesentium voluptas
43: eligendi iste nostrum consequuntur adipisci praesentium sit beatae perferendis
44: optio dolor molestias sit
45: ut numquam possimus omnis eius suscipit laudantium iure
46: aut quo modi neque nostrum ducimus
47: quibusdam cumque rem aut deserunt
48: ut voluptatem illum ea doloribus itaque eos
49: laborum non sunt aut ut assumenda perspiciatis voluptas
50: repellendus qui recusandae incidunt voluptates tenetur qui omnis exercitationem
51: soluta aliquam aperiam consequatur illo quis voluptas
52: qui enim et consequuntur quia animi quis voluptate quibusdam
53: ut quo aut ducimus alias
54: sit asperiores ipsam eveniet odio non quia
55: sit vel voluptatem et non libero
56: qui et at rerum necessitatibus
57: sed ab est est
58: voluptatum itaque dolores nisi et quasi
59: qui commodi dolor at maiores et quis id accusantium
60: consequatur placeat omnis quisquam quia reprehenderit fugit veritatis facere
61: voluptatem doloribus consectetur est ut ducimus
62: beatae enim quia vel
63: voluptas blanditiis repellendus animi ducimus error sapiente et suscipit
64: et fugit quas eum in in aperiam quod
65: consequatur id enim sunt et et
66: repudiandae ea animi iusto
67: aliquid eos sed fuga est maxime repellendus
68: odio quis facere architecto reiciendis optio
69: fugiat quod pariatur odit minima
70: voluptatem laborum magni
71: et iusto veniam et illum aut fuga
72: sint hic doloribus consequatur eos non id
73: consequuntur deleniti eos quia temporibus ab aliquid at
74: enim unde ratione doloribus quas enim ut sit sapiente
75: dignissimos eum dolor ut enim et delectus in
76: doloremque officiis ad et non perferendis
77: necessitatibus quasi exercitationem odio
78: quam voluptatibus rerum veritatis
79: pariatur consequatur quia magnam autem omnis non amet
80: labore in ex et explicabo corporis aut quas
81: tempora rem veritatis voluptas quo dolores vero
82: laudantium voluptate suscipit sunt enim enim
83: odit et voluptates doloribus alias odio et
84: optio ipsam molestias necessitatibus occaecati facilis veritatis dolores aut
85: dolore veritatis porro provident adipisci blanditiis et sunt
86: placeat quia et porro iste
87: nostrum quis quasi placeat
88: sapiente omnis fugit eos
89: sint soluta et vel magnam aut ut sed qui
90: ad iusto omnis odit dolor voluptatibus
91: aut amet sed
92: ratione ex tenetur perferendis
93: beatae soluta recusandae
94: qui qui voluptates illo iste minima
95: id minus libero illum nam ad officiis
96: quaerat velit veniam amet cupiditate aut numquam ut sequi
97: quas fugiat ut perspiciatis vero provident
98: laboriosam dolor voluptates
99: temporibus sit alias delectus eligendi possimus magni
100: at nam consequatur ea labore ea harum

In [ ]:
def print_response_items(api_response):
  if api_response.ok:
    if api_response.text:
        data = api_response.json()
        print(f"Código de la petición: {api_response.status_code}")
        print(f"Descargados {len(data)} items:")
        print(data[0])
        for dicc in data:
          items = list(dicc.items())
          if len(items) >= 3:
            # items[0] és la primera tupla (ex: ('id', 1))
            # items[0][0] és la clau, parelles[0][1] és el valor
            print(f"{items[0][1]}: {items[1][1]} ({items[2][1]})")
    else:
        print("Petición OK, pero el servidor no ha devuelto datos.")

  else:
      print(f"Error en la petición. Código: {api_response.status_code}")
      print(f"Detalles: {api_response.text}")

In [ ]:
response = requests.get(url + "users")
print_response_items(response)

Código de la petición: 200
Descargados 10 items:
{'id': 1, 'name': 'Leanne Graham', 'username': 'Bret', 'email': 'Sincere@april.biz', 'address': {'street': 'Kulas Light', 'suite': 'Apt. 556', 'city': 'Gwenborough', 'zipcode': '92998-3874', 'geo': {'lat': '-37.3159', 'lng': '81.1496'}}, 'phone': '1-770-736-8031 x56442', 'website': 'hildegard.org', 'company': {'name': 'Romaguera-Crona', 'catchPhrase': 'Multi-layered client-server neural-net', 'bs': 'harness real-time e-markets'}}
1: Leanne Graham (Bret)
2: Ervin Howell (Antonette)
3: Clementine Bauch (Samantha)
4: Patricia Lebsack (Karianne)
5: Chelsey Dietrich (Kamren)
6: Mrs. Dennis Schulist (Leopoldo_Corkery)
7: Kurtis Weissnat (Elwyn.Skiles)
8: Nicholas Runolfsdottir V (Maxime_Nienow)
9: Glenna Reichert (Delphine)
10: Clementina DuBuque (Moriah.Stanton)

In [ ]:
response = requests.get(url + "todos")
print_response_items(response)

Código de la petición: 200
Descargados 200 items:
{'userId': 1, 'id': 1, 'title': 'delectus aut autem', 'completed': False}
1: 1 (delectus aut autem)
1: 2 (quis ut nam facilis et officia qui)
1: 3 (fugiat veniam minus)
1: 4 (et porro tempora)
1: 5 (laboriosam mollitia et enim quasi adipisci quia provident illum)
1: 6 (qui ullam ratione quibusdam voluptatem quia omnis)
1: 7 (illo expedita consequatur quia in)
1: 8 (quo adipisci enim quam ut ab)
1: 9 (molestiae perspiciatis ipsa)
1: 10 (illo est ratione doloremque quia maiores aut)
1: 11 (vero rerum temporibus dolor)
1: 12 (ipsa repellendus fugit nisi)
1: 13 (et doloremque nulla)
1: 14 (repellendus sunt dolores architecto voluptatum)
1: 15 (ab voluptatum amet voluptas)
1: 16 (accusamus eos facilis sint et aut voluptatem)
1: 17 (quo laboriosam deleniti aut qui)
1: 18 (dolorum est consequatur ea mollitia in culpa)
1: 19 (molestiae ipsa aut voluptatibus pariatur dolor nihil)
1: 20 (ullam nobis libero sapiente ad optio sint)
2: 21 (suscipit repellat esse quibusdam voluptatem incidunt)
2: 22 (distinctio vitae autem nihil ut molestias quo)
2: 23 (et itaque necessitatibus maxime molestiae qui quas velit)
2: 24 (adipisci non ad dicta qui amet quaerat doloribus ea)
2: 25 (voluptas quo tenetur perspiciatis explicabo natus)
2: 26 (aliquam aut quasi)
2: 27 (veritatis pariatur delectus)
2: 28 (nesciunt totam sit blanditiis sit)
2: 29 (laborum aut in quam)
2: 30 (nemo perspiciatis repellat ut dolor libero commodi blanditiis omnis)
2: 31 (repudiandae totam in est sint facere fuga)
2: 32 (earum doloribus ea doloremque quis)
2: 33 (sint sit aut vero)
2: 34 (porro aut necessitatibus eaque distinctio)
2: 35 (repellendus veritatis molestias dicta incidunt)
2: 36 (excepturi deleniti adipisci voluptatem et neque optio illum ad)
2: 37 (sunt cum tempora)
2: 38 (totam quia non)
2: 39 (doloremque quibusdam asperiores libero corrupti illum qui omnis)
2: 40 (totam atque quo nesciunt)
3: 41 (aliquid amet impedit consequatur aspernatur placeat eaque fugiat suscipit)
3: 42 (rerum perferendis error quia ut eveniet)
3: 43 (tempore ut sint quis recusandae)
3: 44 (cum debitis quis accusamus doloremque ipsa natus sapiente omnis)
3: 45 (velit soluta adipisci molestias reiciendis harum)
3: 46 (vel voluptatem repellat nihil placeat corporis)
3: 47 (nam qui rerum fugiat accusamus)
3: 48 (sit reprehenderit omnis quia)
3: 49 (ut necessitatibus aut maiores debitis officia blanditiis velit et)
3: 50 (cupiditate necessitatibus ullam aut quis dolor voluptate)
3: 51 (distinctio exercitationem ab doloribus)
3: 52 (nesciunt dolorum quis recusandae ad pariatur ratione)
3: 53 (qui labore est occaecati recusandae aliquid quam)
3: 54 (quis et est ut voluptate quam dolor)
3: 55 (voluptatum omnis minima qui occaecati provident nulla voluptatem ratione)
3: 56 (deleniti ea temporibus enim)
3: 57 (pariatur et magnam ea doloribus similique voluptatem rerum quia)
3: 58 (est dicta totam qui explicabo doloribus qui dignissimos)
3: 59 (perspiciatis velit id laborum placeat iusto et aliquam odio)
3: 60 (et sequi qui architecto ut adipisci)
4: 61 (odit optio omnis qui sunt)
4: 62 (et placeat et tempore aspernatur sint numquam)
4: 63 (doloremque aut dolores quidem fuga qui nulla)
4: 64 (voluptas consequatur qui ut quia magnam nemo esse)
4: 65 (fugiat pariatur ratione ut asperiores necessitatibus magni)
4: 66 (rerum eum molestias autem voluptatum sit optio)
4: 67 (quia voluptatibus voluptatem quos similique maiores repellat)
4: 68 (aut id perspiciatis voluptatem iusto)
4: 69 (doloribus sint dolorum ab adipisci itaque dignissimos aliquam suscipit)
4: 70 (ut sequi accusantium et mollitia delectus sunt)
4: 71 (aut velit saepe ullam)
4: 72 (praesentium facilis facere quis harum voluptatibus voluptatem eum)
4: 73 (sint amet quia totam corporis qui exercitationem commodi)
4: 74 (expedita tempore nobis eveniet laborum maiores)
4: 75 (occaecati adipisci est possimus totam)
4: 76 (sequi dolorem sed)
4: 77 (maiores aut nesciunt delectus exercitationem vel assumenda eligendi at)
4: 78 (reiciendis est magnam amet nemo iste recusandae impedit quaerat)
4: 79 (eum ipsa maxime ut)
4: 80 (tempore molestias dolores rerum sequi voluptates ipsum consequatur)
5: 81 (suscipit qui totam)
5: 82 (voluptates eum voluptas et dicta)
5: 83 (quidem at rerum quis ex aut sit quam)
5: 84 (sunt veritatis ut voluptate)
5: 85 (et quia ad iste a)
5: 86 (incidunt ut saepe autem)
5: 87 (laudantium quae eligendi consequatur quia et vero autem)
5: 88 (vitae aut excepturi laboriosam sint aliquam et et accusantium)
5: 89 (sequi ut omnis et)
5: 90 (molestiae nisi accusantium tenetur dolorem et)
5: 91 (nulla quis consequatur saepe qui id expedita)
5: 92 (in omnis laboriosam)
5: 93 (odio iure consequatur molestiae quibusdam necessitatibus quia sint)
5: 94 (facilis modi saepe mollitia)
5: 95 (vel nihil et molestiae iusto assumenda nemo quo ut)
5: 96 (nobis suscipit ducimus enim asperiores voluptas)
5: 97 (dolorum laboriosam eos qui iure aliquam)
5: 98 (debitis accusantium ut quo facilis nihil quis sapiente necessitatibus)
5: 99 (neque voluptates ratione)
5: 100 (excepturi a et neque qui expedita vel voluptate)
6: 101 (explicabo enim cumque porro aperiam occaecati minima)
6: 102 (sed ab consequatur)
6: 103 (non sunt delectus illo nulla tenetur enim omnis)
6: 104 (excepturi non laudantium quo)
6: 105 (totam quia dolorem et illum repellat voluptas optio)
6: 106 (ad illo quis voluptatem temporibus)
6: 107 (praesentium facilis omnis laudantium fugit ad iusto nihil nesciunt)
6: 108 (a eos eaque nihil et exercitationem incidunt delectus)
6: 109 (autem temporibus harum quisquam in culpa)
6: 110 (aut aut ea corporis)
6: 111 (magni accusantium labore et id quis provident)
6: 112 (consectetur impedit quisquam qui deserunt non rerum consequuntur eius)
6: 113 (quia atque aliquam sunt impedit voluptatum rerum assumenda nisi)
6: 114 (cupiditate quos possimus corporis quisquam exercitationem beatae)
6: 115 (sed et ea eum)
6: 116 (ipsa dolores vel facilis ut)
6: 117 (sequi quae est et qui qui eveniet asperiores)
6: 118 (quia modi consequatur vero fugiat)
6: 119 (corporis ducimus ea perspiciatis iste)
6: 120 (dolorem laboriosam vel voluptas et aliquam quasi)
7: 121 (inventore aut nihil minima laudantium hic qui omnis)
7: 122 (provident aut nobis culpa)
7: 123 (esse et quis iste est earum aut impedit)
7: 124 (qui consectetur id)
7: 125 (aut quasi autem iste tempore illum possimus)
7: 126 (ut asperiores perspiciatis veniam ipsum rerum saepe)
7: 127 (voluptatem libero consectetur rerum ut)
7: 128 (eius omnis est qui voluptatem autem)
7: 129 (rerum culpa quis harum)
7: 130 (nulla aliquid eveniet harum laborum libero alias ut unde)
7: 131 (qui ea incidunt quis)
7: 132 (qui molestiae voluptatibus velit iure harum quisquam)
7: 133 (et labore eos enim rerum consequatur sunt)
7: 134 (molestiae doloribus et laborum quod ea)
7: 135 (facere ipsa nam eum voluptates reiciendis vero qui)
7: 136 (asperiores illo tempora fuga sed ut quasi adipisci)
7: 137 (qui sit non)
7: 138 (placeat minima consequatur rem qui ut)
7: 139 (consequatur doloribus id possimus voluptas a voluptatem)
7: 140 (aut consectetur in blanditiis deserunt quia sed laboriosam)
8: 141 (explicabo consectetur debitis voluptates quas quae culpa rerum non)
8: 142 (maiores accusantium architecto necessitatibus reiciendis ea aut)
8: 143 (eum non recusandae cupiditate animi)
8: 144 (ut eum exercitationem sint)
8: 145 (beatae qui ullam incidunt voluptatem non nisi aliquam)
8: 146 (molestiae suscipit ratione nihil odio libero impedit vero totam)
8: 147 (eum itaque quod reprehenderit et facilis dolor autem ut)
8: 148 (esse quas et quo quasi exercitationem)
8: 149 (animi voluptas quod perferendis est)
8: 150 (eos amet tempore laudantium fugit a)
8: 151 (accusamus adipisci dicta qui quo ea explicabo sed vero)
8: 152 (odit eligendi recusandae doloremque cumque non)
8: 153 (ea aperiam consequatur qui repellat eos)
8: 154 (rerum non ex sapiente)
8: 155 (voluptatem nobis consequatur et assumenda magnam)
8: 156 (nam quia quia nulla repellat assumenda quibusdam sit nobis)
8: 157 (dolorem veniam quisquam deserunt repellendus)
8: 158 (debitis vitae delectus et harum accusamus aut deleniti a)
8: 159 (debitis adipisci quibusdam aliquam sed dolore ea praesentium nobis)
8: 160 (et praesentium aliquam est)
9: 161 (ex hic consequuntur earum omnis alias ut occaecati culpa)
9: 162 (omnis laboriosam molestias animi sunt dolore)
9: 163 (natus corrupti maxime laudantium et voluptatem laboriosam odit)
9: 164 (reprehenderit quos aut aut consequatur est sed)
9: 165 (fugiat perferendis sed aut quidem)
9: 166 (quos quo possimus suscipit minima ut)
9: 167 (et quis minus quo a asperiores molestiae)
9: 168 (recusandae quia qui sunt libero)
9: 169 (ea odio perferendis officiis)
9: 170 (quisquam aliquam quia doloribus aut)
9: 171 (fugiat aut voluptatibus corrupti deleniti velit iste odio)
9: 172 (et provident amet rerum consectetur et voluptatum)
9: 173 (harum ad aperiam quis)
9: 174 (similique aut quo)
9: 175 (laudantium eius officia perferendis provident perspiciatis asperiores)
9: 176 (magni soluta corrupti ut maiores rem quidem)
9: 177 (et placeat temporibus voluptas est tempora quos quibusdam)
9: 178 (nesciunt itaque commodi tempore)
9: 179 (omnis consequuntur cupiditate impedit itaque ipsam quo)
9: 180 (debitis nisi et dolorem repellat et)
10: 181 (ut cupiditate sequi aliquam fuga maiores)
10: 182 (inventore saepe cumque et aut illum enim)
10: 183 (omnis nulla eum aliquam distinctio)
10: 184 (molestias modi perferendis perspiciatis)
10: 185 (voluptates dignissimos sed doloribus animi quaerat aut)
10: 186 (explicabo odio est et)
10: 187 (consequuntur animi possimus)
10: 188 (vel non beatae est)
10: 189 (culpa eius et voluptatem et)
10: 190 (accusamus sint iusto et voluptatem exercitationem)
10: 191 (temporibus atque distinctio omnis eius impedit tempore molestias pariatur)
10: 192 (ut quas possimus exercitationem sint voluptates)
10: 193 (rerum debitis voluptatem qui eveniet tempora distinctio a)
10: 194 (sed ut vero sit molestiae)
10: 195 (rerum ex veniam mollitia voluptatibus pariatur)
10: 196 (consequuntur aut ut fugit similique)
10: 197 (dignissimos quo nobis earum saepe)
10: 198 (quis eius est sint explicabo)
10: 199 (numquam repellendus a magnam)
10: 200 (ipsam aperiam voluptates qui)

### 1.3: Petición con Error

In [ ]:
response = requests.get(url + "wtf")
print_response_items(response)

Error en la petición. Código: 404
Detalles: {}

### 1.4: Petición POST

In [ ]:
def print_response_check_details(api_response):
  print(f"Código de estado de la petición: {api_response.status_code} - {api_response.reason}\n")

  if api_response.ok:
      print("La petición se ha ejecutado con éxito.\nEl servidor ha respondido con estos datos:")
      datos_json = api_response.json()
      print(datos_json)
      print(f"\nComprobación ID respuesta: {datos_json.get('id')}")
  else:
      print("Error en crear la publicación.")
      print(f"Detalles: {api_response.text}")

In [ ]:
url = "https://jsonplaceholder.typicode.com/posts"

mi_post = {
    "title": "Learning to do POSTs with Python",
    "body": "Very cool. Connecting to APIs like a pro.",
    "userId": 1  # Usuari del 1 al 10
}

response = requests.post(url, json=mi_post)
print_response_check_details(response)

Código de estado de la petición: 201 - Created

La petición se ha ejecutado con éxito.
El servidor ha respondido con estos datos:
{'title': 'Learning to do POSTs with Python', 'body': 'Very cool. Connecting to APIs like a pro.', 'userId': 1, 'id': 101}

Comprobación ID respuesta: 101

### 1.5: Petición PATCH

In [ ]:
url = "https://jsonplaceholder.typicode.com/posts/1"

updates = {
    "title": "Updated title with PATCH in Python"
}

response = requests.patch(url, json=updates)
print_response_check_details(response)

Código de estado de la petición: 200 - OK

La petición se ha ejecutado con éxito.
El servidor ha respondido con estos datos:
{'userId': 1, 'id': 1, 'title': 'Updated title with PATCH in Python', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

Comprobación ID respuesta: 1

### 1.6: Petición DELETE

In [ ]:
url = "https://jsonplaceholder.typicode.com/posts/1"

response = requests.delete(url)
print_response_check_details(response)

Código de estado de la petición: 200 - OK

La petición se ha ejecutado con éxito.
El servidor ha respondido con estos datos:
{}

Comprobación ID respuesta: None

## Nivel 2: API pública real

### 2.1: Exploración API

In [ ]:
# Crypto Currency
# http://www.coingecko.com/api

url = "https://api.coingecko.com/api/v3/ping"
response = requests.get(url)

if response.ok:
    if response.text:
        data = response.json()
        print(data)

{'gecko_says': '(V3) To the Moon!'}

### 2.2: Documentación

ENDPOINTS:

- /coins/{id} — Display all the coin data including name, price, market related data, website, explorers, etc.
- /simple/price — Display data such as latest coin price, market cap and 24hr trading volume.

QUERY PARAMETERS

https://docs.coingecko.com/reference/simple-price

- vs_currencies: string. default: usd. target currency of coins, comma-separated if querying more than 1 currency. *refers to /simple/supported_vs_currencies.

- ids: string. default: Bitcoin. coins' IDs, comma-separated if querying more than 1 coin. *refers to /coins/list.

- names: string. default: Bitcoin. coins' names, comma-separated if querying more than 1 coin.

- symbols: string. default: btc. coins' symbols, comma-separated if querying more than 1 coin.

- include_tokens: enum<string>. for symbols lookups, specify all to include all matching tokens. Default top returns top-ranked tokens (by market cap or volume). Available options: top, all

- include_market_cap: boolean. include market capitalization, default: false

- include_24hr_vol: boolean. include 24hr volume, default: false

- include_24hr_change: boolean. include 24hr change percentage, default: false

- include_last_updated_at: boolean. include last updated price time in UNIX, default: false

- precision: enum<string>. decimal place for currency price value

### 2.3: Petición GET

In [ ]:
url = "https://api.coingecko.com/api/v3/simple/price?vs_currencies=usd&ids=bitcoin&names=Bitcoin&symbols=btc"
# headers = {"x-cg-pro-api-key": "<api-key>"}

response = requests.get(url)
print(response.text)

{"bitcoin":{"usd":63806}}

In [ ]:
url_btc = "https://api.coingecko.com/api/v3/coins/bitcoin"
response = requests.get(url_btc)
btc_data = response.json()

print(f"Símbolo: {btc_data.get('symbol')}")
print(f"Nombre: {btc_data.get('name')}")
print(f"Precio actual en USD: {btc_data['market_data']['current_price']['usd']}")

Símbolo: btc
Nombre: Bitcoin
Precio actual en USD: 63764

### 2.4: Obtener Dataframe

In [4]:
pd.options.display.float_format = '{:.2f}'.format

url = "https://api.coingecko.com/api/v3/simple/price"

parametros = {
    "ids": "bitcoin,ethereum,solana,cardano",
    "vs_currencies": "eur",
    "include_market_cap": "true",
    "include_24hr_change": "true"
}

response = requests.get(url, params=parametros)
df_cripto = pd.DataFrame()

if response.ok:
  dades = response.json()
  df_cripto = pd.DataFrame.from_dict(dades, orient='index') # orient='index' -> cada moneda en una fila
  df_cripto.index.name = 'moneda'
  df_cripto.round(2)
else:
  print(f"Error {resposta.status_code}: {resposta.text}")

print(df_cripto)

              eur   eur_market_cap  eur_24h_change
moneda
bitcoin  56623.00 1134415979058.71            1.66
cardano      0.16    5802351112.94            5.55
ethereum  1482.04  178781695910.96            2.28
solana      61.57   35668137386.13            4.37

## Nivel 3: API Open Data Bcn

### 3.1: Dataset

Buscar algun dataset mediante package_search y package_show

https://opendata-ajuntament.barcelona.cat/ca/desenvolupadors

https://opendata-ajuntament.barcelona.cat/data/api/action/package_search

https://opendata-ajuntament.barcelona.cat/data/ca/dataset/dades-sales-musica-viu-agrup-dimensions

https://opendata-ajuntament.barcelona.cat/data/ca/dataset/culturailleure-cinemesteatresauditoris

### 3.2: CSV o JSON

Buscar recursos disponibles en CSV o JSON

In [19]:
url_search = "https://opendata-ajuntament.barcelona.cat/data/api/action/package_search"
params_search = {"q": "concerts"}

response = requests.get(url_search, params=params_search)

if response.ok:
    data_json = response.json()
    results = data_json["result"]["results"]
    print(f"Se han encontrado {len(results)} datasets relacionados.\n")

    resource_ids = []
    nombre_datasets = []

    for dataset in results:
        for recurso in dataset["resources"]:
            if recurso.get("format", "").upper() == "CSV" and recurso.get("datastore_active") == True:
                resource_ids.append(recurso["id"])
                nombre_datasets.append(dataset["title"])

    for i in range(min(len(resource_ids), 10)):
        nombre_dataset = nombre_datasets[i]
        resource_id = resource_ids[i]

        print(f" - Dataset {i}: {nombre_dataset}")
        print(f" - Resource ID: {resource_id}")

        # Inspeccionar dataset
        print("\nConectando a la base de datos...\n")
        url_datastore = "https://opendata-ajuntament.barcelona.cat/data/api/action/datastore_search"

        params_datastore = {
            "resource_id": resource_id,
            "limit": 5
        }

        response_datastore = requests.get(url_datastore, params=params_datastore)

        if response_datastore.ok:
            datos_datastore = response_datastore.json()
            registros = datos_datastore["result"]["records"]
            total_filas = datos_datastore["result"]["total"]

            print(f"INFORMACIÓN DEL DATASET:")
            print(f" -> El dataset contiene {total_filas} registros en total.")

            print("Ejemplo del primer registro:")
            for clave, valor in registros[0].items():
                print(f"> {clave}: {valor}")
            print()
        else:
            print(f"Error en la extracción de datos: {response_datastore.status_code}")

    if len(resource_ids) < 1:
        print("Lo siento. Ninguno de los datasets tiene el DataStore activado con CSV.")

else:
    print(f"Error en la búsqueda: {response.status_code}")

Se han encontrado 3 datasets relacionados.

 - Dataset 0: Large capacity venues in the city of Barcelona
 - Resource ID: 63844549-8455-441c-b2aa-20960a34a378

Conectando a la base de datos...

INFORMACIÓN DEL DATASET:
 -> El dataset contiene 12 registros en total.
Ejemplo del primer registro:
> Notes_Dades:
> Recinte: Estadi Olímpic
> Indicador: Dies de concerts
> Valor: 9
> _id: 1
> Any: 2023

 - Dataset 1: Spaces in the city of Barcelona where cinema, theater and concerts take place
 - Resource ID: 0f706441-b9d8-47c9-9e71-ced453810a72

Conectando a la base de datos...

INFORMACIÓN DEL DATASET:
 -> El dataset contiene 202 registros en total.
Ejemplo del primer registro:
> addresses_roadtype_name:
> addresses_end_street_number: None
> geo_epgs_4326_lon: 2.165560019721226
> values_attribute_name: Tel.
> estimated_dates:
> addresses_road_name: Carrer de la Reina Amàlia
> values_category: Telèfons
> addresses_zip_code: 8001
> secondary_filters_id: 55732068
> values_value: 638330741
> addresses_town: Barcelona
> secondary_filters_name: Teatres
> timetable:
> secondary_filters_tree: 651
> start_date:
> addresses_district_name: Ciutat Vella
> end_date:
> geo_epgs_25831_x: 430224.44939951884
> addresses_start_street_number: 3
> register_id: ﻿99400496646
> institution_id: None
> addresses_main_address: True
> addresses_district_id: 1
> addresses_roadtype_id:
> addresses_type:
> addresses_neighborhood_id: 1
> _id: 1
> name: Ateneu del Raval
> addresses_road_id: 277809
> created: 2017-04-25T16:16:33
> geo_epgs_25831_y: 4581054.3418629095
> institution_name:
> modified: 2026-05-28T12:34:37.078785
> secondary_filters_asia_id: 65103002001000
> secondary_filters_fullpath: Planol BCN >> Cultura i lleure >> Cinemes, teatres, auditoris >> Teatres
> geo_epgs_4326_lat: 41.377985919563486
> values_description:
> values_id: 230142
> addresses_neighborhood_name: el Raval
> values_outstanding: True
> values_attribute_id: 20001

 - Dataset 2: List of culture and leisure spaces and facilities in the city of Barcelona
 - Resource ID: f3721b17-bf9e-4bdd-853c-cb6200e1b442

Conectando a la base de datos...

INFORMACIÓN DEL DATASET:
 -> El dataset contiene 3069 registros en total.
Ejemplo del primer registro:
> addresses_roadtype_name:
> addresses_end_street_number: 48
> geo_epgs_4326_lon: 2.1324759607595776
> values_attribute_name:
> estimated_dates:
> addresses_road_name: Carrer d'Antoni de Capmany
> values_category:
> addresses_zip_code: 8014
> secondary_filters_id: 55735068
> values_value:
> addresses_town: Barcelona
> secondary_filters_name: Àrees de jocs infantils
> timetable:
> secondary_filters_tree: 651
> start_date:
> addresses_district_name: Sants-Montjuïc
> end_date:
> geo_epgs_25831_x: 427451.732
> addresses_start_street_number: 30
> register_id: ﻿99400661329
> institution_id: 99400457299
> addresses_main_address: True
> addresses_district_id: 3
> addresses_roadtype_id:
> addresses_type:
> addresses_neighborhood_id: 18
> _id: 1
> name: Àrea de Joc Infantil
> addresses_road_id: 17706
> created: 2020-12-15T13:12:15
> geo_epgs_25831_y: 4580460.604
> institution_name: Jardins de la Rambla de Sants
> modified: 2025-05-30T12:56:55.869366
> secondary_filters_asia_id: 65103002004000
> secondary_filters_fullpath: Planol BCN >> Cultura i lleure >> Espais infantils >> Àrees de jocs infantils
> geo_epgs_4326_lat: 41.372393143770196
> values_description:
> values_id: None
> addresses_neighborhood_name: Sants
> values_outstanding:
> values_attribute_id: None

### 3.3: Realizar consulta

Con el resource_id del recurso seleccionado, realiza una consulta mediante datastore_search para obtener al menos 100 registros.

In [20]:
url_datastore = "https://opendata-ajuntament.barcelona.cat/data/api/action/datastore_search"

parametros = {
    "resource_id": "0f706441-b9d8-47c9-9e71-ced453810a72",
    "limit": 100
}

respuesta = requests.get(url_datastore, params=parametros)

if respuesta.ok:
    datos_json = respuesta.json()
    registros = datos_json["result"]["records"]
    print(f"Se han descargado {len(registros)} registros mediante datastore_search.\n")

    # Datos del primer registro
    print("Ejemplo del primer registro (Concert):")
    for clave, valor in registros[0].items():
        print(f" - {clave}: {valor}")

else:
    print(f"Error {respuesta.status_code}: {respuesta.text}")

Se han descargado 100 registros mediante datastore_search.

Ejemplo del primer registro (Concert):
 - addresses_roadtype_name:
 - addresses_end_street_number: None
 - geo_epgs_4326_lon: 2.165560019721226
 - values_attribute_name: Tel.
 - estimated_dates:
 - addresses_road_name: Carrer de la Reina Amàlia
 - values_category: Telèfons
 - addresses_zip_code: 8001
 - secondary_filters_id: 55732068
 - values_value: 638330741
 - addresses_town: Barcelona
 - secondary_filters_name: Teatres
 - timetable:
 - secondary_filters_tree: 651
 - start_date:
 - addresses_district_name: Ciutat Vella
 - end_date:
 - geo_epgs_25831_x: 430224.44939951884
 - addresses_start_street_number: 3
 - register_id: ﻿99400496646
 - institution_id: None
 - addresses_main_address: True
 - addresses_district_id: 1
 - addresses_roadtype_id:
 - addresses_type:
 - addresses_neighborhood_id: 1
 - _id: 1
 - name: Ateneu del Raval
 - addresses_road_id: 277809
 - created: 2017-04-25T16:16:33
 - geo_epgs_25831_y: 4581054.3418629095
 - institution_name:
 - modified: 2026-05-28T12:34:37.078785
 - secondary_filters_asia_id: 65103002001000
 - secondary_filters_fullpath: Planol BCN >> Cultura i lleure >> Cinemes, teatres, auditoris >> Teatres
 - geo_epgs_4326_lat: 41.377985919563486
 - values_description:
 - values_id: 230142
 - addresses_neighborhood_name: el Raval
 - values_outstanding: True
 - values_attribute_id: 20001

### 3.4: Convertir a DF

Convertir los resultados obtenidos a un Dataframe.

In [32]:
url_datastore = "https://opendata-ajuntament.barcelona.cat/data/api/action/datastore_search"
resource_id = "0f706441-b9d8-47c9-9e71-ced453810a72"

params_iniciales = {
    "resource_id": resource_id,
    "limit": 1
}

respuesta_inicial = requests.get(url_datastore, params=params_iniciales)

if respuesta_inicial.ok:
    total_registros = respuesta_inicial.json()["result"]["total"]
    print(f"El dataset tiene un total de {total_registros} registros. Iniciando descarga...")

    params_totales = {
        "resource_id": resource_id,
        "limit": total_registros
    }

    respuesta_total = requests.get(url_datastore, params=params_totales)

    if respuesta_total.ok:
        datos_json = respuesta_total.json()
        registros = datos_json["result"]["records"]

        df_descarga = pd.DataFrame(registros)

        print("Carga completada con éxito!\n")
        print(f"Dimensiones del DataFrame: {df_descarga.shape}\nMuestra del DataFrame:\n")
        display(df_descarga.head())

    else:
        print(f"Error en la descarga: {respuesta_total.status_code}")

else:
    print(f"Error en la conexión inicial: {respuesta_inicial.status_code}")

El dataset tiene un total de 202 registros. Iniciando descarga...
Carga completada con éxito!

Dimensiones del DataFrame: (202, 41)
Muestra del DataFrame:

,addresses_roadtype_name,addresses_end_street_number,geo_epgs_4326_lon,values_attribute_name,estimated_dates,addresses_road_name,values_category,addresses_zip_code,secondary_filters_id,values_value,...,institution_name,modified,secondary_filters_asia_id,secondary_filters_fullpath,geo_epgs_4326_lat,values_description,values_id,addresses_neighborhood_name,values_outstanding,values_attribute_id
0,,None,2.165560019721226,Tel.,,Carrer de la Reina Amàlia,Telèfons,8001,55732068,638330741,...,,2026-05-28T12:34:37.078785,65103002001000,"Planol BCN >> Cultura i lleure >> Cinemes, tea...",41.377985919563486,,230142,el Raval,True,20001
1,,None,2.135255026078898,,,C Constitució,,8014,55732068,,...,,2023-11-28T11:33:46.656662,65103002001000,"Planol BCN >> Cultura i lleure >> Cinemes, tea...",41.36983398156041,,None,la Bordeta,,None
2,,None,2.1335788480441584,Tel.,,C Ganduxer,Telèfons,8022,55732068,932123354,...,Centre Educatiu Santa Teresa - Ganduxer,2023-01-20T14:05:01.349165,65103002001000,"Planol BCN >> Cultura i lleure >> Cinemes, tea...",41.399968634043724,,162318,les Tres Torres,True,20001
3,,None,2.151721868976122,Taquilles,,Rambla de Prat,Telèfons,8012,55732069,932172642,...,,2023-06-12T08:35:24.349557,65103002001001,"Planol BCN >> Cultura i lleure >> Cinemes, tea...",41.40139721074222,,160340,la Vila de Gràcia,True,20038
4,,40,2.1823673277242173,Tel.,,Carrer de Flassaders,Telèfons,8003,55732068,93 458 99 94,...,Fundació Joan Brossa,2026-05-11T11:44:59.591524,65103002001000,"Planol BCN >> Cultura i lleure >> Cinemes, tea...",41.385220679624325,,432390,"Sant Pere, Santa Caterina i la Ribera",False,20001

In [34]:
display(df_descarga.info())
display(df_descarga[['name', 'institution_name', 'addresses_road_name', 'addresses_district_name', 'addresses_neighborhood_name', 'addresses_zip_code']])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202 entries, 0 to 201
Data columns (total 41 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   addresses_roadtype_name        202 non-null    object
 1   addresses_end_street_number    19 non-null     object
 2   geo_epgs_4326_lon              202 non-null    object
 3   values_attribute_name          202 non-null    object
 4   estimated_dates                202 non-null    object
 5   addresses_road_name            202 non-null    object
 6   values_category                202 non-null    object
 7   addresses_zip_code             202 non-null    object
 8   secondary_filters_id           202 non-null    object
 9   values_value                   202 non-null    object
 10  addresses_town                 202 non-null    object
 11  secondary_filters_name         202 non-null    object
 12  timetable                      202 non-null    object
 13  secondary_filters_tree         202 non-null    object
 14  start_date                     202 non-null    object
 15  addresses_district_name        202 non-null    object
 16  end_date                       202 non-null    object
 17  geo_epgs_25831_x               202 non-null    object
 18  addresses_start_street_number  202 non-null    object
 19  register_id                    202 non-null    object
 20  institution_id                 104 non-null    object
 21  addresses_main_address         202 non-null    object
 22  addresses_district_id          202 non-null    object
 23  addresses_roadtype_id          202 non-null    object
 24  addresses_type                 202 non-null    object
 25  addresses_neighborhood_id      202 non-null    object
 26  _id                            202 non-null    int64
 27  name                           202 non-null    object
 28  addresses_road_id              202 non-null    object
 29  created                        202 non-null    object
 30  geo_epgs_25831_y               202 non-null    object
 31  institution_name               202 non-null    object
 32  modified                       202 non-null    object
 33  secondary_filters_asia_id      202 non-null    object
 34  secondary_filters_fullpath     202 non-null    object
 35  geo_epgs_4326_lat              202 non-null    object
 36  values_description             202 non-null    object
 37  values_id                      179 non-null    object
 38  addresses_neighborhood_name    202 non-null    object
 39  values_outstanding             202 non-null    object
 40  values_attribute_id            179 non-null    object
dtypes: int64(1), object(40)
memory usage: 64.8+ KB

None

,name,institution_name,addresses_road_name,addresses_district_name,addresses_neighborhood_name,addresses_zip_code
0,Ateneu del Raval,,Carrer de la Reina Amàlia,Ciutat Vella,el Raval,8001
1,Sala Clan Destino Mental,,C Constitució,Sants-Montjuïc,la Bordeta,8014
2,Teatre,Centre Educatiu Santa Teresa - Ganduxer,C Ganduxer,Sarrià-Sant Gervasi,les Tres Torres,8022
3,Mooby Bosque Multicines,,Rambla de Prat,Gràcia,la Vila de Gràcia,8012
4,Centre de les Arts Lliures,Fundació Joan Brossa,Carrer de Flassaders,Ciutat Vella,"Sant Pere, Santa Caterina i la Ribera",8003
...,...,...,...,...,...,...
197,The Comedy Clubhouse *Canvis Nous,,Carrer dels Canvis Nous,Ciutat Vella,"Sant Pere, Santa Caterina i la Ribera",8003
198,Teatre La Fàbrica,,Plaça de Mañé i Flaquer,Sarrià-Sant Gervasi,el Putxet i el Farró,8006
199,L'Àtic22,Tantarantana Teatre,Carrer de les Flors,Ciutat Vella,el Raval,8001
200,Teatre Metamorfosis,,Carrer de Tapioles,Sants-Montjuïc,el Poble-sec,8004
201,Auditori Carme Serrallonga i Calafell,,Plaça de Sarrià,Sarrià-Sant Gervasi,Sarrià,8017

### 3.5: Guardar a CSV

Guardar el dataframe en un fichero CSV.

In [35]:
columnas = ['name', 'institution_name', 'addresses_road_name', 'addresses_district_name', 'addresses_neighborhood_name', 'addresses_zip_code']
df_final = df_descarga[columnas]

df_final.to_csv("venues_bcn.csv", index=False, encoding='utf-8-sig')

print("Fichero 'venues_bcn.csv' guardado correctamente!")

Fichero 'venues_bcn.csv' guardado correctamente!