In [ ]:
import pandas as pd
import numpy as np

## N1.1: Exploración del dataset

A partir de un fichero de Excel, vamos a explorar las características que presentan los datos. Debemos crear el dataframe y responder a las siguientes cuestiones:

- Dimensión del dataset
- Ver muestra de filas
- Tipos de variables por columnas
- Coherencia de los datos
- Detectar duplicados
- Detectar problemas iniciales

```
# This is formatted as code
```

In [ ]:
# Importar el dataset
fichero_empleados = "empleats_enquesta.xlsx"

df_empleados = pd.read_excel(fichero_empleados, sheet_name='sprint10_complex', header=3)
df_empleados

,Unnamed: 0,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
0,0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
1,1,Marc,MuÃ±oz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
2,2,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,TÃ¨cnic IT,4.0,NaN,NaN,NaN,16.7
3,3,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 â‚¬",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
4,4,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 â‚¬",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,1002,Alba,MuÃ±oz,97954019T,Espanya,Bilbao,25.0,10.0,1983.0,D,"1,409 â‚¬",NaN,True,Grup B,Responsable de vendes,0.0,NaN,NaN,NaN,14.7
1003,1003,Claudia,Gil Ferrer,55297384F,Espanya,ValÃ¨ncia,1.0,11.0,1981.0,H,1.789 â‚¬,NaN,True,Grup B,Responsable de vendes,0.0,True,29952.0,9.2,20.3
1004,1004,Oriol,Ferrer,52590001R,Espanya,Zaragoza,15.0,7.0,1973.0,D,786â‚¬,NaN,True,Grup A,Analista,0.0,True,81381.0,6.5,13.9
1005,1005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1006,1006,???,###,XXXX,Narnia,Desconeguda,-99.0,99.0,3000.0,??,molts,NaN,NaN,Z,???,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Dimensión del dataset
print(f"El dataset tiene {df_empleados.shape[0]} filas y {df_empleados.shape[1]} columnas.")

El dataset tiene 1007 filas y 20 columnas.

In [ ]:
# Muestra de filas
df_empleados.head(20)

,Unnamed: 0,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
0,0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
1,1,Marc,MuÃ±oz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
2,2,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,TÃ¨cnic IT,4.0,NaN,NaN,NaN,16.7
3,3,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 â‚¬",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
4,4,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 â‚¬",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1
5,5,Alexia,Puig,25014631B,Espanya,Las Palmas de Gran Canaria,1.0,8.0,1978.0,D,"2,069 â‚¬",NaN,True,Grup B,Cap de projecte,0.0,NaN,NaN,NaN,19.9
6,6,David,GÃ³mez Vila,36998038E,Espanya,Palma,25.0,9.0,1971.0,D,"2,349 â‚¬",NaN,True,Grup B,Cap de projecte,NaN,True,6196.0,10.6,17.8
7,7,Carmen,LÃ³pez,47376585K,Espanya,Barcelona,8.0,9.0,1962.0,H,"2,855 â‚¬",True,NaN,Grup C,Responsable de vendes,4.0,True,20000.0,5.9,15.4
8,540,Nora,Andersen Pedersen,37289414J,Noruega,Stavanger,8.0,3.0,1963.0,D,"1,338 â‚¬",NaN,True,Grup B,Analista junior,0.0,False,NaN,NaN,7.6
9,9,Alba,GarcÃ­a,75181648S,Espanya,Las Palmas de Gran Canaria,32.0,0.0,1940.0,H,"1,450 â‚¬",True,NaN,Grup A,Senior analyst,4.0,False,NaN,NaN,20.1
10,10,Joana,Torres DÃ­az,82772208R,Espanya,Valladolid,24.0,10.0,1961.0,F,982 â‚¬,NaN,True,Grup A,Administratiu,0.0,True,14178.0,7.7,38.0
11,11,Guillem,Vidal,52169044F,Espanya,Zaragoza,22.0,4.0,1974.0,H,"2,419 â‚¬",True,True,Grup B,Cap de projecte,1.0,NaN,NaN,NaN,38.0
12,12,Aina,PÃ©rez,31172421Z,Espanya,Las Palmas de Gran Canaria,10.0,6.0,1973.0,H,"3,672 â‚¬",NaN,True,Grup D,Cap de projecte,NaN,True,10800.0,12.9,22.0
13,13,Emilia,Hoffmann,66851377P,Alemanya,Stuttgart,21.0,2.0,1961.0,D,"1,003 â‚¬",NaN,True,Grup A,Project lead,NaN,True,6931.0,12.2,12.4
14,14,Xavier,Casals,43491314K,Espanya,Alacant,22.0,4.0,1980.0,H,mil vuit-cents,NaN,True,Grup A,Analista junior,0.0,True,38248.0,0.5,19.7
15,15,Carmen,HernÃ¡ndez Serra,36786211Z,Espanya,Tarragona,8.0,8.0,1960.0,H,"1,336 â‚¬",True,NaN,Grup B,Administratiu,3.0,True,65950.0,NaN,NaN
16,16,Sara,HernÃ¡ndez Costa,91363974Q,Espanya,ValÃ¨ncia,14.0,6.0,2004.0,Home,982 â‚¬,NaN,True,Grup A,Analista junior,0.0,NaN,NaN,NaN,15.8
17,375,Sigrid,Olsen,70604045C,Noruega,Bergen,19.0,6.0,1964.0,D,"1,385 â‚¬",True,True,Grup A,Admin.,0.0,True,80000.0,25.0,8.8
18,18,Nil,FernÃ¡ndez Vidal,69345683K,Espanya,Bilbao,15.0,8.0,1978.0,Home,"1,751 â‚¬",NaN,True,Grup B,Senior analyst,NaN,True,64444.0,0.5,16.0
19,19,AdriÃ,Ribera,63640499F,Espanya,Palma,16.0,7.0,2002.0,D,889 euros,NaN,True,Grup A,Analyst,NaN,NaN,NaN,NaN,19.2

In [ ]:
# Tipos de variables
df_empleados.dtypes

Unnamed: 0                      int64
Nom                            object
Cognoms                        object
DNI                            object
País d'origen                  object
Ciutat                         object
Dia de Naixement              float64
Mes de Naixement              float64
Any de Naixement              float64
Gènere                         object
Salari mensual                 object
Fills                          object
No Fills                       object
Grup Professional              object
CÃ rrec                        object
Nombre_fills                  float64
Te_cotxe                       object
Km_anuals                     float64
Consum_mitja_L_100km          float64
Temperatura_mitjana_ciutat    float64
dtype: object

In [ ]:
# Coherencia de los datos
df_empleados.info()

columnas_float = df_empleados.select_dtypes(include=[float]).columns.to_list()
columnas_object = df_empleados.select_dtypes(include=[object]).columns.to_list()
print(f"\nColumnas de tipo float:\n{columnas_float}")
print(f"\nColumnas de tipo object:\n{columnas_object}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1007 entries, 0 to 1006
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  1007 non-null   int64
 1   Nom                         1006 non-null   object
 2   Cognoms                     1006 non-null   object
 3   DNI                         1006 non-null   object
 4   País d'origen               1006 non-null   object
 5   Ciutat                      1006 non-null   object
 6   Dia de Naixement            1006 non-null   float64
 7   Mes de Naixement            1006 non-null   float64
 8   Any de Naixement            1006 non-null   float64
 9   Gènere                      966 non-null    object
 10  Salari mensual              1006 non-null   object
 11  Fills                       419 non-null    object
 12  No Fills                    585 non-null    object
 13  Grup Professional           1005 non-null   object
 14  CÃ rrec                     1005 non-null   object
 15  Nombre_fills                709 non-null    float64
 16  Te_cotxe                    658 non-null    object
 17  Km_anuals                   315 non-null    float64
 18  Consum_mitja_L_100km        261 non-null    float64
 19  Temperatura_mitjana_ciutat  936 non-null    float64
dtypes: float64(7), int64(1), object(12)
memory usage: 157.5+ KB

Columnas de tipo float:
['Dia de Naixement', 'Mes de Naixement', 'Any de Naixement', 'Nombre_fills', 'Km_anuals', 'Consum_mitja_L_100km', 'Temperatura_mitjana_ciutat']

Columnas de tipo object:
['Nom', 'Cognoms', 'DNI', "País d'origen", 'Ciutat', 'Gènere', 'Salari mensual', 'Fills', 'No Fills', 'Grup Professional', 'CÃ\xa0rrec', 'Te_cotxe']

Observando las columnas y el tipo de datos que presenta el dataset, puedo ver de entrada que:

- Hay varias columnas de tipo **float** que deberían ser realmente tipo **int**, como es el caso de *'Nombre_fills'*
- También se representan como float valores que realmente tendrían que ser fechas date, como *'Dia de Naixement'*, *'Mes de Naixement'* i *'Any de Naixement'*
- De las columnas tipo object, hay algunas que deberían representarse como **boolean** (*'Fills', 'No Fills', 'Te_cotxe'*)
- Las tres columnas referentes al número de hijos ('Fills', 'No Fills', 'NOmbre_fills') podrían simplificarse
- También hay la columna *'Salari mensual'* que aparece como texto, pero debería expresarse mejor como **float**, pues se trata de una cantidad monetaria

In [ ]:
# Detectar duplicados
numero_duplicados = df_empleados.duplicated().sum()
print(f"El dataset tiene {numero_duplicados} filas totalmente duplicadas.")

numero_duplicados_dni = df_empleados.duplicated(subset=['DNI']).sum()
print(f"El dataset tiene {numero_duplicados_dni} filas con DNI duplicados.")

# Detectar filas vacías
filas_nulas = df_empleados.isna().all(axis=1).sum()
print(f"El dataset tiene {filas_nulas} filas totalmente vacías.")

El dataset tiene 0 filas totalmente duplicadas.
El dataset tiene 15 filas con DNI duplicados.
El dataset tiene 0 filas totalmente vacías.

In [ ]:
# Detectar problemas:

# Texto con carácteres extraños (problema de encoding)
texto_raro = "1,478 â‚¬"
texto_corregido = texto_raro.encode('cp1252').decode('utf-8')
print(f"Texto con símbolos raros: {texto_raro}\nDebería corregirse como: {texto_corregido}\n")

# Columna 'Unnamed: 0' con índices desordenados
print("Columna 'Unnamed' con índices desordenados:\n")
print(df_empleados[df_empleados['Unnamed: 0'] != df_empleados.index][['Unnamed: 0', 'Nom', 'Cognoms', 'DNI']])
print()
print(f"Valores únicos de la columna 'Unnamed': {df_empleados['Unnamed: 0'].nunique()}")
print(f"Son todos los valores de la columna 'Unnamed' únicos? {df_empleados['Unnamed: 0'].is_unique}")

# Último registro sospechoso
print("\nRegistro con valores sospechosamente incorrectos:\n")
print(df_empleados.iloc[1006, :])

Texto con símbolos raros: 1,478 â‚¬
Debería corregirse como: 1,478 €

Columna 'Unnamed' con índices desordenados:

      Unnamed: 0       Nom               Cognoms        DNI
8            540      Nora     Andersen Pedersen  37289414J
17           375    Sigrid                 Olsen  70604045C
36           464       Ida       Karlsen Eriksen  55283701C
40          1001       Ida       Karlsen Eriksen  55283701C
63           504       Jon     Johnsen Pettersen  42352710Z
82            17      Maja          Berg Johnsen  50308572Q
115          958      Maja               Eriksen  69314812J
124          364    Astrid           Olsen Hagen  54445587H
162           82       Liv                 Hagen  24710878J
283          397      Nora              Lie Moen  70655417L
290          737      Nora             Pettersen  86003182L
316          290       Ole              Johansen  47302753Y
322          589      Thea           Kristiansen  90402724B
364          283     Hilde               Solberg  55056176R
375          452      Thea                   Lie  23933416W
383            8      Lars               Eriksen  35529407V
386          515    Henrik                 Hagen  78113806Y
397          533     Elias                Hansen  18718099Y
405          124       Ole                Larsen  40728728N
407          383       Ole               Johnsen  67429121A
452          162      Erik             Pettersen  81770706L
464          647     Sofie               Johnsen  59943747Z
474          407      Erik                 Hagen  86904329H
481          386      Lars      Andersen Karlsen  15087753F
501          481      Erik                 Bakke  79291785G
504          501      Emil                Hansen  16003970L
515          474     Elias                   Lie  12781968G
533          790      Emil              Pedersen  62627379H
540          711    Astrid             Pettersen  30660064E
589           40      Lars               Johnsen  42775624Q
599          674      Emil                  Moen  14887763Y
647          115    Sigrid                Hansen  23656928V
651          316       Ole                  Berg  65426729X
652          842      Emil           Olsen Hagen  80450969A
674          725      Maja                Nilsen  62978421F
697          652  Kristian                   Lie  15190410S
711           36       Ida                Larsen  46698468J
725          405    Astrid          Hansen Bakke  67325876K
737          322     Elias                 Hagen  81192277J
790          861    Magnus         Nilsen Larsen  23391799B
842          599     Sofie        Eriksen Haugen  54363421F
861          697     Elias     Pettersen Karlsen  48272885X
958           63       Ida  Johansen Kristiansen  41407343V
1001         651    Kasper             Pettersen  62042563B

Valores únicos de la columna 'Unnamed': 1007
Son todos los valores de la columna 'Unnamed' únicos? True

Registro con valores sospechosamente incorrectos:

Unnamed: 0                           1006
Nom                                   ???
Cognoms                               ###
DNI                                  XXXX
País d'origen                      Narnia
Ciutat                        Desconeguda
Dia de Naixement                    -99.0
Mes de Naixement                     99.0
Any de Naixement                   3000.0
Gènere                                 ??
Salari mensual                      molts
Fills                                 NaN
No Fills                              NaN
Grup Professional                       Z
CÃ rrec                               ???
Nombre_fills                          NaN
Te_cotxe                              NaN
Km_anuals                             NaN
Consum_mitja_L_100km                  NaN
Temperatura_mitjana_ciutat            NaN
Name: 1006, dtype: object

Tras hacer esta primera inspección del dataset, se detectan diversos problemas que deberemos abordar posteriormente:

- Tipos incorrectos de variables
- Columna con índices desordenados
- Problemas de enconding provoca texto con caracteres extraños
- No se detectan filas totalmente duplicadas, aunque sí hay duplicados parciales que deberemos analizar
- No hay filas con todos los valores nulos, aunque sí que hay muchos registros con valores nulos en diferentes columnas
- Vemos algún registro con datos claramente no válidos (como el 1006)

## N1.2: Validaciones básicas de los datos

En este ejercicio se deberán tomar decisiones para poder dar como válidos los registros o decidir sobre su eliminación. Concretamente, procederemos a:

- Detectar y eliminar filas vacías y duplicadas
- Corregir problemas de codificación
- Comprobar unicidad de los DNI y eliminar registros no fiables
- Identificar campos claves que no deben contener valores nulos, detectar registros con información insuficiente y eliminar filas completamente irrecuperables

In [ ]:
# En primer lugar, para poder identificar bien las filas
# creo una función que reestablece una columna como índice original
# y ordenamos el dataframe según este índice

def restaurar_index(df=None, nom_columna='Unnamed: 0', nom_index='ID_Original'):
  """
  Asigna una columna existente como nuevo índice del DataFrame i lo ordena.

  Args:
  df: El DataFrame original a procesar.
  nom_columna: Nombre de la columna que contiene el identificador. Por defecto 'Unnamed: 0'.
  nom_index: Nombre del nuevo índice. Por defecto 'ID'

  Returns:
  Un nuevo DataFrame con el índice restaurado y ordenado de menor a mayor.
  Retorna un DataFrame vacío si se produce algún error.
  """

  if df is None:
    return pd.DataFrame()

  try:
    df_nou_index = df.set_index(nom_columna)
    df_nou_index.index.name = nom_index
    df_ordenat = df_nou_index.sort_index()

    # print("Índices restaurados y ordenados correctamente.")
    return df_ordenat

  except KeyError as e:
    print(f"Error: No se ha encontrado la columna {e}")
    return pd.DataFrame()
  except Exception as e:
    print(f"Se ha producido un error inesperado: {e}")
    return pd.DataFrame()

In [ ]:
df_ordenado = restaurar_index(df=df_empleados)
df_ordenado

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
ID_Original,,,,,,,,,,,,,,,,,,,
0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
1,Marc,MuÃ±oz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
2,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,TÃ¨cnic IT,4.0,NaN,NaN,NaN,16.7
3,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 â‚¬",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
4,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 â‚¬",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,Alba,MuÃ±oz,97954019T,Espanya,Bilbao,25.0,10.0,1983.0,D,"1,409 â‚¬",NaN,True,Grup B,Responsable de vendes,0.0,NaN,NaN,NaN,14.7
1003,Claudia,Gil Ferrer,55297384F,Espanya,ValÃ¨ncia,1.0,11.0,1981.0,H,1.789 â‚¬,NaN,True,Grup B,Responsable de vendes,0.0,True,29952.0,9.2,20.3
1004,Oriol,Ferrer,52590001R,Espanya,Zaragoza,15.0,7.0,1973.0,D,786â‚¬,NaN,True,Grup A,Analista,0.0,True,81381.0,6.5,13.9
1005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1006,???,###,XXXX,Narnia,Desconeguda,-99.0,99.0,3000.0,??,molts,NaN,NaN,Z,???,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Con el dataframe con el índice reestablecido
# Miramos de nuevo las filas vacías y las duplicadas

filas_vacias = df_ordenado.isna().all(axis=1).sum()
print(f"El dataset tiene {filas_vacias} filas totalmente vacías.")

filas_duplicadas = df_ordenado.duplicated().sum()
print(f"El dataframe tiene {filas_duplicadas} filas totalmente duplicadas.")

numero_duplicados_dni = df_ordenado.duplicated(subset=['DNI']).sum()
print(f"El dataset tiene {numero_duplicados_dni} filas con DNI duplicados.")

El dataset tiene 1 filas totalmente vacías.
El dataframe tiene 4 filas totalmente duplicadas.
El dataset tiene 15 filas con DNI duplicados.

In [ ]:
def limpiar_vacias_y_duplicados(df=None):
  """
  Elimina las filas completamente vacías y las filas totalmente duplicadas de un dataframe.

  Args:
  df: El DataFrame original a procesar.

  Returns:
  Un nuevo DataFrame limpio sin filas totalmente nulas ni repetidas.
  Retorna un DataFrame vacío si se produce algún error o no entran datos.
  """

  if df is None:
    return pd.DataFrame()

  try:
    df_sin_vacias = df.dropna(how='all')
    df_sin_duplicados = df_sin_vacias.drop_duplicates()

    diferencia = len(df) - len(df_sin_duplicados)

    if diferencia > 0:
      print(f"Limpieza completada: Se han eliminado {diferencia} filas.")

    return df_sin_duplicados

  except Exception as e:
    print(f"Se ha producido un error inesperado durante el proceso: {e}")
    return pd.DataFrame()

In [ ]:
# Eliminamos las filas vacías o duplicadas
df_limpio = limpiar_vacias_y_duplicados(df_ordenado)
df_limpio.info()

Limpieza completada: Se han eliminado 5 filas.
<class 'pandas.core.frame.DataFrame'>
Index: 1002 entries, 0 to 1006
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Nom                         1002 non-null   object
 1   Cognoms                     1002 non-null   object
 2   DNI                         1002 non-null   object
 3   País d'origen               1002 non-null   object
 4   Ciutat                      1002 non-null   object
 5   Dia de Naixement            1002 non-null   float64
 6   Mes de Naixement            1002 non-null   float64
 7   Any de Naixement            1002 non-null   float64
 8   Gènere                      962 non-null    object
 9   Salari mensual              1002 non-null   object
 10  Fills                       418 non-null    object
 11  No Fills                    582 non-null    object
 12  Grup Professional           1001 non-null   object
 13  CÃ rrec                     1001 non-null   object
 14  Nombre_fills                705 non-null    float64
 15  Te_cotxe                    656 non-null    object
 16  Km_anuals                   313 non-null    float64
 17  Consum_mitja_L_100km        259 non-null    float64
 18  Temperatura_mitjana_ciutat  932 non-null    float64
dtypes: float64(7), object(12)
memory usage: 156.6+ KB

In [ ]:
# Renombramos la columna con el nombre problemático
df_limpio = df_limpio.rename(columns={"CÃ\xa0rrec": "Càrrec"})
print(df_limpio.columns)

Index(['Nom', 'Cognoms', 'DNI', 'País d'origen', 'Ciutat', 'Dia de Naixement',
       'Mes de Naixement', 'Any de Naixement', 'Gènere', 'Salari mensual',
       'Fills', 'No Fills', 'Grup Professional', 'Càrrec', 'Nombre_fills',
       'Te_cotxe', 'Km_anuals', 'Consum_mitja_L_100km',
       'Temperatura_mitjana_ciutat'],
      dtype='object')

In [ ]:
def reparar_texto(valor=None):
  """
  Repara errores de codificación asumiendo un origen Windows-1252 (cp1252).
  Si la conversión falla debido a bytes invisibles o inválidos en Windows-1252,
  aplica un diccionario de rescate para casos específicos.

  Args:
  valor: El valor de la celda a evaluar.

  Returns:
  El texto corregido, o el valor original si no hay errores.
  """
  if pd.isna(valor) or not isinstance(valor, str):
    return valor

  try:
    return valor.encode('cp1252').decode('utf-8')
    if "Ã" not in texto_reparado:
      return texto_reparado

  except (AttributeError, UnicodeEncodeError, UnicodeDecodeError):
    pass

  texto = valor

  mapa_rescate = {
      "Ã\x81": "Á",      # Álvarez
      "Ã\xad": "í",      # Díaz (contiene un soft-hyphen invisible)
      "Ã": "Á",
      "Ã­": "í",
      "DÃ­az": "Díaz",
      "Ã¨": "è",         # Domènech
      "Ã¡": "á",
      "Ã©": "é",
      "Ã³": "ó",
      "Ãº": "ú",
      "Ã±": "ñ",
      "Ã§": "ç",
      "â‚¬": "€"         # El euro, por si llegara hasta aquí
    }

  for corrupto, limpio in mapa_rescate.items():
    if corrupto in texto:
      texto = texto.replace(corrupto, limpio)

  if "Ã" in texto:
    texto = texto.replace("Ã", "í")

  return texto

In [ ]:
def corregir_encoding_dataframe(df=None):
  """
  Aplica la función de reparación de texto a todas las columnas
  de tipo texto de un DataFrame.

  Args:
  df: El DataFrame a limpiar.

  Returns:
  Un nuevo DataFrame con los textos corregidos en todas sus celdas.
  Retorna un DataFrame vacío si no hay datos o hay errores.
  """
  if df is None:
    return pd.DataFrame()

  try:
    df_corregido = df.copy()

    # Identificamos solo las columnas de texto para no procesar números
    columnas_texto = df_corregido.select_dtypes(include=['object', 'string']).columns

    # Aplicamos el mapeo a cada columna de texto
    for col in columnas_texto:
      df_corregido[col] = df_corregido[col].map(reparar_texto)

    print(f"Se ha procesado con éxito el encoding de {len(columnas_texto)} columnas de texto.")
    return df_corregido

  except Exception as e:
    print(f"Error inesperado procesando el DataFrame: {e}")
    return pd.DataFrame()

In [ ]:
df_reparado = corregir_encoding_dataframe(df_limpio)
df_reparado

Se ha procesado con éxito el encoding de 12 columnas de texto.

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
ID_Original,,,,,,,,,,,,,,,,,,,
0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 €",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
1,Marc,Muñoz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 €",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
2,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,Tècnic IT,4.0,NaN,NaN,NaN,16.7
3,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 €",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
4,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 €",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
997,Jordi,Hernández,67755039Y,Espanya,Zaragoza,12.0,10.0,1961.0,Dona,"1,074 €",NaN,NaN,Grup A,Data Analyst,1.0,True,80000.0,12.0,12.0
998,Chloé,Dubois,66354268T,França,Nice,2.0,12.0,1958.0,H,"1,954 €",True,NaN,Grup B,Data Analyst,1.0,NaN,NaN,NaN,11.7
999,Adrià,Vila Díaz,57511543T,Espanya,Palma,31.0,12.0,1991.0,H,"2,010 €",True,NaN,Grup C,Analista,1.0,False,NaN,NaN,-10.0
1000,Sara,Serra,90585882A,Espanya,Tarragona,28.0,5.0,2002.0,D,"1,073 €",NaN,True,Grup A,Administratiu,0.0,False,NaN,NaN,15.8
1006,???,###,XXXX,Narnia,Desconeguda,-99.0,99.0,3000.0,??,molts,NaN,NaN,Z,???,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Voy a investigar cómo son las filas con DNI duplicados
# para tomar una decisión sobre qué filas podemos quedarnos

df_duplicados_dni = df_reparado[df_reparado.duplicated(subset=['DNI'], keep=False)]
df_duplicados_dni = df_duplicados_dni.sort_values(by=['DNI', 'ID_Original'])
df_duplicados_dni

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
ID_Original,,,,,,,,,,,,,,,,,,,
250,Laia,Navarro Vila,15909601K,Espanya,Bilbao,30.0,5.0,1958.0,D,1235 euros,True,True,Grup D,Analista junior,0.0,False,NaN,NaN,10.3
604,Laia,Navarro,15909601K,Espanya,Bilbao,30.0,5.0,1958.0,D,"1,676 €",True,False,Grup A,Analista,1.0,True,50.0,NaN,14.2
654,Oriol,Gómez,16618423V,Espanya,Madrid,10.0,1.0,1968.0,Home,1731 euros,True,NaN,Grup B,Data analyst,4.0,NaN,NaN,NaN,NaN
754,Oriol,Gómez,16618423V,Espanya,Barcelona,10.0,1.0,1968.0,Home,2.358 €,True,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
758,Oriol,Gómez,16618423V,Espanya,Màlaga,10.0,1.0,1968.0,H,1879 euros,True,NaN,Grup B,Data Analyst,4.0,False,NaN,NaN,NaN
759,Oriol,Gómez,16618423V,Espanya,Sevilla,10.0,1.0,1968.0,NaN,"2,000 €",NaN,NaN,Grup A,Responsable de vendes,5.0,NaN,NaN,NaN,20.7
558,Alexia,Pérez Díaz,49529438G,Espanya,Màlaga,12.0,10.0,1981.0,Dona,"1,176 €",NaN,True,Grup A,Data Analyst,0.0,False,NaN,NaN,38.0
692,Alexia,Pérez Díaz,49529438G,Espanya,Màlaga,12.0,10.0,1981.0,Dona,1663€,NaN,True,Grup C,Cap de projecte,NaN,True,80000.0,10.7,16.9
89,Guillem,Pujol Costa,54013571W,Espanya,A Coruña,17.0,7.0,1983.0,D,1.574 €,True,NaN,Grup B,Project lead,4.0,False,NaN,NaN,14.6
142,Marta,Ruiz,54013571W,Espanya,Palma,24.0,5.0,1982.0,H,"1,276 €",True,True,Grup A,Analista,0.0,False,NaN,NaN,15.7
25,Sara,Serra,90585882A,Espanya,Tarragona,28.0,5.0,2002.0,D,993 €,NaN,True,Grup A,Administratiu,0.0,False,NaN,NaN,15.8
104,Oriol,Vila Casals,90585882A,Espanya,Madrid,30.0,9.0,1964.0,H,1987 euros,NaN,True,Grup B,Responsable de vendes,0.0,False,NaN,NaN,13.5
114,Pol,Serra,90585882A,Espanya,Girona,4.0,12.0,1960.0,H,"1,178 €",NaN,True,Grup A,Data Analyst,NaN,False,NaN,NaN,16.2
281,Xavier,Vidal,90585882A,Espanya,Alacant,2.0,7.0,1958.0,H,1179 euros,NaN,NaN,Grup A,Tècnic IT,0.0,True,63574.0,6.0,16.8
913,Sara,Serra,90585882A,Espanya,Tarragona,28.0,5.0,2002.0,Dona,"1,000 €",NaN,True,Grup A,Administratiu,0.0,False,NaN,NaN,15.8
1000,Sara,Serra,90585882A,Espanya,Tarragona,28.0,5.0,2002.0,D,"1,073 €",NaN,True,Grup A,Administratiu,0.0,False,NaN,NaN,15.8

In [ ]:
def validar_dnis(df=None):
  """
  Elimina todos los registros con el mismo DNI si presentan contradicciones
  en el año de nacimiento o nonmbre, asumiendo que podría tratarse de personas diferentes
  o con datos no fiables.
  Valida y limpia los registros duplicados por DNI utilizando lógica de consenso.
  Si un DNI presenta discrepancias, conserva los registros de la identidad
  mayoritaria (basado en repeticiones de 'Nom' y 'Any de Naixement').
  Para los demás casos de DNI repetidos nos quedamos con el más reciente.

  Args:
  df: El DataFrame a analizar.

  Returns:
  Un nuevo DataFrame con los registros validados.
  Retorna un DataFrame vacío si faltan columnas o hay errors.
  """

  if df is None:
    return pd.DataFrame()

  try:
    columnes_requeridas = {'DNI', 'Any de Naixement', 'Nom'}
    if not columnes_requeridas.issubset(df.columns):
      print("Error: Faltan columnas en el DataFrame")
      return pd.DataFrame()

    df_wip = df.copy()

    # Análisis de frecuencias (Consenso)
    # Calculamos cuántas filas en total tiene cada DNI
    df_wip['total_dni'] = df_wip.groupby('DNI')['DNI'].transform('size')

    # Calculamos cuántas veces se repite la combinación exacta (Identidad)
    df_wip['freq_identidad'] = df_wip.groupby(['DNI', 'Nom', 'Any de Naixement'], dropna=False)['DNI'].transform('size')

    # Buscamos cuál es la frecuencia máxima ganadora para ese DNI
    df_wip['max_freq_dni'] = df_wip.groupby('DNI')['freq_identidad'].transform('max')

    # Aplicamos las reglas de salvación:
    # A) Es la identidad ganadora (freq_identidad == max_freq_dni)
    # B) Es fiable porque se repite (max_freq_dni > 1) o es el único registro (total_dni == 1)
    condicion_ganadora = df_wip['freq_identidad'] == df_wip['max_freq_dni']
    condicion_fiable = (df_wip['max_freq_dni'] > 1) | (df_wip['total_dni'] == 1)

    df_validado = df_wip[condicion_ganadora & condicion_fiable].copy()

    # Limpiamos las columnas temporales de cálculo
    df_validado = df_validado.drop(columns=['total_dni', 'freq_identidad', 'max_freq_dni'])

    # Finalmente nos quedamos con la fila más reciente de los DNI duplicados
    df_validado = df_validado.sort_values(by=['DNI', 'ID_Original'])
    df_validado = df_validado.drop_duplicates(subset=['DNI'], keep='last')

    diferencia = len(df) - len(df_validado)
    if diferencia > 0:
      print(f"Validación completada: Se han eliminado {diferencia} filas.\n")

    return df_validado

  except Exception as e:
    print(f"Se ha producido un error: {e}")
    return pd.DataFrame()

In [21]:
df_validado_dnis = validar_dnis(df_reparado)
df_validado_dnis.info()

numero_duplicados_dni = df_validado_dnis.duplicated(subset=['DNI']).sum()
print(f"\nEl dataset tiene {numero_duplicados_dni} filas con DNI duplicados.")

Validación completada: Se han eliminado 12 filas.

<class 'pandas.core.frame.DataFrame'>
Index: 990 entries, 195 to 1006
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Nom                         990 non-null    object
 1   Cognoms                     990 non-null    object
 2   DNI                         990 non-null    object
 3   País d'origen               990 non-null    object
 4   Ciutat                      990 non-null    object
 5   Dia de Naixement            990 non-null    float64
 6   Mes de Naixement            990 non-null    float64
 7   Any de Naixement            990 non-null    float64
 8   Gènere                      950 non-null    object
 9   Salari mensual              990 non-null    object
 10  Fills                       412 non-null    object
 11  No Fills                    575 non-null    object
 12  Grup Professional           990 non-null    object
 13  Càrrec                      990 non-null    object
 14  Nombre_fills                694 non-null    float64
 15  Te_cotxe                    646 non-null    object
 16  Km_anuals                   312 non-null    float64
 17  Consum_mitja_L_100km        258 non-null    float64
 18  Temperatura_mitjana_ciutat  923 non-null    float64
dtypes: float64(7), object(12)
memory usage: 154.7+ KB

El dataset tiene 0 filas con DNI duplicados.

In [22]:
# Investigamos filas con campos clave vacíos
# No tienen nulos: Nom, Cognoms, DNI, País d'origen, Dia de Naixement, Mes de Naixement, Any de Naixement, Salari mensual, Grup Professional, Càrrec
# Contienen nulos: Gènere, Fills, No Fills, Nombre_fills, Te_cotxe, Km_anuals, Consum_mitja_L_100km, Temperatura_mitjana_ciutat

filtro_nulos_genero = df_validado_dnis["Gènere"].isna()
filtro_nulos_hijos = df_validado_dnis["Fills"].isna() & df_validado_dnis["No Fills"].isna() & df_validado_dnis["Nombre_fills"].isna()
filtro_nulos_coche = df_validado_dnis["Te_cotxe"].isna() & df_validado_dnis["Km_anuals"].isna() & df_validado_dnis["Consum_mitja_L_100km"].isna()
filtro_nulos_temperatura = df_validado_dnis["Temperatura_mitjana_ciutat"].isna()
filtro_dudosos_nacimiento = df_validado_dnis["Any de Naixement"] > 2010
filtro_dudosos_nombre = df_validado_dnis["Nom"].str.contains(r'[^a-zA-ZÀ-ÿ\s\-]', regex=True, na=False)

df_posible_eliminacion = df_validado_dnis[filtro_dudosos_nacimiento]
print(f"Filas con datos dudosos: {len(df_posible_eliminacion)}")
df_posible_eliminacion

Filas con datos dudosos: 61

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
ID_Original,,,,,,,,,,,,,,,,,,,
201,Marta,Domènech Costa,10624307P,Espanya,Màlaga,-5.0,13.0,3000.0,H,"1,445 €",True,NaN,Grup B,Data Analyst,1.0,False,NaN,NaN,17.9
788,Hannah,Fischer Wolf,14098443W,Alemanya,Leipzig,-5.0,99.0,2019.0,H,"1,034 €",NaN,True,Grup A,Tècnic IT,NaN,False,NaN,NaN,12.5
652,Kristian,Lie,15190410S,Noruega,Stavanger,32.0,0.0,3000.0,H,939 €,NaN,True,Grup A,Analista junior,0.0,NaN,NaN,NaN,8.5
325,Marina,Álvarez Puig,20880123Z,Espanya,Valladolid,0.0,0.0,2019.0,NaN,"1,320 €",True,NaN,Grup A,Responsable de vendes,1.0,False,NaN,NaN,6.2
764,Anna,Weber,22111010Q,Alemanya,Hamburg,-5.0,0.0,2019.0,Dona,"1,209 €",True,NaN,Grup A,Responsable de vendes,1.0,True,50000.0,11.6,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512,Anna,Puig Sánchez,98735423C,Espanya,Màlaga,-5.0,0.0,2019.0,H,962 €,NaN,True,Grup A,Analista,0.0,False,NaN,NaN,19.7
751,Aina,Álvarez,99079258Z,Espanya,Palma,-5.0,99.0,2026.0,M,"1,850 €",NaN,True,Grup B,Responsable de vendes,NaN,NaN,NaN,NaN,17.0
911,Paul,Hoffmann Braun,99290377X,Alemanya,Frankfurt,32.0,13.0,3000.0,Home,"1,740 €",NaN,True,Grup B,Tècnic IT,NaN,True,80000.0,0.5,12.6
268,Xavier,López,99600963X,Espanya,Valladolid,-5.0,13.0,2019.0,D,"1,869 €",True,NaN,Grup B,Cap de projecte,1.0,False,NaN,NaN,14.6
1006,???,###,XXXX,Narnia,Desconeguda,-99.0,99.0,3000.0,??,molts,NaN,NaN,Z,???,NaN,NaN,NaN,NaN,NaN

In [19]:
def limpiar_segun_filtro(df=None, filtro=None):
  """
  Elimina las filas del dataframe según el filtro especificado.

  Args:
  df: El DataFrame original a procesar.

  Returns:
  Un nuevo DataFrame limpio sin filas totalmente nulas ni repetidas.
  Retorna un DataFrame vacío si se produce algún error o no entran datos.
  """

  if df is None:
    return pd.DataFrame()

  if filtro is None:
    return df

  try:
    df_limpio = df[~filtro].copy()

    filas_eliminadas = len(df) - len(df_limpio)
    print(f"Limpieza completada: Se han eliminado {filas_eliminadas} filas.")

    return df_limpio

  except Exception as e:
    print(f"Se ha producido un error inesperado durante el proceso: {e}")
    return pd.DataFrame()

In [23]:
# Vamos a eliminar de las filas de datos que hemos considerado no válidas
# Concretamente hemos visto que eran las que presentaban fechas de nacimiento incorrectas
# También hemos visto que hay bastantes filas con datos nulos en diversos campos
# Pero de momento he decidido no eliminarlas puesto que no sé exactamente qué datos necesitaré para el análisis posterior

filtro_dudosos_nacimiento = df_validado_dnis["Any de Naixement"] > 2010
df_filtrado = limpiar_segun_filtro(df_validado_dnis, filtro=filtro_dudosos_nacimiento)
df_filtrado.info()

Limpieza completada: Se han eliminado 61 filas.
<class 'pandas.core.frame.DataFrame'>
Index: 929 entries, 195 to 24
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Nom                         929 non-null    object
 1   Cognoms                     929 non-null    object
 2   DNI                         929 non-null    object
 3   País d'origen               929 non-null    object
 4   Ciutat                      929 non-null    object
 5   Dia de Naixement            929 non-null    float64
 6   Mes de Naixement            929 non-null    float64
 7   Any de Naixement            929 non-null    float64
 8   Gènere                      893 non-null    object
 9   Salari mensual              929 non-null    object
 10  Fills                       391 non-null    object
 11  No Fills                    540 non-null    object
 12  Grup Professional           929 non-null    object
 13  Càrrec                      929 non-null    object
 14  Nombre_fills                651 non-null    float64
 15  Te_cotxe                    600 non-null    object
 16  Km_anuals                   290 non-null    float64
 17  Consum_mitja_L_100km        240 non-null    float64
 18  Temperatura_mitjana_ciutat  866 non-null    float64
dtypes: float64(7), object(12)
memory usage: 145.2+ KB

## N1.3: Transformaciones y preparación del dataset

En este ejercicio vamos a aplicar transformaciones básicas en los datos pera poder usarlos en análisis posteriores. Concretamente deberemos:

- Normalizar valores categóricos (Género, Grupo Profesional y Cargo)
- Revisar coherencia de valores de coches (Kms y Consumo)
- Revisar coherencia de valores de hijos (Número de hijos)
- Unificar columna de hijos
- Validar temperaturas (según criterio de imputación)
- Revisar datos de salarios (según criterio de imputación)

In [24]:
# Ver valores de Género
# El identificador de género presenta diferentes valores
# pero vemos que los nombres no siempre se corresponden al género esperado y es difícil intepretar a qué género se refiere en algunos casos.
# Decido usar la convención habitual interpretando: H (Hombre), D (Dona = Mujer), M (Masculino), F (Femenino)
# Para los casos A y NC no me queda claro a qué género se refiere y lo normalizo como Desconegut
recuento = df_filtrado.groupby('Gènere')['Nom'].count().reset_index()
recuento = recuento.rename(columns={'Nom': 'Total'})
display(recuento)

filtro_genero = (df_filtrado['Gènere'] == 'M')
lista_nombres = sorted(df_filtrado.loc[filtro_genero, 'Nom'].unique())
display(lista_nombres)

  Gènere  Total
0      A     24
1      D    299
2   Dona    110
3      F     98
4      H    260
5   Home     46
6      M     33
7     NC     23

['Adrià',
 'Alba',
 'Alexia',
 'Carlos',
 'Chiara',
 'Claudia',
 'David',
 'Francesca',
 'Hugo',
 'Irene',
 'Jordi',
 'Laia',
 'Lucía',
 'Magnus',
 'Marc',
 'Marina',
 'Marta',
 'Noa',
 'Oriol',
 'Paolo',
 'Sara',
 'Sergio',
 'Sofie',
 'Víctor']

In [61]:
# Normalizar valores de Género
def normalizar_genero(df):
  """
  Normaliza la columna 'Gènere' unificando las categorías.
  """
  if df is None or 'Gènere' not in df.columns:
    return df

  df_genero_ok = df.copy()

  mapa_genero = {
      'Home': 'Home', 'Dona': 'Dona',
      'H': 'Home', 'M': 'Home',
      'D': 'Dona', 'F': 'Dona',
      'A': 'No Conegut', 'NC': 'No Conegut'
  }

  # El .str.upper() es un escudo extra por si alguien escribió 'h' en minúscula
  df_genero_ok['Gènere'] = df_genero_ok['Gènere'].str.upper().map(mapa_genero).fillna('No Conegut')

  return df_genero_ok

df_normalizado_genero = normalizar_genero(df_filtrado)
# display(df_normalizado_genero)
# display(df_normalizado_genero.info())

recuento = df_normalizado_genero.groupby('Gènere')['Nom'].count().reset_index()
recuento = recuento.rename(columns={'Nom': 'Total'})
display(recuento)

       Gènere  Total
0        Dona    397
1        Home    293
2  No Conegut    239

In [62]:
# Ver valores de Grupo Profesional
recuento = df_normalizado_genero.groupby('Grup Professional')['Càrrec'].count().reset_index()
recuento = recuento.rename(columns={'Càrrec': 'Total'})
display(recuento)

lista_cargos = sorted(df_normalizado_genero['Càrrec'].dropna().unique())
display(lista_cargos)

  Grup Professional  Total
0            Grup A    433
1            Grup B    326
2            Grup C    132
3            Grup D     38

['Admin.',
 'Administratiu',
 'Analista',
 'Analista junior',
 'Analyst',
 'Cap de Projecte',
 'Cap de projecte',
 'Data Analyst',
 'Data analyst',
 'Project lead',
 'Responsable de vendes',
 'Senior analyst',
 'Tècnic IT']

In [65]:
# Normalizamos los valores de 'Càrrec'
def normalizar_cargo(df):
  """
  Normaliza la columna 'Càrrec' unificando las categorías.
  """
  if df is None or 'Càrrec' not in df.columns:
    return df

  df_cargo_ok = df.copy()

  mapa_cargos = {
      'Administratiu': 'Administratiu',
      'Admin.': 'Administratiu',
      'Analista junior': 'Analista',
      'Senior analyst': 'Analista',
      'Analista': 'Analista',
      'Analyst': 'Analista',
      'Data Analyst': 'Analista',
      'Data analyst': 'Analista',
      'Cap de Projecte': 'Cap de Projecte',
      'Cap de projecte': 'Cap de Projecte',
      'Project lead': 'Cap de Projecte',
      'Project lead': 'Cap de Projecte',
      'Responsable de vendes': 'Responsable de Vendes',
      'Tècnic IT': 'Tècnic IT' }

  # El .str.upper() es un escudo extra por si alguien escribió 'h' en minúscula
  df_cargo_ok['Càrrec'] = df_cargo_ok['Càrrec'].map(mapa_cargos).fillna('Desconegut')

  return df_cargo_ok

df_normalizado_cargo = normalizar_cargo(df_normalizado_genero)
# display(df_normalizado_cargo[df_normalizado_cargo['Càrrec'] == 'Analista'])
# display(df_normalizado_cargo)

lista_cargos = sorted(df_normalizado_cargo['Càrrec'].dropna().unique())
display(lista_cargos)

print()
display(df_normalizado_cargo.info())

['Administratiu',
 'Analista',
 'Cap de Projecte',
 'Responsable de Vendes',
 'Tècnic IT']

<class 'pandas.core.frame.DataFrame'>
Index: 929 entries, 195 to 24
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Nom                         929 non-null    object
 1   Cognoms                     929 non-null    object
 2   DNI                         929 non-null    object
 3   País d'origen               929 non-null    object
 4   Ciutat                      929 non-null    object
 5   Dia de Naixement            929 non-null    float64
 6   Mes de Naixement            929 non-null    float64
 7   Any de Naixement            929 non-null    float64
 8   Gènere                      929 non-null    object
 9   Salari mensual              929 non-null    object
 10  Fills                       391 non-null    object
 11  No Fills                    540 non-null    object
 12  Grup Professional           929 non-null    object
 13  Càrrec                      929 non-null    object
 14  Nombre_fills                651 non-null    float64
 15  Te_cotxe                    600 non-null    object
 16  Km_anuals                   290 non-null    float64
 17  Consum_mitja_L_100km        240 non-null    float64
 18  Temperatura_mitjana_ciutat  866 non-null    float64
dtypes: float64(7), object(12)
memory usage: 145.2+ KB

None

In [66]:
# Convertimos columnas a tipo Int64
df_normalizado_enteros = df_normalizado_cargo.copy()
df_normalizado_enteros['Nombre_fills'] = df_normalizado_enteros['Nombre_fills'].astype('Int64')
df_normalizado_enteros['Dia de Naixement'] = df_normalizado_enteros['Dia de Naixement'].astype('Int64')
df_normalizado_enteros['Mes de Naixement'] = df_normalizado_enteros['Mes de Naixement'].astype('Int64')
df_normalizado_enteros['Any de Naixement'] = df_normalizado_enteros['Any de Naixement'].astype('Int64')

display(df_normalizado_enteros.info())

<class 'pandas.core.frame.DataFrame'>
Index: 929 entries, 195 to 24
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Nom                         929 non-null    object
 1   Cognoms                     929 non-null    object
 2   DNI                         929 non-null    object
 3   País d'origen               929 non-null    object
 4   Ciutat                      929 non-null    object
 5   Dia de Naixement            929 non-null    Int64
 6   Mes de Naixement            929 non-null    Int64
 7   Any de Naixement            929 non-null    Int64
 8   Gènere                      929 non-null    object
 9   Salari mensual              929 non-null    object
 10  Fills                       391 non-null    object
 11  No Fills                    540 non-null    object
 12  Grup Professional           929 non-null    object
 13  Càrrec                      929 non-null    object
 14  Nombre_fills                651 non-null    Int64
 15  Te_cotxe                    600 non-null    object
 16  Km_anuals                   290 non-null    float64
 17  Consum_mitja_L_100km        240 non-null    float64
 18  Temperatura_mitjana_ciutat  866 non-null    float64
dtypes: Int64(4), float64(3), object(12)
memory usage: 148.8+ KB

None

In [67]:
# Investigo problemático con los Consumos

filtro_dudas_consumo = df_normalizado_enteros["Km_anuals"].isna() & df_normalizado_enteros["Consum_mitja_L_100km"].notna()
display(df_normalizado_enteros[filtro_dudas_consumo])
# filtro_dudas_kms = df_revisado_coches["Km_anuals"].notna() & df_revisado_coches["Consum_mitja_L_100km"].isna()

kms_media = df_normalizado_enteros.groupby('Ciutat')['Km_anuals'].mean().round(2)
display(kms_media.loc['Girona'])
display(kms_media.loc['Bilbao'])

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
ID_Original,,,,,,,,,,,,,,,,,,,
60,Núria,Navarro,47969333N,Espanya,Girona,30,6,1981,Home,"2,125 €",NaN,NaN,Grup B,Tècnic IT,<NA>,True,NaN,25.0,NaN
4,David,Vila,82070937P,Espanya,Bilbao,29,11,1965,No Conegut,"1,284 €",NaN,True,Grup B,Administratiu,<NA>,True,NaN,11.8,13.1

np.float64(42498.83)

np.float64(52090.05)

In [68]:
# Revisar coherencia valores de Coches

def revisar_coches(df):
  """
  Revisa los valores de la columna 'Te_cotxe' comprobando que sea True si hay valores relacionados.
  También comprueba que los valores de 'Km_anuals' y 'Consum_mitja_L_100km' sean coherentes.
  """
  columnas_requeridas = {'Te_cotxe', 'Km_anuals', 'Consum_mitja_L_100km'}

  if df is None or not columnas_requeridas.issubset(df.columns):
    return df

  df_coche_ok = df.copy()

  # Arreglo casos de Kms negativos
  filtro_kms_ko = df_coche_ok['Km_anuals'] < 0
  df_coche_ok.loc[filtro_kms_ko, 'Km_anuals'] = np.nan

  # Miro casos en que había valores de Kms y Consumo y aseguro que tenga coche
  filtro_coche_ok = df_coche_ok['Km_anuals'].notna() & df_coche_ok['Consum_mitja_L_100km'].notna() & (df_coche_ok['Te_cotxe'] != True)
  df_coche_ok.loc[filtro_coche_ok, 'Te_cotxe'] = True

  # Miro casos en que no había valores de Kms ni Consumo y pongo que no tiene coche si era nulo
  filtro_coche_ko = df_coche_ok['Km_anuals'].isna() & df_coche_ok['Consum_mitja_L_100km'].isna() & (df_coche_ok['Te_cotxe'] != True)
  df_coche_ok.loc[filtro_coche_ko, 'Te_cotxe'] = False

  # Imputo los valores de Kms para los casos en que había consumo pero no Kms, cogiendo el valor de la media para esa Ciudad
  filtro_dudas_consumo = df_coche_ok["Km_anuals"].isna() & df_coche_ok["Consum_mitja_L_100km"].notna()
  kms_media = df_coche_ok.groupby('Ciutat')['Km_anuals'].mean().round(2)
  df_coche_ok.loc[filtro_dudas_consumo, 'Km_anuals'] = df_coche_ok.loc[filtro_dudas_consumo, 'Ciutat'].map(kms_media)

  total_actualizados = filtro_coche_ok.sum() + filtro_coche_ko.sum() + filtro_kms_ko.sum() + filtro_dudas_consumo.sum()

  print(f"Se han actualizado {total_actualizados} registros de coche.\n")

  return df_coche_ok

df_revisado_coches = revisar_coches(df_normalizado_enteros)
display(df_revisado_coches.info())

Se han actualizado 630 registros de coche.

<class 'pandas.core.frame.DataFrame'>
Index: 929 entries, 195 to 24
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Nom                         929 non-null    object
 1   Cognoms                     929 non-null    object
 2   DNI                         929 non-null    object
 3   País d'origen               929 non-null    object
 4   Ciutat                      929 non-null    object
 5   Dia de Naixement            929 non-null    Int64
 6   Mes de Naixement            929 non-null    Int64
 7   Any de Naixement            929 non-null    Int64
 8   Gènere                      929 non-null    object
 9   Salari mensual              929 non-null    object
 10  Fills                       391 non-null    object
 11  No Fills                    540 non-null    object
 12  Grup Professional           929 non-null    object
 13  Càrrec                      929 non-null    object
 14  Nombre_fills                651 non-null    Int64
 15  Te_cotxe                    929 non-null    object
 16  Km_anuals                   287 non-null    float64
 17  Consum_mitja_L_100km        240 non-null    float64
 18  Temperatura_mitjana_ciutat  866 non-null    float64
dtypes: Int64(4), float64(3), object(12)
memory usage: 148.8+ KB

None

In [69]:
# Revisar coherencia valores de Hijos

filtro_dudas_hijos = (df_revisado_coches["No Fills"] == True) & df_revisado_coches["Nombre_fills"].isna()
display(df_revisado_coches[filtro_dudas_hijos])

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
ID_Original,,,,,,,,,,,,,,,,,,,
195,Claudia,Pujol Torres,10161088K,Espanya,Las Palmas de Gran Canaria,27,9,1996,Home,946€,NaN,True,Grup A,Tècnic IT,<NA>,False,NaN,NaN,22.7
204,Marina,Sánchez,10889014V,Espanya,Tarragona,20,8,2000,Home,987 €,NaN,True,Grup A,Analista,<NA>,False,NaN,NaN,16.2
213,Oriol,Díaz Romero,10968781V,Espanya,Tarragona,26,4,1996,Dona,935 €,NaN,True,Grup A,Administratiu,<NA>,True,1000000.0,25.0,17.1
275,Noa,Costa Gómez,10969588M,Espanya,Murcia,1,2,1989,Dona,"1,682 €",NaN,True,Grup B,Analista,<NA>,True,80000.0,11.4,18.2
228,Nil,Casals Pérez,13031322X,Espanya,Tarragona,24,10,1988,Dona,2073€,NaN,True,Grup C,Cap de Projecte,<NA>,False,NaN,NaN,12.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
775,Marc,Muñoz,97933602T,Espanya,Girona,26,2,1982,Dona,"1,327 €",NaN,True,Grup A,Analista,<NA>,True,16998.0,NaN,18.1
120,Claudia,Ribera,98032908G,Espanya,Murcia,9,1,1984,Dona,1567€,NaN,True,Grup B,Analista,<NA>,False,NaN,NaN,22.1
262,Víctor,Vidal Roca,98089763D,Espanya,Girona,2,10,1968,Home,"1,771 €",NaN,True,Grup C,Analista,<NA>,False,NaN,NaN,15.2
791,Paolo,Lombardi De Luca,98399977K,Itàlia,Bologna,26,10,1987,Home,2.870 €,NaN,True,Grup D,Tècnic IT,<NA>,False,NaN,NaN,12.0
327,Pol,Casals,99324622A,Espanya,Zaragoza,12,3,1996,Home,1668 euros,NaN,True,Grup B,Administratiu,<NA>,False,NaN,NaN,13.9

In [70]:
# Actualizar valores de Hijos

def revisar_hijos(df):
  """
  Revisa los valores de la columna 'Nombre_fills' comprobando que sea 0 en caso de no tener hijos.
  """
  columnas_requeridas = {'Fills', 'No Fills', 'Nombre_fills'}

  if df is None or not columnas_requeridas.issubset(df.columns):
    return df

  df_hijos_ok = df.copy()

  filtro_hijos_no = (df_hijos_ok["No Fills"] == True) & df_hijos_ok["Nombre_fills"].isna()
  df_hijos_ok.loc[filtro_hijos_no, 'Nombre_fills'] = 0

  print(f"Se han actualizado {filtro_hijos_no.sum()} registros de hijos.\n")

  return df_hijos_ok

df_revisado_hijos = revisar_hijos(df_revisado_coches)
display(df_revisado_hijos.info())

Se han actualizado 249 registros de hijos.

<class 'pandas.core.frame.DataFrame'>
Index: 929 entries, 195 to 24
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Nom                         929 non-null    object
 1   Cognoms                     929 non-null    object
 2   DNI                         929 non-null    object
 3   País d'origen               929 non-null    object
 4   Ciutat                      929 non-null    object
 5   Dia de Naixement            929 non-null    Int64
 6   Mes de Naixement            929 non-null    Int64
 7   Any de Naixement            929 non-null    Int64
 8   Gènere                      929 non-null    object
 9   Salari mensual              929 non-null    object
 10  Fills                       391 non-null    object
 11  No Fills                    540 non-null    object
 12  Grup Professional           929 non-null    object
 13  Càrrec                      929 non-null    object
 14  Nombre_fills                900 non-null    Int64
 15  Te_cotxe                    929 non-null    object
 16  Km_anuals                   287 non-null    float64
 17  Consum_mitja_L_100km        240 non-null    float64
 18  Temperatura_mitjana_ciutat  866 non-null    float64
dtypes: Int64(4), float64(3), object(12)
memory usage: 148.8+ KB

None

In [71]:
# Eliminamos columnas Fills i No Fills
df_revisado_hijos = df_revisado_hijos.drop(columns=['Fills', 'No Fills'])
display(df_revisado_hijos.info())

<class 'pandas.core.frame.DataFrame'>
Index: 929 entries, 195 to 24
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Nom                         929 non-null    object
 1   Cognoms                     929 non-null    object
 2   DNI                         929 non-null    object
 3   País d'origen               929 non-null    object
 4   Ciutat                      929 non-null    object
 5   Dia de Naixement            929 non-null    Int64
 6   Mes de Naixement            929 non-null    Int64
 7   Any de Naixement            929 non-null    Int64
 8   Gènere                      929 non-null    object
 9   Salari mensual              929 non-null    object
 10  Grup Professional           929 non-null    object
 11  Càrrec                      929 non-null    object
 12  Nombre_fills                900 non-null    Int64
 13  Te_cotxe                    929 non-null    object
 14  Km_anuals                   287 non-null    float64
 15  Consum_mitja_L_100km        240 non-null    float64
 16  Temperatura_mitjana_ciutat  866 non-null    float64
dtypes: Int64(4), float64(3), object(10)
memory usage: 134.3+ KB

None

In [72]:
# Validar Temperaturas

filtro_tempeartura_nula = df_revisado_hijos["Temperatura_mitjana_ciutat"].isna()
display(df_revisado_hijos[filtro_tempeartura_nula])

temperaturas_ciudad = df_revisado_hijos.groupby('Ciutat')['Temperatura_mitjana_ciutat'].mean().round(2).reset_index()
display(temperaturas_ciudad)

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
ID_Original,,,,,,,,,,,,,,,,,
458,Anna,Moreno,11361006M,Espanya,Zaragoza,10,3,1968,No Conegut,dos mil,Grup B,Analista,3,True,3936.0,12.9,NaN
100,Carlos,Muñoz Martínez,12176998P,Espanya,Alacant,5,12,1972,Home,918 €,Grup A,Tècnic IT,0,False,NaN,NaN,NaN
979,Carlos,Vila Domènech,18004248E,Espanya,Palma,6,4,2004,Dona,902 €,Grup A,Analista,0,False,NaN,NaN,NaN
45,Hugo,Ribera,18484847C,Espanya,Barcelona,21,4,1997,Dona,"1,032 €",Grup A,Responsable de Vendes,1,False,NaN,NaN,NaN
621,Xavier,Casals,21149828B,Espanya,Madrid,10,6,1998,Dona,976 €,Grup A,Responsable de Vendes,1,False,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,Sergio,Martínez Álvarez,93906615X,Espanya,Bilbao,25,1,1995,No Conegut,"1,003 €",Grup A,Tècnic IT,0,False,NaN,NaN,NaN
993,Xavier,García Gil,95100395N,Espanya,Girona,16,7,1960,Dona,1437€,Grup A,Analista,0,False,NaN,NaN,NaN
642,Guillem,Fernández,96950282C,Espanya,Girona,2,8,1981,Home,"1,747 €",Grup B,Analista,2,False,NaN,NaN,NaN
566,Marie,Robert Petit,98931424M,França,Toulouse,20,3,1968,No Conegut,"1,029 €",Grup A,Administratiu,3,False,NaN,NaN,NaN
552,Adrià,Ribera,99152055K,Espanya,Sevilla,4,11,1981,Home,"1,698 €",Grup B,Cap de Projecte,4,False,NaN,NaN,NaN

                        Ciutat  Temperatura_mitjana_ciutat
0                     A Coruña                       12.86
1                      Alacant                       17.33
2                    Barcelona                       16.79
3                       Bergen                        8.79
4                       Berlin                        9.53
5                       Bilbao                       13.51
6                      Bologna                       15.58
7                     Bordeaux                       11.12
8                   Düsseldorf                       11.43
9                      Firenze                       14.39
10                   Frankfurt                       11.78
11                      Genova                       17.74
12                      Girona                       13.00
13                     Hamburg                       10.03
14                        Köln                        5.33
15  Las Palmas de Gran Canaria                       21.29
16                     Leipzig                       11.30
17                       Lille                       14.79
18                        Lyon                       10.70
19                      Madrid                       15.83
20                   Marseille                       15.07
21                      Milano                       13.24
22                      Murcia                       19.10
23                      Màlaga                       19.72
24                     München                        9.38
25                      Nantes                       12.17
26                      Napoli                       17.49
27                        Nice                       16.36
28                        Oslo                        7.79
29                       Palma                       17.27
30                       Paris                       12.45
31                        Roma                       14.17
32                     Sevilla                       19.00
33                   Stavanger                        7.66
34                   Stuttgart                       10.10
35                   Tarragona                       16.40
36                      Torino                       15.88
37                    Toulouse                       13.54
38                      Tromsø                        2.72
39                   Trondheim                        4.38
40                  Valladolid                       13.63
41                    València                       16.47
42                     Venezia                       13.85
43                    Zaragoza                       15.32

In [73]:
def revisar_temperatura_ciudad(df):
  """
  Revisa los valores de la columna 'Temperatura_mitjana_ciutat' y imputa los valores nulos.
  """

  if df is None or 'Temperatura_mitjana_ciutat' not in df.columns:
    return df

  df_temp_ok = df.copy()

  # Imputo los valores de Temperatura nula cogiendo la media para esa Ciudad
  filtro_no_temp = df_temp_ok["Temperatura_mitjana_ciutat"].isna()
  temp_media_ciudad = df_temp_ok.groupby('Ciutat')['Temperatura_mitjana_ciutat'].mean().round(2)
  df_temp_ok.loc[filtro_no_temp, 'Temperatura_mitjana_ciutat'] = df_temp_ok.loc[filtro_no_temp, 'Ciutat'].map(temp_media_ciudad)

  print(f"Se han actualizado {filtro_no_temp.sum()} registros de temperatura.\n")

  return df_temp_ok

df_revisado_temp = revisar_temperatura_ciudad(df_revisado_hijos)
display(df_revisado_temp.info())

Se han actualizado 63 registros de temperatura.

<class 'pandas.core.frame.DataFrame'>
Index: 929 entries, 195 to 24
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Nom                         929 non-null    object
 1   Cognoms                     929 non-null    object
 2   DNI                         929 non-null    object
 3   País d'origen               929 non-null    object
 4   Ciutat                      929 non-null    object
 5   Dia de Naixement            929 non-null    Int64
 6   Mes de Naixement            929 non-null    Int64
 7   Any de Naixement            929 non-null    Int64
 8   Gènere                      929 non-null    object
 9   Salari mensual              929 non-null    object
 10  Grup Professional           929 non-null    object
 11  Càrrec                      929 non-null    object
 12  Nombre_fills                900 non-null    Int64
 13  Te_cotxe                    929 non-null    object
 14  Km_anuals                   287 non-null    float64
 15  Consum_mitja_L_100km        240 non-null    float64
 16  Temperatura_mitjana_ciutat  929 non-null    float64
dtypes: Int64(4), float64(3), object(10)
memory usage: 134.3+ KB

None

In [74]:
# Formatear valores de Salarios
filtro_salarios = df_revisado_temp["Salari mensual"].str.contains('.', regex=False)
display(df_revisado_temp[filtro_salarios][['Nom', 'Cognoms', 'Grup Professional', 'Càrrec', 'Salari mensual']])

,Nom,Cognoms,Grup Professional,Càrrec,Salari mensual
ID_Original,,,,,
644,Pol,Ribera Hernández,Grup B,Cap de Projecte,1.610 €
326,Alejandro,Fernández,Grup B,Tècnic IT,1.403 €
507,Marco,Conti,Grup B,Analista,1.527 €
85,Joana,Torres Muñoz,Grup A,Tècnic IT,1.008 €
935,Chiara,Rizzo,Grup A,Analista,1.185 €
477,Laia,Torres Romero,Grup A,Cap de Projecte,1.341 €
235,Alejandro,Díaz,Grup A,Analista,1.147 €
618,Laia,Moreno,Grup A,Cap de Projecte,1.200 €
578,Lucía,Gómez,Grup B,Responsable de Vendes,1.944 €
199,Hugo,Roca,Grup A,Responsable de Vendes,1.007 €
829,Sergio,Casals Navarro,Grup A,Analista,1.021 €
736,Anna,García,Grup B,Analista,2.397 €
338,Alexia,Romero Soler,Grup D,Tècnic IT,3.162 €
520,Arthur,Michel,Grup A,Analista,1.081 €
987,Alba,Gil,Grup C,Analista,2.184 €
883,Jonas,Wagner Meyer,Grup B,Analista,1.629 €
862,David,Vila Álvarez,Grup B,Analista,1.349 €
290,Ole,Johansen,Grup C,Cap de Projecte,2.534 €
697,Elias,Pettersen Karlsen,Grup A,Analista,1.237 €
605,Lena,Schröder Schwarz,Grup D,Analista,2.458 €
570,Núria,Ruiz Gil,Grup B,Analista,1.419 €
203,Irene,Soler,Grup B,Analista,1.761 €
830,Marc,Martínez Vila,Grup A,Administratiu,1.131 €
141,Marta,López Soler,Grup A,Analista,1.106 €
396,Alexia,Hernández,Grup A,Cap de Projecte,1.099 €
730,Claudia,Gil Ferrer,Grup B,Responsable de Vendes,1.789 €
881,Lucía,Gómez,Grup A,Responsable de Vendes,1.340 €
614,Marta,Roca,Grup C,Analista,2.706 €
502,Pau,Roca Díaz,Grup A,Tècnic IT,1.028 €
852,Pau,Romero Hernández,Grup A,Analista,1.276 €
659,Marc,Moreno,Grup B,Responsable de Vendes,1.585 €
498,Paul,Garcia Vincent,Grup C,Analista,2.690 €
69,Laura,Hoffmann Bauer,Grup B,Analista,1.798 €
443,Núria,Casals Díaz,Grup B,Analista,2.121 €
651,Kasper,Pettersen,Grup B,Analista,2.290 €
822,Hugo,Leroy,Grup C,Analista,1.804 €
128,Pau,Ramos,Grup B,Analista,1.636 €
56,Sergio,Vidal Álvarez,Grup A,Administratiu,1.021 €
615,Paolo,Ricci,Grup B,Tècnic IT,1.766 €
689,Sara,Gil Pujol,Grup A,Analista,1.163 €
779,Laia,Pujol Casals,Grup A,Analista,1.179 €
933,Alba,Pujol Ferrer,Grup A,Cap de Projecte,1.469 €
731,Irene,Ribera,Grup D,Administratiu,2.613 €
68,Joana,Torres,Grup C,Cap de Projecte,2.275 €
265,Marc,Romero Puig,Grup A,Analista,1.026 €
927,Anna,Pérez Serra,Grup B,Analista,1.927 €
110,Víctor,Ruiz Hernández,Grup B,Analista,1.825 €
691,Alexia,Roca,Grup A,Cap de Projecte,1.435 €
91,Alexia,Gil,Grup C,Responsable de Vendes,2.257 €
180,Alexia,Roca Soler,Grup C,Analista,2.025 €
868,Alexia,García,Grup A,Tècnic IT,1.336 €
409,Francesca,Esposito,Grup A,Analista,1.552 €
791,Paolo,Lombardi De Luca,Grup D,Tècnic IT,2.870 €
491,Sergio,Ribera,Grup A,Analista,1.517 €

In [75]:
# Formatear los valores de los Salarios como valores numéricos

def formatear_salarios(df):
  if df is None or 'Salari mensual' not in df.columns:
    return df

  df_salario_ok = df.copy()

  # Imputación manual para casos concretos donde estaba escrito en letras
  mapa_texto_numero = {
      'dos mil': '2000',
      'tres mil': '3000',
      'mil vuit-cents': '1800' }

  df_salario_ok['Salari formatejat €'] = df_salario_ok['Salari mensual'].astype(str).str.lower()
  df_salario_ok['Salari formatejat €'] = df_salario_ok['Salari formatejat €'].replace(mapa_texto_numero, regex=True)

  # Quitamos todo lo que no sean dígitos
  df_salario_ok['Salari formatejat €'] = df_salario_ok['Salari formatejat €'].str.replace(r'[^\d]', '', regex=True)

  # Conversión a valor numérico
  df_salario_ok['Salari formatejat €'] = pd.to_numeric(df_salario_ok['Salari formatejat €'], errors='coerce')

  return df_salario_ok

df_revisado_salarios = formatear_salarios(df_revisado_temp)
display(df_revisado_salarios.head(50))

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat,Salari formatejat €
ID_Original,,,,,,,,,,,,,,,,,,
195,Claudia,Pujol Torres,10161088K,Espanya,Las Palmas de Gran Canaria,27,9,1996,Home,946€,Grup A,Tècnic IT,0,False,NaN,NaN,22.70,946.0
270,Oriol,Torres Vila,10443906N,Espanya,Tarragona,8,9,1962,Dona,1632€,Grup B,Responsable de Vendes,1,False,0.0,NaN,15.10,1632.0
94,Marco,Romano,10466177T,Itàlia,Firenze,8,12,1966,Home,"1,455 €",Grup A,Cap de Projecte,2,False,NaN,NaN,16.60,1455.0
530,Clara,Laurent Martin,10753570H,França,Toulouse,7,9,1981,Home,"2,696 €",Grup C,Cap de Projecte,3,False,NaN,NaN,11.70,2696.0
204,Marina,Sánchez,10889014V,Espanya,Tarragona,20,8,2000,Home,987 €,Grup A,Analista,0,False,NaN,NaN,16.20,987.0
213,Oriol,Díaz Romero,10968781V,Espanya,Tarragona,26,4,1996,Dona,935 €,Grup A,Administratiu,0,True,1000000.0,25.0,17.10,935.0
275,Noa,Costa Gómez,10969588M,Espanya,Murcia,1,2,1989,Dona,"1,682 €",Grup B,Analista,0,True,80000.0,11.4,18.20,1682.0
931,Marco,Russo Lombardi,11110324P,Itàlia,Firenze,7,8,1966,No Conegut,"1,529 €",Grup B,Analista,0,False,NaN,NaN,15.00,1529.0
476,Marina,Romero,11118688S,Espanya,A Coruña,4,5,1980,No Conegut,922 €,Grup A,Analista,0,False,NaN,NaN,13.30,922.0
904,Lucía,Moreno Costa,11212316Z,Espanya,Alacant,21,11,1985,Home,"3,070 €",Grup C,Cap de Projecte,4,False,NaN,NaN,21.80,3070.0
525,Chiara,Colombo Ferrari,11318177X,Itàlia,Venezia,3,9,1969,No Conegut,"1,939 €",Grup C,Tècnic IT,1,False,NaN,NaN,14.60,1939.0
458,Anna,Moreno,11361006M,Espanya,Zaragoza,10,3,1968,No Conegut,dos mil,Grup B,Analista,3,True,3936.0,12.9,15.32,2000.0
266,Ilaria,Colombo,11419753K,Itàlia,Napoli,18,6,1969,Dona,724 €,Grup A,Analista,4,False,NaN,NaN,19.70,724.0
472,Carmen,Gómez López,11709239K,Espanya,Girona,5,8,1979,No Conegut,dos mil,Grup B,Responsable de Vendes,1,False,NaN,NaN,14.80,2000.0
624,Alejandro,Vidal,11804855X,Espanya,Madrid,24,1,1962,Dona,1219€,Grup A,Analista,1,True,11090.0,5.0,14.80,1219.0
804,Marc,López Costa,11828041P,Espanya,Sevilla,30,8,1980,Home,2406 euros,Grup C,Responsable de Vendes,<NA>,False,NaN,NaN,16.50,2406.0
755,Jordi,Roca,12098146L,Espanya,Màlaga,11,9,1982,Home,1825 euros,Grup B,Administratiu,2,False,NaN,NaN,18.50,1825.0
100,Carlos,Muñoz Martínez,12176998P,Espanya,Alacant,5,12,1972,Home,918 €,Grup A,Tècnic IT,0,False,NaN,NaN,17.33,918.0
474,Elias,Lie,12781968G,Noruega,Trondheim,21,12,1991,Home,"1,139 €",Grup A,Tècnic IT,1,False,NaN,NaN,3.90,1139.0
228,Nil,Casals Pérez,13031322X,Espanya,Tarragona,24,10,1988,Dona,2073€,Grup C,Cap de Projecte,0,False,NaN,NaN,12.60,2073.0
716,Lucía,Soler Vila,13667070K,Espanya,Palma,25,1,1960,No Conegut,"2,343 €",Grup C,Analista,0,False,NaN,NaN,17.70,2343.0
602,Marta,Sánchez Ramos,13711597H,Espanya,Valladolid,10,7,1978,No Conegut,1844€,Grup C,Administratiu,0,True,80000.0,13.5,10.80,1844.0
399,Léa,Richard,13922081M,França,Toulouse,14,2,1963,Home,1390€,Grup B,Administratiu,0,False,NaN,NaN,13.30,1390.0
955,Jordi,Martínez Gil,13976162W,Espanya,Zaragoza,3,8,1967,Dona,n/d,Grup A,Cap de Projecte,1,False,NaN,NaN,-5.00,NaN
49,Pol,Casals,14180968R,Espanya,Barcelona,21,8,1977,Dona,"1,112 €",Grup A,Responsable de Vendes,<NA>,True,114730.0,25.0,17.10,1112.0
83,Noa,Ferrer,14237322H,Espanya,Las Palmas de Gran Canaria,8,11,1967,No Conegut,878 €,Grup A,Analista,0,False,NaN,NaN,38.00,878.0
2,Noa,Serra,14308421X,Espanya,Alacant,27,4,1961,Dona,1358 euros,Grup A,Tècnic IT,4,False,NaN,NaN,16.70,1358.0
216,Jordi,Sánchez,14497675Y,Espanya,Murcia,8,8,1982,Dona,1379€,Grup B,Responsable de Vendes,4,False,NaN,NaN,19.70,1379.0
637,Jordi,Roca Moreno,14635073C,Espanya,Las Palmas de Gran Canaria,27,10,1978,Home,2125 euros,Grup B,Cap de Projecte,2,True,11169.0,13.7,18.40,2125.0
644,Pol,Ribera Hernández,14696647A,Espanya,Zaragoza,25,5,1959,No Conegut,1.610 €,Grup B,Cap de Projecte,0,False,NaN,NaN,14.00,1610.0
750,Pau,Roca Muñoz,14804924E,Espanya,Valladolid,15,9,1992,Dona,967 €,Grup A,Responsable de Vendes,2,False,NaN,NaN,12.00,967.0
887,Anna,López,14839040C,Espanya,Alacant,23,5,1989,No Conegut,"1,072 €",Grup A,Analista,0,True,65950.0,0.5,-10.00,1072.0
674,Emil,Moen,14887763Y,Noruega,Stavanger,26,3,1989,Home,"1,501 €",Grup B,Analista,0,False,NaN,NaN,8.70,1501.0
410,Gabriele,Lombardi,14930347Y,Itàlia,Firenze,8,1,2000,No Conegut,1432€,Grup B,Analista,3,False,NaN,NaN,10.50,1432.0
339,Sergio,Álvarez,14978636K,Espanya,Màlaga,25,7,1961,Dona,tres mil,Grup A,Analista,1,False,NaN,NaN,18.10,3000.0
386,Lars,Andersen Karlsen,15087753F,Noruega,Oslo,21,4,1982,Dona,"1,546 €",Grup B,Cap de Projecte,0,False,NaN,NaN,5.80,1546.0
545,Alba,Costa,15347831A,Espanya,Las Palmas de Gran Canaria,10,8,1961,Home,903€,Grup A,Analista,3,True,NaN,NaN,20.80,903.0
59,Pau,Costa,15505975Z,Espanya,Murcia,26,9,1995,Dona,"1,242 €",Grup A,Analista,1,False,NaN,NaN,19.40,1242.0
604,Laia,Navarro,15909601K,Espanya,Bilbao,30,5,1958,Dona,"1,676 €",Grup A,Analista,1,True,50.0,NaN,14.20,1676.0
501,Emil,Hansen,16003970L,Noruega,Trondheim,23,9,1980,Home,"1,015 €",Grup A,Analista,0,False,NaN,NaN,3.90,1015.0
80,Marc,Sánchez Ribera,16072331N,Espanya,Barcelona,12,7,1981,Home,827 €,Grup A,Analista,1,False,NaN,NaN,18.40,827.0
29,Giorgio,Ricci Greco,16109013R,Itàlia,Napoli,9,3,1992,Dona,2400 euros,Grup C,Cap de Projecte,0,False,NaN,NaN,15.80,2400.0
832,Sara,Sánchez Muñoz,16121285Q,Espanya,Alacant,14,4,1960,Dona,1160€,Grup A,Cap de Projecte,2,False,NaN,NaN,18.00,1160.0
789,Riccardo,Rossi,16284386J,Itàlia,Firenze,18,5,1959,Dona,1920 euros,Grup B,Responsable de Vendes,2,True,40000.0,4.5,42.00,1920.0
592,Marta,Domènech,16415488X,Espanya,Bilbao,15,5,1973,No Conegut,3369€,Grup D,Responsable de Vendes,1,False,NaN,NaN,16.60,3369.0
772,Guillem,Vidal,16498347C,Espanya,Sevilla,13,3,1965,Home,"1,364 €",Grup B,Analista,0,False,NaN,NaN,16.70,1364.0
759,Oriol,Gómez,16618423V,Espanya,Sevilla,10,1,1968,No Conegut,"2,000 €",Grup A,Responsable de Vendes,5,False,NaN,NaN,20.70,2000.0
422,Aina,Fernández,16839113N,Espanya,Barcelona,3,4,1997,Dona,mil vuit-cents,Grup A,Tècnic IT,4,False,NaN,NaN,16.70,1800.0
198,Julien,Petit,16986408M,França,Marseille,23,10,1993,Dona,722 euros,Grup A,Cap de Projecte,<NA>,False,NaN,NaN,10.40,722.0
261,Guillem,Soler Roca,17083242X,Espanya,Girona,20,5,1995,Home,"2,309 €",Grup C,Analista,3,False,NaN,NaN,16.10,2309.0

In [76]:
# Revisar e imputar Salarios
filtro_salarios_nulos = df_revisado_salarios["Salari formatejat €"].isna()
display(df_revisado_salarios[filtro_salarios_nulos])

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat,Salari formatejat €
ID_Original,,,,,,,,,,,,,,,,,,
955,Jordi,Martínez Gil,13976162W,Espanya,Zaragoza,3,8,1967,Dona,n/d,Grup A,Cap de Projecte,1,False,NaN,NaN,-5.00,NaN
917,Claudia,Gil Fernández,19213734E,Espanya,Palma,3,7,1971,Home,n/d,Grup C,Analista,0,True,81219.0,6.6,13.30,NaN
860,Thomas,David,27341287F,França,Bordeaux,8,6,1972,No Conegut,n/d,Grup A,Tècnic IT,1,False,NaN,NaN,16.20,NaN
953,Luca,Rizzo Ferrari,28245984Z,Itàlia,Torino,29,6,2002,No Conegut,n/d,Grup A,Analista,2,False,NaN,NaN,13.60,NaN
875,Laia,Vidal Romero,39330100H,Espanya,Sevilla,24,8,2004,Dona,n/d,Grup A,Cap de Projecte,2,False,NaN,NaN,20.30,NaN
956,Alexia,Moreno Domènech,61249115R,Espanya,Zaragoza,10,5,2004,Dona,n/d,Grup A,Cap de Projecte,0,True,9017.0,0.5,13.00,NaN
159,Anna,Fernández,65446317R,Espanya,Palma,10,9,1982,Dona,n/d,Grup A,Cap de Projecte,2,False,NaN,NaN,17.27,NaN
307,David,Moreno Soler,66528833P,Espanya,Barcelona,29,9,1994,No Conegut,n/d,Grup C,Analista,0,False,NaN,NaN,18.50,NaN
446,Anna,Domènech,68131630Y,Espanya,Las Palmas de Gran Canaria,13,2,2004,Dona,n/d,Grup A,Tècnic IT,4,False,NaN,NaN,21.29,NaN
146,Luca,Gallo Ferrari,74468586Y,Itàlia,Torino,20,11,2000,Dona,n/d,Grup A,Analista,0,False,NaN,NaN,14.40,NaN
384,Pau,Ribera Díaz,81965066H,Espanya,Barcelona,23,2,1989,Dona,n/d,Grup B,Analista,0,False,NaN,NaN,13.40,NaN
291,Thomas,Lefebvre Moreau,85300576W,França,Lille,28,8,1977,No Conegut,n/d,Grup C,Analista,4,False,NaN,NaN,12.90,NaN
254,Zoé,Thomas Dubois,89260394J,França,Marseille,13,8,1992,Home,n/d,Grup A,Analista,2,False,NaN,NaN,20.60,NaN

In [77]:
# Ver Salarios según Grupo Profesional y Cargo
df_revisado_salarios.groupby(['Grup Professional', 'Càrrec'])['Salari formatejat €'].mean().round(2).reset_index()

   Grup Professional                 Càrrec  Salari formatejat €
0             Grup A          Administratiu               995.23
1             Grup A               Analista              1113.12
2             Grup A        Cap de Projecte              1200.28
3             Grup A  Responsable de Vendes              1088.08
4             Grup A              Tècnic IT              1155.21
5             Grup B          Administratiu              1521.80
6             Grup B               Analista              1641.26
7             Grup B        Cap de Projecte              1846.74
8             Grup B  Responsable de Vendes              1658.87
9             Grup B              Tècnic IT              1588.44
10            Grup C          Administratiu              2208.28
11            Grup C               Analista              2341.65
12            Grup C        Cap de Projecte              2624.67
13            Grup C  Responsable de Vendes              2411.12
14            Grup C              Tècnic IT              2311.07
15            Grup D          Administratiu              2900.50
16            Grup D               Analista              3232.81
17            Grup D        Cap de Projecte              3508.25
18            Grup D  Responsable de Vendes              3066.83
19            Grup D              Tècnic IT              3142.12

In [78]:
# Imputar Salarios según Grupo Profesioal y Cargo
def imputar_salarios(df):
  """
  Imputa los valores de la columna 'Salari formatejat €' según el Grupo Profesional y el Cargo.
  """
  columnas_requeridas = {'Salari formatejat €', 'Grup Professional', 'Càrrec'}

  if df is None or not columnas_requeridas.issubset(df.columns):
    return df

  df_salarios_ok = df.copy()

  filtro_salario_ko = df_salarios_ok['Salari formatejat €'].isna()
  salarios_medios = df_salarios_ok.groupby(['Grup Professional', 'Càrrec'])['Salari formatejat €'].transform('mean').round(2)
  df_salarios_ok.loc[filtro_salario_ko, 'Salari formatejat €'] = salarios_medios[filtro_salario_ko]

  print(f"Se han actualizado {filtro_salario_ko.sum()} registros de Salarios.\n")

  return df_salarios_ok

df_imputado_salarios = imputar_salarios(df_revisado_salarios)
display(df_imputado_salarios.info())

Se han actualizado 13 registros de Salarios.

<class 'pandas.core.frame.DataFrame'>
Index: 929 entries, 195 to 24
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Nom                         929 non-null    object
 1   Cognoms                     929 non-null    object
 2   DNI                         929 non-null    object
 3   País d'origen               929 non-null    object
 4   Ciutat                      929 non-null    object
 5   Dia de Naixement            929 non-null    Int64
 6   Mes de Naixement            929 non-null    Int64
 7   Any de Naixement            929 non-null    Int64
 8   Gènere                      929 non-null    object
 9   Salari mensual              929 non-null    object
 10  Grup Professional           929 non-null    object
 11  Càrrec                      929 non-null    object
 12  Nombre_fills                900 non-null    Int64
 13  Te_cotxe                    929 non-null    object
 14  Km_anuals                   287 non-null    float64
 15  Consum_mitja_L_100km        240 non-null    float64
 16  Temperatura_mitjana_ciutat  929 non-null    float64
 17  Salari formatejat €         929 non-null    float64
dtypes: Int64(4), float64(4), object(10)
memory usage: 141.5+ KB

None

## N1.4: Análisis Descriptivas

- Tabla descriptiva de Salarios por Género
- Tabla de Salarios por Género (filas) y País (columnas)
- Ver Porcentajes vs. Valores Absolutos

In [79]:
# Reordeno y Renombro Columnas para el análisis
columnas_ordenadas = [
    "Nom",
    "Cognoms",
    "DNI",
    "Dia_Naixement",
    "Mes_Naixement",
    "Any_Naixement",
    "Genere",
    "Pais_Origen",
    "Ciutat",
    "Num_Fills",
    "Grup_Professional",
    "Carrec",
    "Salari_Mensual_Euros",
    "Te_Cotxe",
    "Km_Anuals",
    "Consum_Mitja",
    "Temperatura_Mitja"]

df_preparado = df_imputado_salarios.rename(columns={"País d'origen": "Pais_Origen",
                "Dia de Naixement": "Dia_Naixement",
                "Mes de Naixement": "Mes_Naixement",
                "Any de Naixement": "Any_Naixement",
                "Gènere": "Genere",
                "Grup Professional": "Grup_Professional",
                "Càrrec": "Carrec",
                "Nombre_fills": "Num_Fills",
                "Te_cotxe": "Te_Cotxe",
                "Km_anuals": "Km_Anuals",
                "Consum_mitja_L_100km": "Consum_Mitja",
                "Temperatura_mitjana_ciutat": "Temperatura_Mitja",
                "Salari formatejat €": "Salari_Mensual_Euros" }).drop(columns=["Salari mensual"])[columnas_ordenadas]

display(df_preparado.info())
display(df_preparado.head(10))

<class 'pandas.core.frame.DataFrame'>
Index: 929 entries, 195 to 24
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Nom                   929 non-null    object
 1   Cognoms               929 non-null    object
 2   DNI                   929 non-null    object
 3   Dia_Naixement         929 non-null    Int64
 4   Mes_Naixement         929 non-null    Int64
 5   Any_Naixement         929 non-null    Int64
 6   Genere                929 non-null    object
 7   Pais_Origen           929 non-null    object
 8   Ciutat                929 non-null    object
 9   Num_Fills             900 non-null    Int64
 10  Grup_Professional     929 non-null    object
 11  Carrec                929 non-null    object
 12  Salari_Mensual_Euros  929 non-null    float64
 13  Te_Cotxe              929 non-null    object
 14  Km_Anuals             287 non-null    float64
 15  Consum_Mitja          240 non-null    float64
 16  Temperatura_Mitja     929 non-null    float64
dtypes: Int64(4), float64(4), object(9)
memory usage: 134.3+ KB

None

,Nom,Cognoms,DNI,Dia_Naixement,Mes_Naixement,Any_Naixement,Genere,Pais_Origen,Ciutat,Num_Fills,Grup_Professional,Carrec,Salari_Mensual_Euros,Te_Cotxe,Km_Anuals,Consum_Mitja,Temperatura_Mitja
ID_Original,,,,,,,,,,,,,,,,,
195,Claudia,Pujol Torres,10161088K,27,9,1996,Home,Espanya,Las Palmas de Gran Canaria,0,Grup A,Tècnic IT,946.0,False,NaN,NaN,22.7
270,Oriol,Torres Vila,10443906N,8,9,1962,Dona,Espanya,Tarragona,1,Grup B,Responsable de Vendes,1632.0,False,0.0,NaN,15.1
94,Marco,Romano,10466177T,8,12,1966,Home,Itàlia,Firenze,2,Grup A,Cap de Projecte,1455.0,False,NaN,NaN,16.6
530,Clara,Laurent Martin,10753570H,7,9,1981,Home,França,Toulouse,3,Grup C,Cap de Projecte,2696.0,False,NaN,NaN,11.7
204,Marina,Sánchez,10889014V,20,8,2000,Home,Espanya,Tarragona,0,Grup A,Analista,987.0,False,NaN,NaN,16.2
213,Oriol,Díaz Romero,10968781V,26,4,1996,Dona,Espanya,Tarragona,0,Grup A,Administratiu,935.0,True,1000000.0,25.0,17.1
275,Noa,Costa Gómez,10969588M,1,2,1989,Dona,Espanya,Murcia,0,Grup B,Analista,1682.0,True,80000.0,11.4,18.2
931,Marco,Russo Lombardi,11110324P,7,8,1966,No Conegut,Itàlia,Firenze,0,Grup B,Analista,1529.0,False,NaN,NaN,15.0
476,Marina,Romero,11118688S,4,5,1980,No Conegut,Espanya,A Coruña,0,Grup A,Analista,922.0,False,NaN,NaN,13.3
904,Lucía,Moreno Costa,11212316Z,21,11,1985,Home,Espanya,Alacant,4,Grup C,Cap de Projecte,3070.0,False,NaN,NaN,21.8

In [82]:
# Tabla descriptiva de Salarios por Género
tabla_salarios_genero = (
    df_preparado.groupby('Genere')['Salari_Mensual_Euros']
    .describe()
    .round(2)
    .sort_values(by='mean', ascending=False))

display(tabla_salarios_genero)

            count     mean     std    min     25%     50%     75%     max
Genere
Home        293.0  1669.46  691.79  751.0  1126.0  1455.0  2028.0  3672.0
No Conegut  239.0  1566.22  643.41  673.0  1072.0  1367.0  1939.0  3672.0
Dona        397.0  1487.52  543.63  701.0  1073.0  1379.0  1778.0  3564.0

In [94]:
# Salarios por Género y País

tabla_genero_paises = pd.crosstab(
    index=df_preparado['Genere'],
    columns=df_preparado['Pais_Origen'],
    values=df_preparado['Salari_Mensual_Euros'],
    aggfunc='mean',
    margins=True,                  # Exactament el mateix paràmetre
    margins_name='Mitjana Global'
).round(2)

# display(tabla_genero_paises.style.background_gradient(cmap='Blues'))

lista_paises = sorted(df_preparado['Pais_Origen'].unique())
parte_coloreada = pd.IndexSlice[tabla_genero_paises.index[:-1], lista_paises]

tabla_con_estilo = (tabla_genero_paises.style
                    .background_gradient(subset=parte_coloreada,
                                         cmap='Blues')
                    .format(precision=2) )

display(tabla_con_estilo)